In [1]:
!pip install -U llama-cpp-python

Collecting llama-cpp-python
  Downloading llama_cpp_python-0.3.35.tar.gz (74.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.9/74.9 MB 21.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (4.15.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (2.0.2)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.3->llama-cpp-python) (3.0.3)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.1 MB/s eta 0:00:00
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.3.35-py3-none-linux_x86_64.whl size=20848303 sha256=86e890bd18c5c1c6b604f8a2f16174f7b5fb5b592a59744b9bc721a3c2b595b6
  Stored in directory: /root/.cache/pip/wheels/1b/64/d4/17744d793e69b485a7664ef47b18e402a72a6e08e84f7b9926
Successfully built llama-cpp-python
Installing collected packages: diskcache, llama-cpp-python
Successfully installed diskcache-5.6.3 llama-cpp-python-0.3.35

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/wangapa106g/massage-analysis/test_50_consistent.csv

In [3]:

from llama_cpp import Llama

llm = Llama.from_pretrained(
	repo_id="EngineerWanga0791709020/SME-Ledger",
	filename="sme-ledger-v2-Q4_K_M.gguf",
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `hf_hub_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

./sme-ledger-v2-Q4_K_M.gguf:   0%|          | 0.00/261M [00:00<?, ?B/s]

llama_model_loader: loaded meta data with 33 key-value pairs and 236 tensors from /root/.cache/huggingface/hub/models--EngineerWanga0791709020--SME-Ledger/snapshots/1aa4d6566c59f07727d7a814269122c8f037dd09/./sme-ledger-v2-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                     general.sampling.top_k i32              = 64
llama_model_loader: - kv   3:                     general.sampling.top_p f32              = 0.950000
llama_model_loader: - kv   4:                               general.name str              = Merged
llama_model_loader: - kv   5:                         general.size_label str              = 268M
llama_model_loader: - kv   6:                         gemma3.block_count u32              = 18
llama_model_loader: - kv   7:                      gemma3.context_length u32              = 32768
llama_model_loader: - kv   8:                    gemma3.embedding_length u32              = 640
llama_model_loader: - kv   9:                 gemma3.feed_forward_length u32              = 2048
llama_model_loader: - kv  10:                gemma3.attention.head_count u32              = 4
llama_model_loader: - kv  11:             gemma3.attention.head_count_kv u32              = 1
llama_model_loader: - kv  12:                      gemma3.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                  gemma3.rope.freq_base_swa f32              = 10000.000000
llama_model_loader: - kv  14:    gemma3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  15:                gemma3.attention.key_length u32              = 256
llama_model_loader: - kv  16:              gemma3.attention.value_length u32              = 256
llama_model_loader: - kv  17:            gemma3.attention.sliding_window u32              = 512
llama_model_loader: - kv  18:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  19:                         tokenizer.ggml.pre str              = granite-embed-multi-311m
llama_model_loader: - kv  20:                      tokenizer.ggml.tokens arr[str,262144]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  21:                  tokenizer.ggml.token_type arr[i32,262144]  = [3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  22:                      tokenizer.ggml.merges arr[str,514906]  = ["\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n", ...
llama_model_loader: - kv  23:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  24:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  25:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  26:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  27:               tokenizer.ggml.mask_token_id u32              = 4
llama_model_loader: - kv  28:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  29:               tokenizer.ggml.add_sep_token bool             = false
llama_model_loader: - kv  30:                    tokenizer.chat_template str              = {{ bos_token }}\n{%- if messages[0]['r...
llama_model_loader: - kv  31:               general.quantization_version u32              = 2
llama_model_loader: - kv  32:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  109 tensors
llama_model_loader: - type q5_0:   81 tensors
llama_model_loader: - type q8_0:   10 tensors
llama_model_loader: - type q4_K:   27 tensors
llama_model_loader: - type q6_K:    9 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 235.16 MiB (7.36 BPW)
init_tokenizer: initializing tokenizer for type 2
load: 6242 unused tokens
load: control token: 256000 '<end_of_image>' is not marked as EOG
load: control token: 255999 '<start_of_image>' is not marked as EOG
load: control token:    105 '<start_of_turn>' is not marked as EOG
load: control token:      2 '<bos>' is not marked as EOG
load: control-looking token:    212 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token:      0 '<pad>' is not marked as EOG
load: control token:      3 '<unk>' is not marked as EOG
load: control token:      4 '<mask>' is not marked as EOG
load: printing all EOG tokens:
load:   - 1 ('<eos>')
load:   - 106 ('<end_of_turn>')
load:   - 212 ('</s>')
load: special tokens cache size = 6414
load: token to piece cache size = 1.9458 MB
print_info: arch                  = gemma3
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 32768
print_info: n_embd_inp            = 640
print_info: n_embd                = 640
print_info: n_embd_out            = 640
print_info: n_layer               = 18
print_info: n_layer_all           = 18
print_info: n_head                = 4
print_info: n_head_kv             = 1
print_info: n_rot                 = 256
print_info: n_swa                 = 512
print_info: is_swa_any            = 1
print_info: n_embd_head_k         = 256
print_info: n_embd_head_v         = 256
print_info: n_gqa                 = 4
print_info: n_embd_k_gqa          = 256
print_info: n_embd_v_gqa          = 256
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-06
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 6.2e-02
print_info: f_attn_value_scale    = 0.0000
print_info: n_ff                  = 2048
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 2
print_info: rope scaling          = linear
print_info: freq_base_train       = 1000000.0
print_info: freq_scale_train      = 1
print_info: freq_base_swa         = 10000.0
print_info: freq_scale_swa        = 1
print_info: n_embd_head_k_swa     = 256
print_info: n_embd_head_v_swa     = 256
print_info: n_rot_swa             = 256
print_info: n_ctx_orig_yarn       = 32768
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = 270M
print_info: model params          = 268.10 M
print_info: general.name          = Merged
print_info: vocab type            = BPE
print_info: n_vocab               = 262144
print_info: n_merges              = 514906
print_info: BOS token             = 2 '<bos>'
print_info: EOS token             = 1 '<eos>'
print_info: EOT token             = 106 '<end_of_turn>'
print_info: UNK token             = 3 '<unk>'
print_info: PAD token             = 0 '<pad>'
print_info: MASK token            = 4 '<mask>'
print_info: LF token              = 107 '
'
print_info: EOG token             = 1 '<eos>'
print_info: EOG token             = 106 '<end_of_turn>'
print_info: EOG token             = 212 '</s>'
print_info: max token length      = 48
load_tensors: loading model tensors, this can take a while... (load_mode = mmap)
load_tensors: layer   0 assigned to device CPU, is_swa = 1
load_tensors: layer   1 assigned to device CPU, is_swa = 1
load_tensors: layer   2 assigned to device CPU, is_swa = 1
load_tensors: layer   3 assigned to device CPU, is_swa = 1
load_tensors: layer   4 assigned to device CPU, is_swa = 1
load_tensors: layer   5 assigned to device CPU, is_swa = 0
load_tensors: layer   6 assigned to device CPU, is_swa = 1
load_tensors: layer   7 assigned to device CPU, is_swa = 1
load_tensors: layer   8 assigned to device CPU, is_swa = 1
load_tensors: layer   9 assigned to device CPU, is_swa = 1
load_tensors: layer  10 assigned to device CPU, is_swa = 1
load_tensors: layer  11 assigned to device CPU, is_swa = 0
load_tensors: layer  12 assigned to device CPU, is_swa = 1
load_tensors: layer  13 assigned to device CPU, is_swa = 1
load_tensors: layer  14 assigned to device CPU, is_swa = 1
load_tensors: layer  15 assigned to device CPU, is_swa = 1
load_tensors: layer  16 assigned to device CPU, is_swa = 1
load_tensors: layer  17 assigned to device CPU, is_swa = 0
load_tensors: layer  18 assigned to device CPU, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor output.weight
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor dense_2.weight
create_tensor: loading tensor dense_3.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_qkv.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_q.bias
create_tensor: loading tensor blk.0.attn_k.bias
create_tensor: loading tensor blk.0.attn_v.bias
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.post_attention_norm.weight
create_tensor: loading tensor blk.0.attn_k_norm.weight
create_tensor: loading tensor blk.0.attn_q_norm.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.post_ffw_norm.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_qkv.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_q.bias
create_tensor: loading tensor blk.1.attn_k.bias
create_tensor: loading tensor blk.1.attn_v.bias
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.post_attention_norm.weight
create_tensor: loading tensor blk.1.attn_k_norm.weight
create_tensor: loading tensor blk.1.attn_q_norm.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.post_ffw_norm.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_qkv.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_q.bias
create_tensor: loading tensor blk.2.attn_k.bias
create_tensor: loading tensor blk.2.attn_v.bias
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.post_attention_norm.weight
create_tensor: loading tensor blk.2.attn_k_norm.weight
create_tensor: loading tensor blk.2.attn_q_norm.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.post_ffw_norm.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_qkv.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_q.bias
create_tensor: loading tensor blk.3.attn_k.bias
create_tensor: loading tensor blk.3.attn_v.bias
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.post_attention_norm.weight
create_tensor: loading tensor blk.3.attn_k_norm.weight
create_tensor: loading tensor blk.3.attn_q_norm.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.post_ffw_norm.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_qkv.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_q.bias
create_tensor: loading tensor blk.4.attn_k.bias
create_tensor: loading tensor blk.4.attn_v.bias
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.post_attention_norm.weight
create_tensor: loading tensor blk.4.attn_k_norm.weight
create_tensor: loading tensor blk.4.attn_q_norm.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.post_ffw_norm.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_qkv.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_q.bias
create_tensor: loading tensor blk.5.attn_k.bias
create_tensor: loading tensor blk.5.attn_v.bias
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.post_attention_norm.weight
create_tensor: loading tensor blk.5.attn_k_norm.weight
create_tensor: loading tensor blk.5.attn_q_norm.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.post_ffw_norm.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_qkv.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_q.bias
create_tensor: loading tensor blk.6.attn_k.bias
create_tensor: loading tensor blk.6.attn_v.bias
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.post_attention_norm.weight
create_tensor: loading tensor blk.6.attn_k_norm.weight
create_tensor: loading tensor blk.6.attn_q_norm.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.post_ffw_norm.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_qkv.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_q.bias
create_tensor: loading tensor blk.7.attn_k.bias
create_tensor: loading tensor blk.7.attn_v.bias
create_tensor: loading tensor blk.7.attn_output.weight
create_tensor: loading tensor blk.7.post_attention_norm.weight
create_tensor: loading tensor blk.7.attn_k_norm.weight
create_tensor: loading tensor blk.7.attn_q_norm.weight
create_tensor: loading tensor blk.7.ffn_norm.weight
create_tensor: loading tensor blk.7.ffn_gate.weight
create_tensor: loading tensor blk.7.ffn_up.weight
create_tensor: loading tensor blk.7.ffn_down.weight
create_tensor: loading tensor blk.7.post_ffw_norm.weight
create_tensor: loading tensor blk.8.attn_norm.weight
create_tensor: loading tensor blk.8.attn_qkv.weight
create_tensor: loading tensor blk.8.attn_q.weight
create_tensor: loading tensor blk.8.attn_k.weight
create_tensor: loading tensor blk.8.attn_v.weight
create_tensor: loading tensor blk.8.attn_q.bias
create_tensor: loading tensor blk.8.attn_k.bias
create_tensor: loading tensor blk.8.attn_v.bias
create_tensor: loading tensor blk.8.attn_output.weight
create_tensor: loading tensor blk.8.post_attention_norm.weight
create_tensor: loading tensor blk.8.attn_k_norm.weight
create_tensor: loading tensor blk.8.attn_q_norm.weight
create_tensor: loading tensor blk.8.ffn_norm.weight
create_tensor: loading tensor blk.8.ffn_gate.weight
create_tensor: loading tensor blk.8.ffn_up.weight
create_tensor: loading tensor blk.8.ffn_down.weight
create_tensor: loading tensor blk.8.post_ffw_norm.weight
create_tensor: loading tensor blk.9.attn_norm.weight
create_tensor: loading tensor blk.9.attn_qkv.weight
create_tensor: loading tensor blk.9.attn_q.weight
create_tensor: loading tensor blk.9.attn_k.weight
create_tensor: loading tensor blk.9.attn_v.weight
create_tensor: loading tensor blk.9.attn_q.bias
create_tensor: loading tensor blk.9.attn_k.bias
create_tensor: loading tensor blk.9.attn_v.bias
create_tensor: loading tensor blk.9.attn_output.weight
create_tensor: loading tensor blk.9.post_attention_norm.weight
create_tensor: loading tensor blk.9.attn_k_norm.weight
create_tensor: loading tensor blk.9.attn_q_norm.weight
create_tensor: loading tensor blk.9.ffn_norm.weight
create_tensor: loading tensor blk.9.ffn_gate.weight
create_tensor: loading tensor blk.9.ffn_up.weight
create_tensor: loading tensor blk.9.ffn_down.weight
create_tensor: loading tensor blk.9.post_ffw_norm.weight
create_tensor: loading tensor blk.10.attn_norm.weight
create_tensor: loading tensor blk.10.attn_qkv.weight
create_tensor: loading tensor blk.10.attn_q.weight
create_tensor: loading tensor blk.10.attn_k.weight
create_tensor: loading tensor blk.10.attn_v.weight
create_tensor: loading tensor blk.10.attn_q.bias
create_tensor: loading tensor blk.10.attn_k.bias
create_tensor: loading tensor blk.10.attn_v.bias
create_tensor: loading tensor blk.10.attn_output.weight
create_tensor: loading tensor blk.10.post_attention_norm.weight
create_tensor: loading tensor blk.10.attn_k_norm.weight
create_tensor: loading tensor blk.10.attn_q_norm.weight
create_tensor: loading tensor blk.10.ffn_norm.weight
create_tensor: loading tensor blk.10.ffn_gate.weight
create_tensor: loading tensor blk.10.ffn_up.weight
create_tensor: loading tensor blk.10.ffn_down.weight
create_tensor: loading tensor blk.10.post_ffw_norm.weight
create_tensor: loading tensor blk.11.attn_norm.weight
create_tensor: loading tensor blk.11.attn_qkv.weight
create_tensor: loading tensor blk.11.attn_q.weight
create_tensor: loading tensor blk.11.attn_k.weight
create_tensor: loading tensor blk.11.attn_v.weight
create_tensor: loading tensor blk.11.attn_q.bias
create_tensor: loading tensor blk.11.attn_k.bias
create_tensor: loading tensor blk.11.attn_v.bias
create_tensor: loading tensor blk.11.attn_output.weight
create_tensor: loading tensor blk.11.post_attention_norm.weight
create_tensor: loading tensor blk.11.attn_k_norm.weight
create_tensor: loading tensor blk.11.attn_q_norm.weight
create_tensor: loading tensor blk.11.ffn_norm.weight
create_tensor: loading tensor blk.11.ffn_gate.weight
create_tensor: loading tensor blk.11.ffn_up.weight
create_tensor: loading tensor blk.11.ffn_down.weight
create_tensor: loading tensor blk.11.post_ffw_norm.weight
create_tensor: loading tensor blk.12.attn_norm.weight
create_tensor: loading tensor blk.12.attn_qkv.weight
create_tensor: loading tensor blk.12.attn_q.weight
create_tensor: loading tensor blk.12.attn_k.weight
create_tensor: loading tensor blk.12.attn_v.weight

In [4]:
# ============================================================
# SME-LEDGER V2 — MANUAL 20-SAMPLE EVALUATION
#
# You manually judge:
#   - JSON validity
#   - Correctness
#   - Missing information handling
#   - Capability answers
#
# This script ONLY shows:
#   1. Prompt given to model
#   2. Model response
#   3. Latency
#
# No automatic JSON scoring.
# ============================================================

import json
import time
from datetime import datetime


# ============================================================
# 20 TEST CASES
# ============================================================

TESTS = [

    # ========================================================
    # CATEGORY 1 — VALID TRANSACTIONS (8)
    # ========================================================

    {
        "id": "valid_01",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract the financial transaction below.

Return ONLY valid JSON with exactly these fields:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Rules:
- amount, balance and fee must be numbers.
- type must be income, expense, or unknown.
- date must be YYYY-MM-DD.
- Do not invent missing information.
- Use null when information is unavailable.
- No markdown.
- No explanation.

SMS:
QGH7K3M2P1 Confirmed. You have received Ksh20,000.00 from Ann Mueni 0712***456 on 05/03/2026 at 10:42 AM. New M-PESA balance is Ksh159,583.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_02",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this M-Pesa payment.

Return ONLY JSON with:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent missing information. Use null where necessary.

SMS:
TLA82K9P4Q Confirmed. Ksh1,250.00 paid to Naivas Supermarket on 06/03/2026 at 14:21. New M-PESA balance is Ksh158,333.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_03",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this M-Pesa Till transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
RTP93LMN72 Confirmed. Ksh3,500.00 paid to 123456 - Wanga Electronics via M-PESA Till Number on 07/03/2026 at 09:15 AM. New M-PESA balance is Ksh154,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_04",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this PayBill transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
PBY72LK91A Confirmed. Ksh5,000.00 sent to KPLC via PayBill 88888 for account 123456789 on 08/03/2026 at 18:03. New M-PESA balance is Ksh149,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_05",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this bank transfer received.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
BNK72PQ91 Confirmed. Ksh45,000.00 received in your M-PESA account from Equity Bank on 09/03/2026 at 11:30 AM. New M-PESA balance is Ksh194,833.00. Reference EQT98431.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_06",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this Fuliza transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
FUL123ABC Confirmed. Fuliza loan of Ksh10,000.00 received on 10/03/2026 at 08:05 AM. New M-PESA balance is Ksh204,833.00. Fuliza outstanding balance is Ksh10,000.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_07",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this cash withdrawal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
WD91KLM22 Confirmed. Ksh8,000.00 withdrawn from M-PESA at Agent 456789 - John Kamau on 11/03/2026 at 16:40. Transaction cost, Ksh80.00. New M-PESA balance is Ksh196,753.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_08",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this reversal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
REV8821 Confirmed. Reversal of Ksh2,500.00 for transaction QWE12345 has been credited to your M-PESA account on 12/03/2026 at 13:22. New M-PESA balance is Ksh199,253.00.

Return ONLY JSON.
"""
    },


    # ========================================================
    # CATEGORY 2 — MISSING / AMBIGUOUS DATA (6)
    # ========================================================

    {
        "id": "missing_01",
        "category": "missing_data",
        "task": "Handle missing balance",
        "prompt": """
Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for information that is not present.
Do not guess.

SMS:
ABC12345 Confirmed. You have received Ksh7,500.00 from Mary Wanjiku on 13/03/2026 at 09:10 AM.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_02",
        "category": "missing_data",
        "task": "Handle missing transaction ID",
        "prompt": """
Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for missing information.

SMS:
You paid Ksh2,000.00 to Green Valley Shop on 14/03/2026 at 15:20. New M-PESA balance is Ksh197,253.00.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_03",
        "category": "missing_data",
        "task": "Handle missing entity",
        "prompt": """
Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent an entity.

SMS:
TX99821 Confirmed. Ksh3,200.00 paid via M-PESA on 15/03/2026 at 12:00 PM. New M-PESA balance is Ksh194,053.00.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_04",
        "category": "missing_data",
        "task": "Ambiguous transaction",
        "prompt": """
Determine what can safely be extracted from this message.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null when information is ambiguous or missing.
Do not invent facts.

SMS:
TX7712 Confirmed. Ksh5,000 sent. Balance Ksh100,000.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_05",
        "category": "missing_data",
        "task": "Noisy SMS",
        "prompt": """
Extract the transaction from this noisy SMS.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Ignore irrelevant text.
Do not invent missing information.

SMS:
M-PESA ALERT!!! Your account was updated. TX88K21 Confirmed. You received Ksh12,000 from Peter on 16/03/2026. Please do not share your PIN. New balance Ksh112,000.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_06",
        "category": "missing_data",
        "task": "Conflicting information",
        "prompt": """
Extract this transaction carefully.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

If the message contains conflicting information, preserve only what can be determined safely and use null where necessary.

SMS:
TX5566 Confirmed. Ksh4,000 paid to ABC Shop on 17/03/2026. New M-PESA balance is Ksh90,000. Later message says transaction amount was Ksh5,000.

Return ONLY JSON.
"""
    },


    # ========================================================
    # CATEGORY 3 — CAPABILITY / SELF-KNOWLEDGE (6)
    # ========================================================

    {
        "id": "capability_01",
        "category": "capability",
        "task": "Capabilities",
        "prompt": """
What types of financial transaction messages are you designed to understand?

Mention the transaction categories you can identify.

Answer concisely.
"""
    },

    {
        "id": "capability_02",
        "category": "capability",
        "task": "Supported fields",
        "prompt": """
What information can you extract from an M-Pesa or bank transaction message?

List the fields you are designed to identify.
"""
    },

    {
        "id": "capability_03",
        "category": "capability",
        "task": "Missing information",
        "prompt": """
What do you do when a financial SMS is missing important information such as the transaction ID, entity, balance, date, or amount?
"""
    },

    {
        "id": "capability_04",
        "category": "capability",
        "task": "Unsupported claims",
        "prompt": """
Can you access a user's bank account, M-Pesa account, contacts, internet, or private financial records directly?

Explain what you can and cannot access.
"""
    },

    {
        "id": "capability_05",
        "category": "capability",
        "task": "Role",
        "prompt": """
What is your role in the SME Ledger system?

Explain what happens after you extract a transaction from an SMS.
"""
    },

    {
        "id": "capability_06",
        "category": "capability",
        "task": "Transaction types",
        "prompt": """
Can you distinguish between income, expenses, transfers, withdrawals, merchant payments, PayBill payments, Fuliza transactions, reversals, and failed transactions?

If yes, briefly explain how.
"""
    }
]


# ============================================================
# RUN MODEL
# ============================================================

def run_model(prompt, max_tokens=256):

    start = time.time()

    try:

        response = llm.create_chat_completion(
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0,
            top_p=1,
            seed=42,
            max_tokens=max_tokens
        )

        elapsed = time.time() - start

        text = response["choices"][0]["message"]["content"]

        return text.strip(), round(elapsed, 3), None

    except Exception as e:

        elapsed = time.time() - start

        return "", round(elapsed, 3), str(e)


# ============================================================
# RUN 20 TESTS
# ============================================================

results = []

print("\n")
print("=" * 90)
print("                 SME-LEDGER V2 — MANUAL 20-TEST EVALUATION")
print("=" * 90)


for i, test in enumerate(TESTS, start=1):

    print("\n\n")
    print("█" * 90)
    print(f"TEST {i}/20")
    print(f"ID       : {test['id']}")
    print(f"CATEGORY : {test['category']}")
    print(f"TASK     : {test['task']}")
    print("█" * 90)

    # --------------------------------------------------------
    # PROMPT
    # --------------------------------------------------------

    print("\n")
    print("┌" + "─" * 88 + "┐")
    print("│ PROMPT GIVEN TO MODEL")
    print("└" + "─" * 88 + "┘")

    print(test["prompt"])

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    response, latency, error = run_model(test["prompt"])

    print("\n")
    print("┌" + "─" * 88 + "┐")
    print("│ MODEL RESPONSE")
    print("└" + "─" * 88 + "┘")

    if error:
        print("❌ ERROR:")
        print(error)
    else:
        print(response)

    print("\n")
    print(f"⏱️  Latency: {latency:.3f} seconds")

    # --------------------------------------------------------
    # Store raw result
    # --------------------------------------------------------

    results.append({
        "test_number": i,
        "id": test["id"],
        "category": test["category"],
        "task": test["task"],
        "prompt": test["prompt"],
        "response": response,
        "latency_seconds": latency,
        "error": error
    })


# ============================================================
# SAVE RAW RESULTS
# ============================================================

OUTPUT_FILE = "sme_ledger_20_manual_test_results.json"

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:

    json.dump(
        {
            "evaluation": {
                "name": "SME-Ledger V2 Manual 20-Test Evaluation",
                "model": "sme-ledger-v2-Q4_K_M.gguf",
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "seed": 42
            },
            "results": results
        },
        f,
        indent=2,
        ensure_ascii=False
    )


# ============================================================
# FINAL RUN SUMMARY
# ============================================================

successful = sum(
    r["error"] is None
    for r in results
)

average_latency = sum(
    r["latency_seconds"]
    for r in results
) / len(results)


print("\n\n")
print("=" * 90)
print("                         TEST RUN COMPLETE")
print("=" * 90)

print(f"""
Tests executed:       {len(results)}/20
Successful runs:      {successful}/20
Average latency:      {average_latency:.3f} seconds

No automatic correctness or JSON validation was performed.
You are the evaluator.
""")

print(f"Raw results saved to: {OUTPUT_FILE}")
print("=" * 90)

==========================================================================================
                 SME-LEDGER V2 — MANUAL 20-TEST EVALUATION
==========================================================================================



██████████████████████████████████████████████████████████████████████████████████████████
TEST 1/20
ID       : valid_01
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the financial transaction below.

Return ONLY valid JSON with exactly these fields:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Rules:
- amount, balance and fee must be numbers.
- type must be income, expense, or unknown.
- date must be YYYY-MM-DD.
- Do not invent missing information.
- Use null when information is unavailable.
- No markdown.
- No explanation.

SMS:
QGH7K3M2P1 Confirmed. You have received Ksh20,000.00 from Ann Mueni 0712***456 on 05/03/2026 at 10:42 AM. New M-PESA balance is Ksh159,583.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     663.24 ms /   209 tokens (    3.17 ms per token,   315.12 tokens per second)
llama_perf_context_print:        eval time =    2119.15 ms /    93 runs   (   22.79 ms per token,    43.89 tokens per second)
llama_perf_context_print:       total time =    2903.95 ms /   302 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 5 prefix-match hit, remaining 136 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: QGH7K3M2P1
date: 2026-03-05
time: 10:42
type: Income
domain: bank_transfer_receive_money
entity: Ann Mueni
amount: 20000.0
balance: 0.0
fee: 0.0
reference: QGH7K3M2P1


⏱️  Latency: 2.910 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 2/20
ID       : valid_02
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this M-Pesa payment.

Return ONLY JSON with:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent missing information. Use null where necessary.

SMS:
TLA82K9P4Q Confirmed. Ksh1,250.00 paid to Naivas Supermarket on 06/03/2026 at 14:21. New M-PESA balance is Ksh158,333.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     434.32 ms /   136 tokens (    3.19 ms per token,   313.14 tokens per second)
llama_perf_context_print:        eval time =    2156.15 ms /    95 runs   (   22.70 ms per token,    44.06 tokens per second)
llama_perf_context_print:       total time =    2718.14 ms /   231 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 10 prefix-match hit, remaining 133 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: TLA82K9P4Q
date: 2026-03-06
time: 14:21
type: Expense
domain: M-PESA
entity: Naivas Supermarket
amount: 1250.0
balance: 158333.0
fee: 0.0
reference: TLA82K9P4Q


⏱️  Latency: 2.724 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 3/20
ID       : valid_03
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this M-Pesa Till transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
RTP93LMN72 Confirmed. Ksh3,500.00 paid to 123456 - Wanga Electronics via M-PESA Till Number on 07/03/2026 at 09:15 AM. New M-PESA balance is Ksh154,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     428.62 ms /   133 tokens (    3.22 ms per token,   310.29 tokens per second)
llama_perf_context_print:        eval time =    2139.67 ms /    95 runs   (   22.52 ms per token,    44.40 tokens per second)
llama_perf_context_print:       total time =    2694.19 ms /   228 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 6 prefix-match hit, remaining 138 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: SMS-RTP93LMN72; date: 07/03/2026; time: 09:15; type: M-PESA; domain: till_payment; entity: Wanga Electronics; amount: 3500.0; balance: 154833.0; fee: 0.0; reference: RTP93LMN72


⏱️  Latency: 2.700 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 4/20
ID       : valid_04
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this PayBill transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
PBY72LK91A Confirmed. Ksh5,000.00 sent to KPLC via PayBill 88888 for account 123456789 on 08/03/2026 at 18:03. New M-PESA balance is Ksh149,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     435.60 ms /   138 tokens (    3.16 ms per token,   316.81 tokens per second)
llama_perf_context_print:        eval time =    2168.79 ms /    97 runs   (   22.36 ms per token,    44.73 tokens per second)
llama_perf_context_print:       total time =    2731.60 ms /   235 tokens
llama_perf_context_print:    graphs reused =         96
Llama.generate: 6 prefix-match hit, remaining 125 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: PBY72LK91A
date: 2026-03-08
time: 18:03
type: Expense
domain: paybill
entity: KPLC
amount: 5000.0
balance: 149833.0
fee: 0.0
reference: 88888:123456789


⏱️  Latency: 2.737 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 5/20
ID       : valid_05
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this bank transfer received.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
BNK72PQ91 Confirmed. Ksh45,000.00 received in your M-PESA account from Equity Bank on 09/03/2026 at 11:30 AM. New M-PESA balance is Ksh194,833.00. Reference EQT98431.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     407.74 ms /   125 tokens (    3.26 ms per token,   306.57 tokens per second)
llama_perf_context_print:        eval time =    2062.94 ms /    92 runs   (   22.42 ms per token,    44.60 tokens per second)
llama_perf_context_print:       total time =    2591.43 ms /   217 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 6 prefix-match hit, remaining 124 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: BNK72PQ91
date: 2026-03-09
time: 11:30
type: Callback
domain: bank_to_mpesa
entity: Equity Bank
amount: 45000.0
balance: 194833.0
fee: 0.0
reference: BNK72PQ91


⏱️  Latency: 2.597 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 6/20
ID       : valid_06
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this Fuliza transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
FUL123ABC Confirmed. Fuliza loan of Ksh10,000.00 received on 10/03/2026 at 08:05 AM. New M-PESA balance is Ksh204,833.00. Fuliza outstanding balance is Ksh10,000.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     394.27 ms /   124 tokens (    3.18 ms per token,   314.50 tokens per second)
llama_perf_context_print:        eval time =    1929.50 ms /    85 runs   (   22.70 ms per token,    44.05 tokens per second)
llama_perf_context_print:       total time =    2436.09 ms /   209 tokens
llama_perf_context_print:    graphs reused =         84
Llama.generate: 6 prefix-match hit, remaining 131 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id:FUL123ABC
date:2026-03-10
time:08:05
type:income_receive_money
domain:fuliza_loan
entity:Fuliza
amount:10000.0
balance:204833.0
fee:0.0
reference:FUL123ABC


⏱️  Latency: 2.444 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 7/20
ID       : valid_07
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this cash withdrawal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
WD91KLM22 Confirmed. Ksh8,000.00 withdrawn from M-PESA at Agent 456789 - John Kamau on 11/03/2026 at 16:40. Transaction cost, Ksh80.00. New M-PESA balance is Ksh196,753.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     423.21 ms /   131 tokens (    3.23 ms per token,   309.54 tokens per second)
llama_perf_context_print:        eval time =    2165.02 ms /    97 runs   (   22.32 ms per token,    44.80 tokens per second)
llama_perf_context_print:       total time =    2714.50 ms /   228 tokens
llama_perf_context_print:    graphs reused =         96
Llama.generate: 6 prefix-match hit, remaining 121 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: WD91KLM22, date: 2026-03-11, time: 16:40, type: Expense, domain: M-PESA, entity: Agent 456789, amount: 8000.0, balance: 196753.0, fee: 80.0, reference: WDD91KLM22


⏱️  Latency: 2.721 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 8/20
ID       : valid_08
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this reversal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
REV8821 Confirmed. Reversal of Ksh2,500.00 for transaction QWE12345 has been credited to your M-PESA account on 12/03/2026 at 13:22. New M-PESA balance is Ksh199,253.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     392.22 ms /   121 tokens (    3.24 ms per token,   308.50 tokens per second)
llama_perf_context_print:        eval time =    1988.47 ms /    88 runs   (   22.60 ms per token,    44.26 tokens per second)
llama_perf_context_print:       total time =    2495.70 ms /   209 tokens
llama_perf_context_print:    graphs reused =         87
Llama.generate: 5 prefix-match hit, remaining 106 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: REV8821
date: 2026-03-12
time: 13:22
type: Expense
domain: send_cash_withdrawal
entity: M-PESA
amount: 2500.0
balance: 199253.0
fee: 0.0
reference: REV8821


⏱️  Latency: 2.500 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 9/20
ID       : missing_01
CATEGORY : missing_data
TASK     : Handle missing balance
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for information that is not present.
Do not guess.

SMS:
ABC12345 Confirmed. You have received Ksh7,500.00 from Mary Wanjiku on 13/03/2026 at 09:10 AM.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     363.72 ms /   106 tokens (    3.43 ms per token,   291.43 tokens per second)
llama_perf_context_print:        eval time =    1791.19 ms /    80 runs   (   22.39 ms per token,    44.66 tokens per second)
llama_perf_context_print:       total time =    2259.16 ms /   186 tokens
llama_perf_context_print:    graphs reused =         79
Llama.generate: 39 prefix-match hit, remaining 71 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: ABC12345
date: 2026-03-13
time: 09:10
type: Callback
domain: receive_transaction
entity: Mary Wanjiku
amount: 7500.0
balance: null
fee: 0.0
reference: ABC12345


⏱️  Latency: 2.264 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 10/20
ID       : missing_02
CATEGORY : missing_data
TASK     : Handle missing transaction ID
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for missing information.

SMS:
You paid Ksh2,000.00 to Green Valley Shop on 14/03/2026 at 15:20. New M-PESA balance is Ksh197,253.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     241.05 ms /    71 tokens (    3.40 ms per token,   294.55 tokens per second)
llama_perf_context_print:        eval time =    1815.94 ms /    79 runs   (   22.99 ms per token,    43.50 tokens per second)
llama_perf_context_print:       total time =    2161.98 ms /   150 tokens
llama_perf_context_print:    graphs reused =         78
Llama.generate: 36 prefix-match hit, remaining 84 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: null
date: 2026-03-14
time: 15:20
type: Expense
domain: paid_send_transaction
entity: Green Valley Shop
amount: 2000.0
balance: 197253.0
fee: 0.0
reference: null


⏱️  Latency: 2.169 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 11/20
ID       : missing_03
CATEGORY : missing_data
TASK     : Handle missing entity
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent an entity.

SMS:
TX99821 Confirmed. Ksh3,200.00 paid via M-PESA on 15/03/2026 at 12:00 PM. New M-PESA balance is Ksh194,053.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     275.58 ms /    84 tokens (    3.28 ms per token,   304.81 tokens per second)
llama_perf_context_print:        eval time =    1988.48 ms /    89 runs   (   22.34 ms per token,    44.76 tokens per second)
llama_perf_context_print:       total time =    2379.31 ms /   173 tokens
llama_perf_context_print:    graphs reused =         88
Llama.generate: 4 prefix-match hit, remaining 93 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: TX99821
date: 2026-03-15
time: 12:00
type: Expense
domain: pay_mpesa
entity: M-PESA
amount: 3200.0
balance: 194053.0
fee: 0.0
reference: TX99821


⏱️  Latency: 2.385 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 12/20
ID       : missing_04
CATEGORY : missing_data
TASK     : Ambiguous transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Determine what can safely be extracted from this message.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null when information is ambiguous or missing.
Do not invent facts.

SMS:
TX7712 Confirmed. Ksh5,000 sent. Balance Ksh100,000.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     301.79 ms /    93 tokens (    3.25 ms per token,   308.17 tokens per second)
llama_perf_context_print:        eval time =    1070.21 ms /    48 runs   (   22.30 ms per token,    44.85 tokens per second)
llama_perf_context_print:       total time =    1435.49 ms /   141 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 4 prefix-match hit, remaining 123 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The utterance is a confirmation that transaction_id 7712 has been initiated and sent to a specified party with sent_money and send_envelope attachments. It does not specify who sent the SMS or whether the transaction is fraudulent.


⏱️  Latency: 1.441 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 13/20
ID       : missing_05
CATEGORY : missing_data
TASK     : Noisy SMS
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction from this noisy SMS.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Ignore irrelevant text.
Do not invent missing information.

SMS:
M-PESA ALERT!!! Your account was updated. TX88K21 Confirmed. You received Ksh12,000 from Peter on 16/03/2026. Please do not share your PIN. New balance Ksh112,000.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     392.27 ms /   123 tokens (    3.19 ms per token,   313.56 tokens per second)
llama_perf_context_print:        eval time =    5795.33 ms /   255 runs   (   22.73 ms per token,    44.00 tokens per second)
llama_perf_context_print:       total time =    6555.17 ms /   378 tokens
llama_perf_context_print:    graphs reused =        253
Llama.generate: 5 prefix-match hit, remaining 125 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: M-PESA-ALERT-2026-03-16-2026-send_update_poffits_receivable_sent_sms_income_shorter_than_net_income_receive_refund_delay_init_bank_transfer_sent_income_shorter_than_income_receive_money_refund_applies_income_discrepation_forecasting_requires_in-depth_analysis_and_personal_finance_information_to_support_decision_allocation_of_bank_repayment_and_income_increase_in_bank_income_from_cash_flow_to_bank_of_borrowers_of_property_refund_applies_income_discrepation_and_forecasting_errors_require_detailed_query_and_analysis_of_bank_transfers_and_income_flows_to_bank_of_borrowers_and_empirists_of_property_income_increasing_bank_income_by_cash_in_bank_of_cash_flow_to_income_of_living_people_and_expenses_must_


⏱️  Latency: 6.560 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 14/20
ID       : missing_06
CATEGORY : missing_data
TASK     : Conflicting information
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this transaction carefully.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

If the message contains conflicting information, preserve only what can be determined safely and use null where necessary.

SMS:
TX5566 Confirmed. Ksh4,000 paid to ABC Shop on 17/03/2026. New M-PESA balance is Ksh90,000. Later message says transaction amount was Ksh5,000.

Return ONLY JSON.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     467.04 ms /   125 tokens (    3.74 ms per token,   267.64 tokens per second)
llama_perf_context_print:        eval time =    5779.49 ms /   255 runs   (   22.66 ms per token,    44.12 tokens per second)
llama_perf_context_print:       total time =    6609.94 ms /   380 tokens
llama_perf_context_print:    graphs reused =        253
Llama.generate: 4 prefix-match hit, remaining 30 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: TSE5566-2026-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-12


⏱️  Latency: 6.615 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 15/20
ID       : capability_01
CATEGORY : capability
TASK     : Capabilities
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What types of financial transaction messages are you designed to understand?

Mention the transaction categories you can identify.

Answer concisely.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     113.40 ms /    30 tokens (    3.78 ms per token,   264.56 tokens per second)
llama_perf_context_print:        eval time =     550.61 ms /    24 runs   (   22.94 ms per token,    43.59 tokens per second)
llama_perf_context_print:       total time =     697.99 ms /    54 tokens
llama_perf_context_print:    graphs reused =         23
Llama.generate: 5 prefix-match hit, remaining 30 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
This is a tailored search of SMS for M-PESA and bank transfers, prioritizing necessary information and minimizing unnecessary processing.


⏱️  Latency: 0.703 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 16/20
ID       : capability_02
CATEGORY : capability
TASK     : Supported fields
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What information can you extract from an M-Pesa or bank transaction message?

List the fields you are designed to identify.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     111.93 ms /    30 tokens (    3.73 ms per token,   268.03 tokens per second)
llama_perf_context_print:        eval time =     806.90 ms /    36 runs   (   22.41 ms per token,    44.62 tokens per second)
llama_perf_context_print:       total time =     966.52 ms /    66 tokens
llama_perf_context_print:    graphs reused =         35
Llama.generate: 5 prefix-match hit, remaining 31 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The design prioritizes local processing of sensitive financial information and minimizes unnecessary transmission of extracted data to remote services. This aligns with the principle of least-to-most data and privacy.


⏱️  Latency: 0.971 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 17/20
ID       : capability_03
CATEGORY : capability
TASK     : Missing information
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What do you do when a financial SMS is missing important information such as the transaction ID, entity, balance, date, or amount?

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     115.60 ms /    31 tokens (    3.73 ms per token,   268.17 tokens per second)
llama_perf_context_print:        eval time =     950.83 ms /    41 runs   (   23.19 ms per token,    43.12 tokens per second)
llama_perf_context_print:       total time =    1122.30 ms /    72 tokens
llama_perf_context_print:    graphs reused =         40
Llama.generate: 4 prefix-match hit, remaining 40 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The primary action I would take on a financial transaction is to initiate an offline inquiry with the bank or financial institution to search their records for duplicates or unavailable information. This reduces unnecessary manual effort and personal bias.


⏱️  Latency: 1.127 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 18/20
ID       : capability_04
CATEGORY : capability
TASK     : Unsupported claims
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Can you access a user's bank account, M-Pesa account, contacts, internet, or private financial records directly?

Explain what you can and cannot access.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     139.29 ms /    40 tokens (    3.48 ms per token,   287.17 tokens per second)
llama_perf_context_print:        eval time =     877.88 ms /    39 runs   (   22.51 ms per token,    44.43 tokens per second)
llama_perf_context_print:       total time =    1069.35 ms /    79 tokens
llama_perf_context_print:    graphs reused =         38
Llama.generate: 4 prefix-match hit, remaining 28 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The design prioritizes local processing of sensitive financial information and minimizes unnecessary transmission of extracted data to remote services. This approach is more efficient and reduces the burden on senders and receivers of financial SMS.


⏱️  Latency: 1.074 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 19/20
ID       : capability_05
CATEGORY : capability
TASK     : Role
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What is your role in the SME Ledger system?

Explain what happens after you extract a transaction from an SMS.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     100.23 ms /    28 tokens (    3.58 ms per token,   279.36 tokens per second)
llama_perf_context_print:        eval time =     816.02 ms /    36 runs   (   22.67 ms per token,    44.12 tokens per second)
llama_perf_context_print:       total time =     964.28 ms /    64 tokens
llama_perf_context_print:    graphs reused =         35
Llama.generate: 4 prefix-match hit, remaining 42 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
I turn a M-PESA-Ledger-like assistant on-device, processing sensitive financial information and forwarding it to authorized financial intermediaries or cash-flow-oriented entities.


⏱️  Latency: 0.970 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 20/20
ID       : capability_06
CATEGORY : capability
TASK     : Transaction types
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Can you distinguish between income, expenses, transfers, withdrawals, merchant payments, PayBill payments, Fuliza transactions, reversals, and failed transactions?

If yes, briefly explain how.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     141.16 ms /    42 tokens (    3.36 ms per token,   297.54 tokens per second)
llama_perf_context_print:        eval time =    1101.27 ms /    49 runs   (   22.47 ms per token,    44.49 tokens per second)
llama_perf_context_print:       total time =    1306.74 ms /    91 tokens
llama_perf_context_print:    graphs reused =         48

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
Yes. The application can analyze financial information in a supported manner to identify transaction or balance-related patterns, such as income, expenses, cash-flow or spending imbalances. This is a preliminary step and should be tailored to the specific application structure.


⏱️  Latency: 1.312 seconds



==========================================================================================
                         TEST RUN COMPLETE
==========================================================================================

Tests executed:       20/20
Successful runs:      20/20
Average latency:      2.446 seconds

No automatic correctness or JSON validation was performed.
You are the evaluator.

Raw results saved to: sme_ledger_20_manual_test_results.json
==========================================================================================

/tmp/ipykernel_16/1229522993.py:493: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "timestamp": datetime.utcnow().isoformat() + "Z",

In [5]:

# ============================================================
# CELL 5 — SME-LEDGER V2
# 50 SMS FINANCIAL LEDGER EXTRACTION
# Robust prompt + JSON/key:value parser
# ============================================================

import os
import re
import json
import time
import pandas as pd
import numpy as np


# ------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------

INPUT_FILE = "/kaggle/input/datasets/wangapa106g/massage-analysis/test_50_consistent.csv"
OUTPUT_FILE = "/kaggle/working/sme_ledger_50_results.csv"

# Successful manual test used ~93 generated tokens.
# Give the model a little headroom.
MAX_OUTPUT_TOKENS = 110

print("=" * 80)
print("SME-LEDGER V2 — 50 SMS FINANCIAL LEDGER EXTRACTION")
print("=" * 80)


# ------------------------------------------------------------
# CHECK MODEL
# ------------------------------------------------------------

if "llm" not in globals():
    raise RuntimeError(
        "The `llm` model is not loaded. Run the model-loading cell first."
    )


# ------------------------------------------------------------
# LOAD DATA
# ------------------------------------------------------------

df = pd.read_csv(INPUT_FILE)

print(f"Input file : {INPUT_FILE}")
print(f"Rows loaded: {len(df)}")
print(f"Columns    : {list(df.columns)}")

if "message" in df.columns:
    SMS_COLUMN = "message"
elif "sms" in df.columns:
    SMS_COLUMN = "sms"
else:
    raise ValueError(
        f"No SMS column found. Available columns: {list(df.columns)}"
    )

df = df.head(50).copy()

print(f"SMS column : {SMS_COLUMN}")
print(f"Samples    : {len(df)}")
print()


# ------------------------------------------------------------
# FINAL OUTPUT COLUMNS
# ------------------------------------------------------------

OUTPUT_COLUMNS = [
    "sms",
    "transaction_id",
    "date",
    "time",
    "type",
    "domain",
    "entity",
    "amount",
    "balance",
]


# ------------------------------------------------------------
# HELPER FUNCTIONS
# ------------------------------------------------------------

def clean_text(value):
    if value is None:
        return None

    if isinstance(value, float) and np.isnan(value):
        return None

    value = str(value).strip()

    if value.lower() in {
        "",
        "null",
        "none",
        "n/a",
        "na",
        "unknown",
    }:
        return None

    return value


def normalize_number(value):
    """
    Convert:
        7500
        "7500"
        "7,500.00"
        "Ksh7,500.00"
    into float.
    """

    if value is None:
        return None

    if isinstance(value, (int, float, np.integer, np.floating)):
        if pd.isna(value):
            return None
        return float(value)

    text = str(value).strip()

    if not text:
        return None

    text = re.sub(r"[Kk][Ss][Hh]\s*", "", text)
    text = re.sub(r"[Kk][Ee][Ss]\s*", "", text)
    text = text.replace(",", "")

    match = re.search(r"-?\d+(?:\.\d+)?", text)

    if not match:
        return None

    try:
        return float(match.group())
    except Exception:
        return None


# ------------------------------------------------------------
# JSON PARSER
# ------------------------------------------------------------

def extract_json_object(text):
    """
    Extract JSON if the model returns JSON, even if surrounded
    by markdown fences or small amounts of text.
    """

    if not text:
        return None

    text = str(text).strip()

    # Remove markdown fences
    text = re.sub(r"```json", "", text, flags=re.IGNORECASE)
    text = re.sub(r"```", "", text).strip()

    # Direct JSON
    try:
        obj = json.loads(text)

        if isinstance(obj, dict):
            return obj

    except Exception:
        pass

    # JSON embedded in text
    start = text.find("{")

    if start == -1:
        return None

    depth = 0
    in_string = False
    escape = False

    for i in range(start, len(text)):

        char = text[i]

        if escape:
            escape = False
            continue

        if char == "\\" and in_string:
            escape = True
            continue

        if char == '"':
            in_string = not in_string
            continue

        if not in_string:

            if char == "{":
                depth += 1

            elif char == "}":
                depth -= 1

                if depth == 0:

                    candidate = text[start:i + 1]

                    try:
                        obj = json.loads(candidate)

                        if isinstance(obj, dict):
                            return obj

                    except Exception:
                        return None

    return None


# ------------------------------------------------------------
# KEY: VALUE PARSER
# ------------------------------------------------------------

def extract_key_value_object(text):
    """
    The fine-tuned model may naturally respond in:

        transaction_id: ABC123
        date: 2026-03-05
        time: 10:42
        type: Income
        ...

    Accept that format and normalize it into a dictionary.
    """

    if not text:
        return None

    text = str(text).strip()

    fields = [
        "transaction_id",
        "date",
        "time",
        "type",
        "domain",
        "entity",
        "amount",
        "balance",
        "fee",
        "reference",
    ]

    result = {}

    for field in fields:

        # Match:
        # field: value
        # field = value
        pattern = rf"(?im)^\s*{re.escape(field)}\s*[:=]\s*(.*?)\s*$"

        match = re.search(pattern, text)

        if match:
            value = match.group(1).strip()

            # Remove surrounding quotes
            if (
                len(value) >= 2
                and value[0] == '"'
                and value[-1] == '"'
            ):
                value = value[1:-1]

            result[field] = value

    if result:
        return result

    return None


# ------------------------------------------------------------
# UNIFIED PARSER
# ------------------------------------------------------------

def parse_model_response(text):

    # Try proper JSON first
    parsed = extract_json_object(text)

    if parsed is not None:
        return parsed, "json"

    # Then accept learned key:value format
    parsed = extract_key_value_object(text)

    if parsed is not None:
        return parsed, "key_value"

    return None, None


# ------------------------------------------------------------
# NORMALIZE TRANSACTION
# ------------------------------------------------------------

def normalize_transaction(data):

    if not isinstance(data, dict):
        data = {}

    # Make keys case-insensitive
    normalized_keys = {}

    for key, value in data.items():
        normalized_keys[str(key).strip().lower()] = value

    result = {
        "transaction_id": clean_text(
            normalized_keys.get("transaction_id")
        ),

        "date": clean_text(
            normalized_keys.get("date")
        ),

        "time": clean_text(
            normalized_keys.get("time")
        ),

        "type": clean_text(
            normalized_keys.get("type")
        ),

        "domain": clean_text(
            normalized_keys.get("domain")
        ),

        "entity": clean_text(
            normalized_keys.get("entity")
        ),

        "amount": normalize_number(
            normalized_keys.get("amount")
        ),

        "balance": normalize_number(
            normalized_keys.get("balance")
        ),
    }

    # Normalize transaction type
    if result["type"]:

        t = result["type"].lower().strip()

        if t in {
            "income",
            "received",
            "receive",
            "credit",
        }:
            result["type"] = "income"

        elif t in {
            "expense",
            "spent",
            "payment",
            "paid",
            "sent",
            "debit",
            "withdrawal",
            "withdraw",
        }:
            result["type"] = "expense"

        else:
            result["type"] = "unknown"

    return result


# ------------------------------------------------------------
# PROVEN PROMPT
# ------------------------------------------------------------
#
# IMPORTANT:
# We intentionally use the same instruction structure that
# successfully produced a response in the manual test.
#
# We do NOT use the previous compact system prompt + JSON
# skeleton because that caused the model to terminate after
# only ~2 generated tokens.
#
# ------------------------------------------------------------

def build_prompt(sms):

    return f"""Extract the financial transaction below.

Return ONLY valid JSON with exactly these fields:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Rules:
- amount, balance and fee must be numbers.
- type must be income, expense, or unknown.
- date must be YYYY-MM-DD.
- Do not invent missing information.
- Use null when information is unavailable.
- No markdown.
- No explanation.

SMS:
{sms}

Return ONLY JSON."""


# ------------------------------------------------------------
# START FRESH
# ------------------------------------------------------------

if os.path.exists(OUTPUT_FILE):
    os.remove(OUTPUT_FILE)

results = []


# ------------------------------------------------------------
# PROCESS 50 SMS ONE AT A TIME
# ------------------------------------------------------------

print("=" * 80)
print("STARTING SEQUENTIAL SMS EXTRACTION")
print("=" * 80)
print()


for idx in range(len(df)):

    sample_number = idx + 1

    sms = str(
        df.iloc[idx][SMS_COLUMN]
    ).strip()

    print("-" * 80)
    print(f"SMS {sample_number}/{len(df)}")
    print("-" * 80)
    print(f"SMS: {sms}")

    start_time = time.time()

    # Default row
    row = {
        "sms": sms,
        "transaction_id": None,
        "date": None,
        "time": None,
        "type": None,
        "domain": None,
        "entity": None,
        "amount": None,
        "balance": None,
    }

    try:

        # ----------------------------------------------------
        # MODEL INFERENCE
        # ----------------------------------------------------

        #
        # IMPORTANT:
        # Use ONE user message.
        # This matches the successful manual prompting pattern.
        #

        response = llm.create_chat_completion(

            messages=[
                {
                    "role": "user",
                    "content": build_prompt(sms),
                }
            ],

            temperature=0,
            top_p=1,
            seed=42,

            max_tokens=MAX_OUTPUT_TOKENS,
        )


        # ----------------------------------------------------
        # GET MODEL RESPONSE
        # ----------------------------------------------------

        raw_response = ""

        try:

            raw_response = response[
                "choices"
            ][0][
                "message"
            ][
                "content"
            ]

        except Exception:

            try:

                raw_response = response[
                    "choices"
                ][0][
                    "text"
                ]

            except Exception:

                raw_response = ""

        raw_response = str(
            raw_response
        ).strip()


        # ----------------------------------------------------
        # SHOW RAW MODEL OUTPUT
        # ----------------------------------------------------

        print()
        print("MODEL OUTPUT:")
        print(raw_response if raw_response else "[EMPTY]")
        print()


        # ----------------------------------------------------
        # PARSE MODEL RESPONSE
        # ----------------------------------------------------

        parsed, parse_method = parse_model_response(
            raw_response
        )


        if parsed is None:

            print("Status: ✗ PARSE FAILED")

        else:

            transaction = normalize_transaction(
                parsed
            )

            row.update(transaction)

            if parse_method == "json":
                print("Parser: JSON")
            else:
                print("Parser: KEY/VALUE")

            print("Status: ✓ SUCCESS")
            print(
                f"Transaction: {row['transaction_id']}"
            )
            print(
                f"Type       : {row['type']}"
            )
            print(
                f"Domain     : {row['domain']}"
            )
            print(
                f"Entity     : {row['entity']}"
            )
            print(
                f"Amount     : {row['amount']}"
            )
            print(
                f"Balance    : {row['balance']}"
            )


    except Exception as e:

        print("Status: ✗ ERROR")
        print(f"Error : {e}")


    latency = time.time() - start_time

    print(
        f"Latency: {latency:.3f}s"
    )


    # --------------------------------------------------------
    # APPEND ROW
    # --------------------------------------------------------

    results.append(row)


    # --------------------------------------------------------
    # SAVE IMMEDIATELY
    # --------------------------------------------------------

    current_df = pd.DataFrame(
        results,
        columns=OUTPUT_COLUMNS,
    )

    current_df.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    print(
        f"Saved rows: {len(results)}"
    )

    print()


# ------------------------------------------------------------
# FINAL DATAFRAME
# ------------------------------------------------------------

final_df = pd.DataFrame(
    results,
    columns=OUTPUT_COLUMNS,
)

final_df.to_csv(
    OUTPUT_FILE,
    index=False,
)


# ------------------------------------------------------------
# FINAL SUMMARY
# ------------------------------------------------------------

print("=" * 80)
print("EXTRACTION COMPLETE")
print("=" * 80)

print(
    f"Total SMS processed: {len(final_df)}"
)

print(
    f"Output columns: {list(final_df.columns)}"
)

print(
    f"Output file: {OUTPUT_FILE}"
)


# ------------------------------------------------------------
# BASIC QUALITY CHECK
# ------------------------------------------------------------

print()
print("=" * 80)
print("EXTRACTION SUMMARY")
print("=" * 80)

print(
    f"Transaction IDs extracted: "
    f"{final_df['transaction_id'].notna().sum()}/{len(final_df)}"
)

print(
    f"Dates extracted: "
    f"{final_df['date'].notna().sum()}/{len(final_df)}"
)

print(
    f"Amounts extracted: "
    f"{final_df['amount'].notna().sum()}/{len(final_df)}"
)

print(
    f"Balances extracted: "
    f"{final_df['balance'].notna().sum()}/{len(final_df)}"
)

print()
print("=" * 80)
print("FINAL LEDGER")
print("=" * 80)

display(final_df)

================================================================================
SME-LEDGER V2 — 50 SMS FINANCIAL LEDGER EXTRACTION
================================================================================
Input file : /kaggle/input/datasets/wangapa106g/massage-analysis/test_50_consistent.csv
Rows loaded: 50
Columns    : ['message']
SMS column : message
Samples    : 50

================================================================================
STARTING SEQUENTIAL SMS EXTRACTION
================================================================================

--------------------------------------------------------------------------------
SMS 1/50
--------------------------------------------------------------------------------
SMS: TX03010001 Confirmed. You have received Ksh7,500.00 from John Kamau on 01/03/2026 at 08:18 AM. New M-PESA balance is Ksh157,500.00. Transaction cost, Ksh0.00.

Llama.generate: 4 prefix-match hit, remaining 195 prompt tokens to eval
llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     619.44 ms /   195 tokens (    3.18 ms per token,   314.80 tokens per second)
llama_perf_context_print:        eval time =    2223.10 ms /    97 runs   (   22.92 ms per token,    43.63 tokens per second)
llama_perf_context_print:       total time =    2968.73 ms /   292 tokens
llama_perf_context_print:    graphs reused =         95
Llama.generate: 120 prefix-match hit, remaining 79 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03010001; date: 2026-03-01; time: 08:18; type: income; domain: bank_transfer_receive_money; entity: John Kamau; amount: 7500.0; balance: 157500.0; fee: 0.0; reference: TX03010001

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03010001; date: 2026-03-01; time: 08:18; type: income; domain: bank_transfer_receive_money; entity: John Kamau; amount: 7500.0; balance: 157500.0; fee: 0.0; reference: TX03010001
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.977s
Saved rows: 1

--------------------------------------------------------------------------------
SMS 2/50
--------------------------------------------------------------------------------
SMS: TX03010002 Confirmed. You have received Ksh2,500.00 from Peter Mwangi on 01/03/2026 at 01:27 PM. New M-PESA balance is Ksh160,000.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     263.74 ms /    79 tokens (    3.34 ms per token,   299.54 tokens per second)
llama_perf_context_print:        eval time =    2170.87 ms /    96 runs   (   22.61 ms per token,    44.22 tokens per second)
llama_perf_context_print:       total time =    2558.09 ms /   175 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 116 prefix-match hit, remaining 79 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03010002
date: 2026-03-01
time: 12:27
type: Income
domain: bank_transfer_receive_money
entity: Peter Mwangi
amount: 2500.0
balance: 16000.0
fee: 0.0
reference: TX03010002

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03010002
Type       : income
Domain     : bank_transfer_receive_money
Entity     : Peter Mwangi
Amount     : 2500.0
Balance    : 16000.0
Latency: 2.564s
Saved rows: 2

--------------------------------------------------------------------------------
SMS 3/50
--------------------------------------------------------------------------------
SMS: TX03020003 Confirmed. Ksh500.00 paid to Green Valley Shop on 02/03/2026 at 09:02 AM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh159,500.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     270.62 ms /    79 tokens (    3.43 ms per token,   291.92 tokens per second)
llama_perf_context_print:        eval time =    1994.68 ms /    87 runs   (   22.93 ms per token,    43.62 tokens per second)
llama_perf_context_print:       total time =    2377.39 ms /   166 tokens
llama_perf_context_print:    graphs reused =         85
Llama.generate: 120 prefix-match hit, remaining 77 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03020003
date: 2026-03-02
time: 09:02
type: Expense
domain: send_money
entity: Green Valley Shop
amount: 500.0
balance: 0.0
fee: 0.0
reference: TX03020003

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03020003
Type       : expense
Domain     : send_money
Entity     : Green Valley Shop
Amount     : 500.0
Balance    : 0.0
Latency: 2.384s
Saved rows: 3

--------------------------------------------------------------------------------
SMS 4/50
--------------------------------------------------------------------------------
SMS: TX03020004 Confirmed. Ksh500.00 sent to David Kiptoo on 02/03/2026 at 01:27 PM. Transaction cost, Ksh10.00. New M-PESA balance is Ksh158,990.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     267.86 ms /    77 tokens (    3.48 ms per token,   287.46 tokens per second)
llama_perf_context_print:        eval time =     295.61 ms /    13 runs   (   22.74 ms per token,    43.98 tokens per second)
llama_perf_context_print:       total time =     581.04 ms /    90 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 116 prefix-match hit, remaining 81 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03020004

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03020004
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.586s
Saved rows: 4

--------------------------------------------------------------------------------
SMS 5/50
--------------------------------------------------------------------------------
SMS: TX03030005 Confirmed. Ksh1,500.00 paid to Wanga Electronics on 03/03/2026 at 08:27 AM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh157,490.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     263.62 ms /    81 tokens (    3.25 ms per token,   307.26 tokens per second)
llama_perf_context_print:        eval time =    1986.09 ms /    88 runs   (   22.57 ms per token,    44.31 tokens per second)
llama_perf_context_print:       total time =    2361.66 ms /   169 tokens
llama_perf_context_print:    graphs reused =         86
Llama.generate: 120 prefix-match hit, remaining 77 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03030005; date: 2026-03-03; time: 08:27; type: expense; domain: bank_transfer_paid; entity: Wanga Electronics; amount: 1500.0; balance: 0; fee: 0.0; reference: TX03030005

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03030005; date: 2026-03-03; time: 08:27; type: expense; domain: bank_transfer_paid; entity: Wanga Electronics; amount: 1500.0; balance: 0; fee: 0.0; reference: TX03030005
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.368s
Saved rows: 5

--------------------------------------------------------------------------------
SMS 6/50
--------------------------------------------------------------------------------
SMS: TX03030006 Confirmed. Ksh1,000.00 paid to Airtel Money on 03/03/2026 at 01:49 PM. Transaction cost, Ksh10.00. New M-PESA balance is Ksh156,480.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     254.81 ms /    77 tokens (    3.31 ms per token,   302.19 tokens per second)
llama_perf_context_print:        eval time =    1963.79 ms /    87 runs   (   22.57 ms per token,    44.30 tokens per second)
llama_perf_context_print:       total time =    2328.79 ms /   164 tokens
llama_perf_context_print:    graphs reused =         85
Llama.generate: 116 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03030006; date: 2026-03-03; time: 01:49; type: expense; domain: bank_transfer_paid; entity: Airtel Money; amount: 1000.0; balance: 0; fee: 0.0; reference: TX03030006

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03030006; date: 2026-03-03; time: 01:49; type: expense; domain: bank_transfer_paid; entity: Airtel Money; amount: 1000.0; balance: 0; fee: 0.0; reference: TX03030006
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.335s
Saved rows: 6

--------------------------------------------------------------------------------
SMS 7/50
--------------------------------------------------------------------------------
SMS: TX03040007 Confirmed. You have received Ksh2,500.00 from Grace Njeri on 04/03/2026 at 08:18 AM. New M-PESA balance is Ksh158,980.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     275.06 ms /    83 tokens (    3.31 ms per token,   301.76 tokens per second)
llama_perf_context_print:        eval time =    2193.78 ms /    97 runs   (   22.62 ms per token,    44.22 tokens per second)
llama_perf_context_print:       total time =    2596.00 ms /   180 tokens
llama_perf_context_print:    graphs reused =         95
Llama.generate: 120 prefix-match hit, remaining 76 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03040007
date: 2026-03-04
time: 08:18
type: Income
domain: bank_transfer_receive_money
entity: Grace Njeri
amount: 2500.0
balance: 158980.0
fee: 0.0
reference: TX03040007

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03040007
Type       : income
Domain     : bank_transfer_receive_money
Entity     : Grace Njeri
Amount     : 2500.0
Balance    : 158980.0
Latency: 2.603s
Saved rows: 7

--------------------------------------------------------------------------------
SMS 8/50
--------------------------------------------------------------------------------
SMS: TX03040008 Confirmed. Ksh500.00 sent to Peter Mwangi on 04/03/2026 at 01:36 PM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh158,430.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     330.76 ms /    76 tokens (    4.35 ms per token,   229.77 tokens per second)
llama_perf_context_print:        eval time =     292.09 ms /    13 runs   (   22.47 ms per token,    44.51 tokens per second)
llama_perf_context_print:       total time =     640.19 ms /    89 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 116 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03040008

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03040008
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.646s
Saved rows: 8

--------------------------------------------------------------------------------
SMS 9/50
--------------------------------------------------------------------------------
SMS: TX03050009 Confirmed. You have received Ksh7,500.00 from Grace Njeri on 05/03/2026 at 08:49 AM. New M-PESA balance is Ksh165,930.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     276.08 ms /    83 tokens (    3.33 ms per token,   300.64 tokens per second)
llama_perf_context_print:        eval time =    2174.64 ms /    95 runs   (   22.89 ms per token,    43.69 tokens per second)
llama_perf_context_print:       total time =    2575.13 ms /   178 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 119 prefix-match hit, remaining 80 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03050009
date: 2026-03-05
time: 08:49
type: Income
domain: bank_transfer_received
entity: Grace Njeri
amount: 7500.0
balance: 165930.0
fee: 0.0
reference: TX03050009

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03050009
Type       : income
Domain     : bank_transfer_received
Entity     : Grace Njeri
Amount     : 7500.0
Balance    : 165930.0
Latency: 2.580s
Saved rows: 9

--------------------------------------------------------------------------------
SMS 10/50
--------------------------------------------------------------------------------
SMS: TX03050010 Confirmed. You have received Ksh2,500.00 from Ann Mueni on 05/03/2026 at 02:02 PM. New M-PESA balance is Ksh168,430.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     258.01 ms /    80 tokens (    3.23 ms per token,   310.06 tokens per second)
llama_perf_context_print:        eval time =    2182.01 ms /    97 runs   (   22.49 ms per token,    44.45 tokens per second)
llama_perf_context_print:       total time =    2563.63 ms /   177 tokens
llama_perf_context_print:    graphs reused =         95
Llama.generate: 116 prefix-match hit, remaining 94 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03050010
date: 2026-03-05
time: 12:02
type: Income
domain: bank_transfer_receive_money
entity: Ann Mueni
amount: 2500.0
balance: 168430.0
fee: 0.0
reference: TX03050010

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03050010
Type       : income
Domain     : bank_transfer_receive_money
Entity     : Ann Mueni
Amount     : 2500.0
Balance    : 168430.0
Latency: 2.571s
Saved rows: 10

--------------------------------------------------------------------------------
SMS 11/50
--------------------------------------------------------------------------------
SMS: TX03060011 Confirmed. Ksh800.00 withdrawn from M-PESA at Agent 498591 - John Kamau on 06/03/2026 at 08:27 AM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh167,580.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     302.27 ms /    94 tokens (    3.22 ms per token,   310.98 tokens per second)
llama_perf_context_print:        eval time =    2231.33 ms /    98 runs   (   22.77 ms per token,    43.92 tokens per second)
llama_perf_context_print:       total time =    2659.70 ms /   192 tokens
llama_perf_context_print:    graphs reused =         96
Llama.generate: 120 prefix-match hit, remaining 76 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03060011; date: 2026-03-06; time: 08:27; domain: cash_withdrawal; entity: Agent 498591; amount: 800.0; balance: 167.580; fee: 50.0; reference: T0001234567891

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03060011; date: 2026-03-06; time: 08:27; domain: cash_withdrawal; entity: Agent 498591; amount: 800.0; balance: 167.580; fee: 50.0; reference: T0001234567891
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.665s
Saved rows: 11

--------------------------------------------------------------------------------
SMS 12/50
--------------------------------------------------------------------------------
SMS: TX03060012 Confirmed. Ksh2,000.00 paid to Airtel Money on 06/03/2026 at 01:36 PM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh165,580.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     252.55 ms /    76 tokens (    3.32 ms per token,   300.93 tokens per second)
llama_perf_context_print:        eval time =    1993.65 ms /    87 runs   (   22.92 ms per token,    43.64 tokens per second)
llama_perf_context_print:       total time =    2360.24 ms /   163 tokens
llama_perf_context_print:    graphs reused =         85
Llama.generate: 116 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03060012; date: 2026-03-06; time: 01:36; type: expense; domain: bank_transfer_paid; entity: Airtel Money; amount: 2000.0; balance: 0; fee: 0.0; reference: TX03060012

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03060012; date: 2026-03-06; time: 01:36; type: expense; domain: bank_transfer_paid; entity: Airtel Money; amount: 2000.0; balance: 0; fee: 0.0; reference: TX03060012
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.367s
Saved rows: 12

--------------------------------------------------------------------------------
SMS 13/50
--------------------------------------------------------------------------------
SMS: TX03070013 Confirmed. You have received Ksh7,500.00 from Peter Mwangi on 07/03/2026 at 08:36 AM. New M-PESA balance is Ksh173,080.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     271.13 ms /    83 tokens (    3.27 ms per token,   306.13 tokens per second)
llama_perf_context_print:        eval time =    2193.52 ms /    97 runs   (   22.61 ms per token,    44.22 tokens per second)
llama_perf_context_print:       total time =    2590.29 ms /   180 tokens
llama_perf_context_print:    graphs reused =         95
Llama.generate: 120 prefix-match hit, remaining 79 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03070013
date: 2026-03-07
time: 08:36
type: Income
domain: bank_transfer_receive_money
entity: Peter Mwangi
amount: 7500.0
balance: 173080.0
fee: 0.0
reference: TX03070013

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03070013
Type       : income
Domain     : bank_transfer_receive_money
Entity     : Peter Mwangi
Amount     : 7500.0
Balance    : 173080.0
Latency: 2.596s
Saved rows: 13

--------------------------------------------------------------------------------
SMS 14/50
--------------------------------------------------------------------------------
SMS: TX03070014 Confirmed. Ksh3,500.00 sent to Mary Wanjiku on 07/03/2026 at 02:02 PM. Transaction cost, Ksh10.00. New M-PESA balance is Ksh169,570.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     260.84 ms /    79 tokens (    3.30 ms per token,   302.87 tokens per second)
llama_perf_context_print:        eval time =    2171.61 ms /    95 runs   (   22.86 ms per token,    43.75 tokens per second)
llama_perf_context_print:       total time =    2555.01 ms /   174 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 116 prefix-match hit, remaining 81 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03070014
date: 2026-03-07
time: 02:02
type: Expense
domain: send_money
entity: Mary Wanjiku
amount: 3500.0
balance: 169570.0
fee: 10.0
reference: TX03070014

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03070014
Type       : expense
Domain     : send_money
Entity     : Mary Wanjiku
Amount     : 3500.0
Balance    : 169570.0
Latency: 2.561s
Saved rows: 14

--------------------------------------------------------------------------------
SMS 15/50
--------------------------------------------------------------------------------
SMS: TX03080015 Confirmed. Ksh7,500.00 paid to Airtel Money on 08/03/2026 at 08:49 AM. Transaction cost, Ksh10.00. New M-PESA balance is Ksh162,060.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     345.57 ms /    81 tokens (    4.27 ms per token,   234.39 tokens per second)
llama_perf_context_print:        eval time =     293.21 ms /    13 runs   (   22.55 ms per token,    44.34 tokens per second)
llama_perf_context_print:       total time =     656.42 ms /    94 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 120 prefix-match hit, remaining 79 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03080015

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03080015
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.663s
Saved rows: 15

--------------------------------------------------------------------------------
SMS 16/50
--------------------------------------------------------------------------------
SMS: TX03080016 Confirmed. You have received Ksh1,500.00 from Grace Njeri on 08/03/2026 at 01:18 PM. New M-PESA balance is Ksh163,560.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     259.81 ms /    79 tokens (    3.29 ms per token,   304.07 tokens per second)
llama_perf_context_print:        eval time =     294.19 ms /    13 runs   (   22.63 ms per token,    44.19 tokens per second)
llama_perf_context_print:       total time =     571.70 ms /    92 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 116 prefix-match hit, remaining 82 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03080016

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03080016
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.579s
Saved rows: 16

--------------------------------------------------------------------------------
SMS 17/50
--------------------------------------------------------------------------------
SMS: TX03090017 Confirmed. Ksh1,250.00 paid to Green Valley Shop on 09/03/2026 at 08:49 AM. Transaction cost, Ksh25.00. New M-PESA balance is Ksh162,285.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     267.43 ms /    82 tokens (    3.26 ms per token,   306.62 tokens per second)
llama_perf_context_print:        eval time =    2025.06 ms /    89 runs   (   22.75 ms per token,    43.95 tokens per second)
llama_perf_context_print:       total time =    2407.78 ms /   171 tokens
llama_perf_context_print:    graphs reused =         87
Llama.generate: 120 prefix-match hit, remaining 78 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03090017
date: 2026-03-09
time: 08:49
type: Expense
domain: send_money
entity: Green Valley Shop
amount: 1250.0
balance: 0.0
fee: 25.0
reference: TX03090017

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03090017
Type       : expense
Domain     : send_money
Entity     : Green Valley Shop
Amount     : 1250.0
Balance    : 0.0
Latency: 2.414s
Saved rows: 17

--------------------------------------------------------------------------------
SMS 18/50
--------------------------------------------------------------------------------
SMS: TX03090018 Confirmed. Ksh7,500.00 paid to Wanga Electronics on 09/03/2026 at 01:49 PM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh154,735.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     269.50 ms /    78 tokens (    3.46 ms per token,   289.43 tokens per second)
llama_perf_context_print:        eval time =    2043.62 ms /    89 runs   (   22.96 ms per token,    43.55 tokens per second)
llama_perf_context_print:       total time =    2429.09 ms /   167 tokens
llama_perf_context_print:    graphs reused =         87
Llama.generate: 115 prefix-match hit, remaining 85 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03090018
date: 2026-03-09
time: 01:49
type: Expense
domain: send_money
entity: Wanga Electronics
amount: 7500.0
balance: 0.0
fee: 50.0
reference: TX03090018

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03090018
Type       : expense
Domain     : send_money
Entity     : Wanga Electronics
Amount     : 7500.0
Balance    : 0.0
Latency: 2.435s
Saved rows: 18

--------------------------------------------------------------------------------
SMS 19/50
--------------------------------------------------------------------------------
SMS: TX03100019 Confirmed. You have received Ksh7,500.00 from David Kiptoo on 10/03/2026 at 08:36 AM. New M-PESA balance is Ksh162,235.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     284.16 ms /    85 tokens (    3.34 ms per token,   299.12 tokens per second)
llama_perf_context_print:        eval time =    2216.32 ms /    98 runs   (   22.62 ms per token,    44.22 tokens per second)
llama_perf_context_print:       total time =    2627.45 ms /   183 tokens
llama_perf_context_print:    graphs reused =         96
Llama.generate: 119 prefix-match hit, remaining 78 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03100019
date: 2026-03-10
time: 08:36
type: Income
domain: bank_transfer_receive_money
entity: David Kiptoo
amount: 7500.0
balance: 162235.0
fee: 0.0
reference: TX03100019

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03100019
Type       : income
Domain     : bank_transfer_receive_money
Entity     : David Kiptoo
Amount     : 7500.0
Balance    : 162235.0
Latency: 2.633s
Saved rows: 19

--------------------------------------------------------------------------------
SMS 20/50
--------------------------------------------------------------------------------
SMS: TX03100020 Confirmed. Ksh1,250.00 paid to Safaricom on 10/03/2026 at 02:02 PM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh160,985.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     254.46 ms /    78 tokens (    3.26 ms per token,   306.53 tokens per second)
llama_perf_context_print:        eval time =    2067.32 ms /    91 runs   (   22.72 ms per token,    44.02 tokens per second)
llama_perf_context_print:       total time =    2438.86 ms /   169 tokens
llama_perf_context_print:    graphs reused =         89
Llama.generate: 116 prefix-match hit, remaining 98 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03100020; date: 2026-03-10; time: 02:02; type: expense; domain: bank_transfer_paid; entity: Safaricom; amount: 1250; balance: 160985; fee: 0.0; reference: TX03100020

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03100020; date: 2026-03-10; time: 02:02; type: expense; domain: bank_transfer_paid; entity: Safaricom; amount: 1250; balance: 160985; fee: 0.0; reference: TX03100020
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.445s
Saved rows: 20

--------------------------------------------------------------------------------
SMS 21/50
--------------------------------------------------------------------------------
SMS: TX03110021 Confirmed. Ksh800.00 paid to Water Services via PayBill 88888 for account 66661351 on 11/03/2026 at 08:18 AM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh160,185.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     317.07 ms /    98 tokens (    3.24 ms per token,   309.08 tokens per second)
llama_perf_context_print:        eval time =    1995.51 ms /    88 runs   (   22.68 ms per token,    44.10 tokens per second)
llama_perf_context_print:       total time =    2424.70 ms /   186 tokens
llama_perf_context_print:    graphs reused =         86
Llama.generate: 120 prefix-match hit, remaining 81 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03110021
date: 2026-03-11
time: 08:18
type: Expense
domain: paybill
entity: Water Services
amount: 800.0
balance: null
fee: 0.0
reference: 88888:66661351

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03110021
Type       : expense
Domain     : paybill
Entity     : Water Services
Amount     : 800.0
Balance    : None
Latency: 2.432s
Saved rows: 21

--------------------------------------------------------------------------------
SMS 22/50
--------------------------------------------------------------------------------
SMS: TX03110022 Confirmed. You have received Ksh15,000.00 from Faith Achieng on 11/03/2026 at 02:02 PM. New M-PESA balance is Ksh175,185.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     266.59 ms /    81 tokens (    3.29 ms per token,   303.83 tokens per second)
llama_perf_context_print:        eval time =    2510.63 ms /   109 runs   (   23.03 ms per token,    43.42 tokens per second)
llama_perf_context_print:       total time =    2919.95 ms /   190 tokens
llama_perf_context_print:    graphs reused =        107
Llama.generate: 116 prefix-match hit, remaining 80 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03110022; date: 2026-03-11; time: 02:02; type: income; domain: bank_transfer_received; entity: Faith Achieng; amount: 15000.0; balance: 175185.0; fee: 0.0; reference: TX03110022

This is only a form; actual transaction should include sent_

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03110022; date: 2026-03-11; time: 02:02; type: income; domain: bank_transfer_received; entity: Faith Achieng; amount: 15000.0; balance: 175185.0; fee: 0.0; reference: TX03110022
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.927s
Saved rows: 22

--------------------------------------------------------------------------------
SMS 23/50
--------------------------------------------------------------------------------
SMS: TX03120023 Confirmed. Ksh3,500.00 paid to Quickmart on 12/03/2026 at 09:02 AM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh171,685.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     266.93 ms /    80 tokens (    3.34 ms per token,   299.71 tokens per second)
llama_perf_context_print:        eval time =     296.14 ms /    13 runs   (   22.78 ms per token,    43.90 tokens per second)
llama_perf_context_print:       total time =     580.87 ms /    93 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 120 prefix-match hit, remaining 97 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03120023

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03120023
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.587s
Saved rows: 23

--------------------------------------------------------------------------------
SMS 24/50
--------------------------------------------------------------------------------
SMS: TX03120024 Confirmed. Ksh7,500.00 paid to KPLC via PayBill 88888 for account 49392920 on 12/03/2026 at 02:02 PM. Transaction cost, Ksh25.00. New M-PESA balance is Ksh164,160.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     315.30 ms /    97 tokens (    3.25 ms per token,   307.64 tokens per second)
llama_perf_context_print:        eval time =    2069.59 ms /    91 runs   (   22.74 ms per token,    43.97 tokens per second)
llama_perf_context_print:       total time =    2502.32 ms /   188 tokens
llama_perf_context_print:    graphs reused =         89
Llama.generate: 116 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03120024
date: 2026-03-12
time: 02:02
type: Expense
domain: bill_payment
entity: KPLC
amount: 7500.0
balance: null
fee: 25.0
reference: 88888:49392920

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03120024
Type       : expense
Domain     : bill_payment
Entity     : KPLC
Amount     : 7500.0
Balance    : None
Latency: 2.508s
Saved rows: 24

--------------------------------------------------------------------------------
SMS 25/50
--------------------------------------------------------------------------------
SMS: TX03130025 Confirmed. You have received Ksh1,500.00 from Brian Otieno on 13/03/2026 at 08:49 AM. New M-PESA balance is Ksh165,660.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     273.56 ms /    83 tokens (    3.30 ms per token,   303.40 tokens per second)
llama_perf_context_print:        eval time =    2143.21 ms /    93 runs   (   23.05 ms per token,    43.39 tokens per second)
llama_perf_context_print:       total time =    2537.71 ms /   176 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 120 prefix-match hit, remaining 96 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03130025; date: 2026-03-13; time: 08:49; type: income; domain: bank_transfer_received; entity: Brian Otieno; amount: 1500; balance: 165660.0; fee: 0.0; reference: TX03130025

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03130025; date: 2026-03-13; time: 08:49; type: income; domain: bank_transfer_received; entity: Brian Otieno; amount: 1500; balance: 165660.0; fee: 0.0; reference: TX03130025
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.544s
Saved rows: 25

--------------------------------------------------------------------------------
SMS 26/50
--------------------------------------------------------------------------------
SMS: TX03130026 Confirmed. Ksh3,500.00 paid to Zuku via PayBill 88888 for account 95758349 on 13/03/2026 at 02:02 PM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh162,160.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     309.81 ms /    96 tokens (    3.23 ms per token,   309.87 tokens per second)
llama_perf_context_print:        eval time =    2145.13 ms /    93 runs   (   23.07 ms per token,    43.35 tokens per second)
llama_perf_context_print:       total time =    2574.96 ms /   189 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 116 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03130026
date: 2026-03-13
time: 02:02
type: Expense
domain: bill_payment
entity: Zuku
amount: 3500.0
balance: 0.0
fee: 0.0
reference: 88888:95758349

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03130026
Type       : expense
Domain     : bill_payment
Entity     : Zuku
Amount     : 3500.0
Balance    : 0.0
Latency: 2.580s
Saved rows: 26

--------------------------------------------------------------------------------
SMS 27/50
--------------------------------------------------------------------------------
SMS: TX03140027 Confirmed. Ksh1,000.00 sent to Mary Wanjiku on 14/03/2026 at 09:02 AM. Transaction cost, Ksh25.00. New M-PESA balance is Ksh161,135.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     278.41 ms /    83 tokens (    3.35 ms per token,   298.12 tokens per second)
llama_perf_context_print:        eval time =    2093.45 ms /    92 runs   (   22.75 ms per token,    43.95 tokens per second)
llama_perf_context_print:       total time =    2489.53 ms /   175 tokens
llama_perf_context_print:    graphs reused =         90
Llama.generate: 120 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03140027; date: 2026-03-14; time: 09:02; type: expense; domain: send_money; entity: Mary Wanjiku; amount: 1000.0; balance: 0; fee: 25.0; reference: T000000000000

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03140027; date: 2026-03-14; time: 09:02; type: expense; domain: send_money; entity: Mary Wanjiku; amount: 1000.0; balance: 0; fee: 25.0; reference: T000000000000
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.495s
Saved rows: 27

--------------------------------------------------------------------------------
SMS 28/50
--------------------------------------------------------------------------------
SMS: TX03140028 Confirmed. Fuliza loan of Ksh3,000.00 received on 14/03/2026 at 02:02 PM. New M-PESA balance is Ksh164,135.00. Fuliza outstanding balance is Ksh3,000.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     268.98 ms /    83 tokens (    3.24 ms per token,   308.57 tokens per second)
llama_perf_context_print:        eval time =    2111.06 ms /    93 runs   (   22.70 ms per token,    44.05 tokens per second)
llama_perf_context_print:       total time =    2498.48 ms /   176 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 116 prefix-match hit, remaining 78 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03140028
date: 2026-03-14
time: 11:02
type: Income
domain: bank_transfer
entity: Fuliza Bank
amount: 3000.0
balance: 164135.0
fee: 0.0
reference: TX03140028

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03140028
Type       : income
Domain     : bank_transfer
Entity     : Fuliza Bank
Amount     : 3000.0
Balance    : 164135.0
Latency: 2.504s
Saved rows: 28

--------------------------------------------------------------------------------
SMS 29/50
--------------------------------------------------------------------------------
SMS: TX03150029 Confirmed. Ksh500.00 paid to Airtel Money on 15/03/2026 at 09:02 AM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh163,635.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     258.54 ms /    78 tokens (    3.31 ms per token,   301.70 tokens per second)
llama_perf_context_print:        eval time =     300.77 ms /    13 runs   (   23.14 ms per token,    43.22 tokens per second)
llama_perf_context_print:       total time =     576.90 ms /    91 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 80 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03150029

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03150029
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.582s
Saved rows: 29

--------------------------------------------------------------------------------
SMS 30/50
--------------------------------------------------------------------------------
SMS: TX03150030 Confirmed. You have received Ksh5,000.00 from Peter Mwangi on 15/03/2026 at 01:36 PM. New M-PESA balance is Ksh168,635.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     334.79 ms /    80 tokens (    4.18 ms per token,   238.96 tokens per second)
llama_perf_context_print:        eval time =    2244.70 ms /    97 runs   (   23.14 ms per token,    43.21 tokens per second)
llama_perf_context_print:       total time =    2706.41 ms /   177 tokens
llama_perf_context_print:    graphs reused =         95
Llama.generate: 116 prefix-match hit, remaining 98 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03150030; date: 2026-03-15; time: 13:36; type: income; domain: bank_transfer_receive_money; entity: Peter Mwangi; amount: 5000.0; balance: 168635.0; fee: 0.0; reference: TX03150030

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03150030; date: 2026-03-15; time: 13:36; type: income; domain: bank_transfer_receive_money; entity: Peter Mwangi; amount: 5000.0; balance: 168635.0; fee: 0.0; reference: TX03150030
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.713s
Saved rows: 30

--------------------------------------------------------------------------------
SMS 31/50
--------------------------------------------------------------------------------
SMS: TX03160031 Confirmed. Ksh800.00 paid to Water Services via PayBill 88888 for account 98550256 on 16/03/2026 at 08:18 AM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh167,835.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     316.67 ms /    98 tokens (    3.23 ms per token,   309.47 tokens per second)
llama_perf_context_print:        eval time =    2251.72 ms /    96 runs   (   23.46 ms per token,    42.63 tokens per second)
llama_perf_context_print:       total time =    2696.82 ms /   194 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 120 prefix-match hit, remaining 83 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03160031
date: 2026-03-16
time: 08:18
type: Expense
domain: paybill: 88888:98550256
entity: Water Services
amount: 0.0
balance: null
fee: 0.0
reference: TX03160031

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03160031
Type       : expense
Domain     : paybill: 88888:98550256
Entity     : Water Services
Amount     : 0.0
Balance    : None
Latency: 2.703s
Saved rows: 31

--------------------------------------------------------------------------------
SMS 32/50
--------------------------------------------------------------------------------
SMS: TX03160032 Confirmed. Fuliza loan of Ksh5,000.00 received on 16/03/2026 at 01:49 PM. New M-PESA balance is Ksh172,835.00. Fuliza outstanding balance is Ksh5,000.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     276.88 ms /    83 tokens (    3.34 ms per token,   299.77 tokens per second)
llama_perf_context_print:        eval time =    2496.39 ms /   109 runs   (   22.90 ms per token,    43.66 tokens per second)
llama_perf_context_print:       total time =    2918.27 ms /   192 tokens
llama_perf_context_print:    graphs reused =        107
Llama.generate: 116 prefix-match hit, remaining 82 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03160032; date: 2026-03-16; time: 13:49; type: income; domain: bank_transfer; entity: Fuliza; amount: 5000.0; balance: 172835.0; fee: 0.0; reference: T00000000-0012-0000-0000-00

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03160032; date: 2026-03-16; time: 13:49; type: income; domain: bank_transfer; entity: Fuliza; amount: 5000.0; balance: 172835.0; fee: 0.0; reference: T00000000-0012-0000-0000-00
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.924s
Saved rows: 32

--------------------------------------------------------------------------------
SMS 33/50
--------------------------------------------------------------------------------
SMS: TX03170033 Confirmed. Ksh5,000.00 sent to John Kamau on 17/03/2026 at 08:36 AM. Transaction cost, Ksh30.00. New M-PESA balance is Ksh167,805.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     270.61 ms /    82 tokens (    3.30 ms per token,   303.02 tokens per second)
llama_perf_context_print:        eval time =    2155.29 ms /    94 runs   (   22.93 ms per token,    43.61 tokens per second)
llama_perf_context_print:       total time =    2549.98 ms /   176 tokens
llama_perf_context_print:    graphs reused =         92
Llama.generate: 120 prefix-match hit, remaining 98 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03170033
date: 2026-03-17
time: 08:36
type: Expense
domain: send_money
entity: John Kamau
amount: 5000.0
balance: 167805.0
fee: 30.0
reference: TX03170033

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03170033
Type       : expense
Domain     : send_money
Entity     : John Kamau
Amount     : 5000.0
Balance    : 167805.0
Latency: 2.555s
Saved rows: 33

--------------------------------------------------------------------------------
SMS 34/50
--------------------------------------------------------------------------------
SMS: TX03170034 Confirmed. Ksh1,250.00 paid to Safaricom via PayBill 88888 for account 97225156 on 17/03/2026 at 02:02 PM. Transaction cost, Ksh15.00. New M-PESA balance is Ksh166,540.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     316.42 ms /    98 tokens (    3.23 ms per token,   309.71 tokens per second)
llama_perf_context_print:        eval time =    2109.00 ms /    92 runs   (   22.92 ms per token,    43.62 tokens per second)
llama_perf_context_print:       total time =    2546.28 ms /   190 tokens
llama_perf_context_print:    graphs reused =         90
Llama.generate: 116 prefix-match hit, remaining 81 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03170034
date: 2026-03-17
time: 02:02
type: Expense
domain: bill_payment
entity: Safaricom
amount: 1250.0
balance: null
fee: 15.0
reference: 88888:97225156

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03170034
Type       : expense
Domain     : bill_payment
Entity     : Safaricom
Amount     : 1250.0
Balance    : None
Latency: 2.552s
Saved rows: 34

--------------------------------------------------------------------------------
SMS 35/50
--------------------------------------------------------------------------------
SMS: TX03180035 Confirmed. Ksh3,500.00 paid to Quickmart on 18/03/2026 at 08:36 AM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh162,990.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     312.09 ms /    81 tokens (    3.85 ms per token,   259.54 tokens per second)
llama_perf_context_print:        eval time =    2189.65 ms /    95 runs   (   23.05 ms per token,    43.39 tokens per second)
llama_perf_context_print:       total time =    2629.41 ms /   176 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 120 prefix-match hit, remaining 80 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03180035; date: 2026-03-18; time: 08:36; type: expense; domain: bank_transfer_paid; entity: Quickmart; amount: 3500.0; balance: 162990.0; fee: 50.0; reference: TX03180035

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03180035; date: 2026-03-18; time: 08:36; type: expense; domain: bank_transfer_paid; entity: Quickmart; amount: 3500.0; balance: 162990.0; fee: 50.0; reference: TX03180035
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.635s
Saved rows: 35

--------------------------------------------------------------------------------
SMS 36/50
--------------------------------------------------------------------------------
SMS: TX03180036 Confirmed. You have received Ksh10,000.00 from Ann Mueni on 18/03/2026 at 01:27 PM. New M-PESA balance is Ksh172,990.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     259.88 ms /    80 tokens (    3.25 ms per token,   307.83 tokens per second)
llama_perf_context_print:        eval time =    2120.75 ms /    93 runs   (   22.80 ms per token,    43.85 tokens per second)
llama_perf_context_print:       total time =    2501.85 ms /   173 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 116 prefix-match hit, remaining 82 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03180036
date: 2026-03-18
time: 13:27
type: Income
domain: bank_transfer_receive_money
entity: Ann Mueni
amount: 10000.0
balance: 0.0
fee: 0.0
reference: TX03180036

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03180036
Type       : income
Domain     : bank_transfer_receive_money
Entity     : Ann Mueni
Amount     : 10000.0
Balance    : 0.0
Latency: 2.509s
Saved rows: 36

--------------------------------------------------------------------------------
SMS 37/50
--------------------------------------------------------------------------------
SMS: TX03190037 Confirmed. Ksh5,000.00 sent to Ann Mueni on 19/03/2026 at 09:02 AM. Transaction cost, Ksh10.00. New M-PESA balance is Ksh167,980.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     271.81 ms /    82 tokens (    3.31 ms per token,   301.69 tokens per second)
llama_perf_context_print:        eval time =    2140.97 ms /    94 runs   (   22.78 ms per token,    43.91 tokens per second)
llama_perf_context_print:       total time =    2536.47 ms /   176 tokens
llama_perf_context_print:    graphs reused =         92
Llama.generate: 120 prefix-match hit, remaining 95 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03190037
date: 2026-03-19
time: 09:02
type: Expense
domain: send_money
entity: Ann Mueni
amount: 5000.0
balance: 167980.0
fee: 10.0
reference: TX03190037

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03190037
Type       : expense
Domain     : send_money
Entity     : Ann Mueni
Amount     : 5000.0
Balance    : 167980.0
Latency: 2.542s
Saved rows: 37

--------------------------------------------------------------------------------
SMS 38/50
--------------------------------------------------------------------------------
SMS: TX03190038 Confirmed. Ksh500.00 paid to KPLC via PayBill 88888 for account 14216175 on 19/03/2026 at 01:18 PM. Transaction cost, Ksh10.00. New M-PESA balance is Ksh167,470.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     314.11 ms /    95 tokens (    3.31 ms per token,   302.44 tokens per second)
llama_perf_context_print:        eval time =    2087.62 ms /    90 runs   (   23.20 ms per token,    43.11 tokens per second)
llama_perf_context_print:       total time =    2521.26 ms /   185 tokens
llama_perf_context_print:    graphs reused =         88
Llama.generate: 115 prefix-match hit, remaining 84 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03190038
date: 2026-03-19
time: 01:18
type: Expense
domain: bill_payment
entity: KPLC
amount: 500.0
balance: null
fee: 10.0
reference: 88888:14216175

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03190038
Type       : expense
Domain     : bill_payment
Entity     : KPLC
Amount     : 500.0
Balance    : None
Latency: 2.529s
Saved rows: 38

--------------------------------------------------------------------------------
SMS 39/50
--------------------------------------------------------------------------------
SMS: TX03200039 Confirmed. You have received Ksh5,000.00 from Brian Otieno on 20/03/2026 at 08:36 AM. New M-PESA balance is Ksh172,470.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     347.68 ms /    84 tokens (    4.14 ms per token,   241.60 tokens per second)
llama_perf_context_print:        eval time =    2154.35 ms /    95 runs   (   22.68 ms per token,    44.10 tokens per second)
llama_perf_context_print:       total time =    2627.03 ms /   179 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 119 prefix-match hit, remaining 81 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03200039
date: 2026-03-20
time: 08:36
type: Income
domain: bank_transfer_receive
entity: Brian Otieno
amount: 5000.0
balance: 172470.0
fee: 0.0
reference: TX03200039

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03200039
Type       : income
Domain     : bank_transfer_receive
Entity     : Brian Otieno
Amount     : 5000.0
Balance    : 172470.0
Latency: 2.633s
Saved rows: 39

--------------------------------------------------------------------------------
SMS 40/50
--------------------------------------------------------------------------------
SMS: TX03200040 Confirmed. You have received Ksh3,000.00 from Faith Achieng on 20/03/2026 at 01:49 PM. New M-PESA balance is Ksh175,470.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     265.15 ms /    81 tokens (    3.27 ms per token,   305.49 tokens per second)
llama_perf_context_print:        eval time =    2171.80 ms /    96 runs   (   22.62 ms per token,    44.20 tokens per second)
llama_perf_context_print:       total time =    2561.15 ms /   177 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 116 prefix-match hit, remaining 96 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03200040; date: 2026-03-20; time: 14:49; type: income; domain: bank_transfer_received; entity: Faith Achieng; amount: 3000.0; balance: 175470.0; fee: 0.0; reference: TX03200040

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03200040; date: 2026-03-20; time: 14:49; type: income; domain: bank_transfer_received; entity: Faith Achieng; amount: 3000.0; balance: 175470.0; fee: 0.0; reference: TX03200040
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.566s
Saved rows: 40

--------------------------------------------------------------------------------
SMS 41/50
--------------------------------------------------------------------------------
SMS: TX03210041 Confirmed. Ksh2,500.00 withdrawn from M-PESA at Agent 201639 - John Kamau on 21/03/2026 at 08:27 AM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh172,920.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     305.48 ms /    96 tokens (    3.18 ms per token,   314.26 tokens per second)
llama_perf_context_print:        eval time =    2262.24 ms /    99 runs   (   22.85 ms per token,    43.76 tokens per second)
llama_perf_context_print:       total time =    2697.82 ms /   195 tokens
llama_perf_context_print:    graphs reused =         97
Llama.generate: 120 prefix-match hit, remaining 79 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03210041
date: 21/03/2026
time: 08:27
type: Expense
domain: M-PESA
entity: Agent 201639
amount: 2500.0
balance: 172920.0
fee: 0.0
reference: TX03210041

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03210041
Type       : expense
Domain     : M-PESA
Entity     : Agent 201639
Amount     : 2500.0
Balance    : 172920.0
Latency: 2.703s
Saved rows: 41

--------------------------------------------------------------------------------
SMS 42/50
--------------------------------------------------------------------------------
SMS: TX03210042 Confirmed. Ksh2,500.00 paid to Naivas Supermarket on 21/03/2026 at 01:49 PM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh170,370.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     343.84 ms /    79 tokens (    4.35 ms per token,   229.76 tokens per second)
llama_perf_context_print:        eval time =    2035.53 ms /    89 runs   (   22.87 ms per token,    43.72 tokens per second)
llama_perf_context_print:       total time =    2496.35 ms /   168 tokens
llama_perf_context_print:    graphs reused =         87
Llama.generate: 116 prefix-match hit, remaining 84 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03210042; date: 2026-03-21; time: 01:49; type: expense; domain: bank_transfer_paid; entity: Naivas Supermarket; amount: 2500.0; balance: 0; fee: 0.0; reference: TX03210042

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03210042; date: 2026-03-21; time: 01:49; type: expense; domain: bank_transfer_paid; entity: Naivas Supermarket; amount: 2500.0; balance: 0; fee: 0.0; reference: TX03210042
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.502s
Saved rows: 42

--------------------------------------------------------------------------------
SMS 43/50
--------------------------------------------------------------------------------
SMS: TX03220043 Confirmed. You have received Ksh10,000.00 from Peter Mwangi on 22/03/2026 at 08:18 AM. New M-PESA balance is Ksh180,370.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     277.73 ms /    84 tokens (    3.31 ms per token,   302.45 tokens per second)
llama_perf_context_print:        eval time =     297.16 ms /    13 runs   (   22.86 ms per token,    43.75 tokens per second)
llama_perf_context_print:       total time =     594.91 ms /    97 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 120 prefix-match hit, remaining 81 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03220043

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03220043
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.600s
Saved rows: 43

--------------------------------------------------------------------------------
SMS 44/50
--------------------------------------------------------------------------------
SMS: TX03220044 Confirmed. You have received Ksh20,000.00 from Mary Wanjiku on 22/03/2026 at 01:27 PM. New M-PESA balance is Ksh200,370.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     264.80 ms /    81 tokens (    3.27 ms per token,   305.89 tokens per second)
llama_perf_context_print:        eval time =    2188.53 ms /    97 runs   (   22.56 ms per token,    44.32 tokens per second)
llama_perf_context_print:       total time =    2579.27 ms /   178 tokens
llama_perf_context_print:    graphs reused =         95
Llama.generate: 116 prefix-match hit, remaining 84 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03220044
date: 2026-03-22
time: 13:27
type: Income
domain: bank_transfer_received
entity: Mary Wanjiku
amount: 20000.0
balance: 200370.0
fee: 0.0
reference: TX03220044

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03220044
Type       : income
Domain     : bank_transfer_received
Entity     : Mary Wanjiku
Amount     : 20000.0
Balance    : 200370.0
Latency: 2.585s
Saved rows: 44

--------------------------------------------------------------------------------
SMS 45/50
--------------------------------------------------------------------------------
SMS: TX03230045 Confirmed. You have received Ksh20,000.00 from John Kamau on 23/03/2026 at 08:49 AM. New M-PESA balance is Ksh220,370.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     273.51 ms /    84 tokens (    3.26 ms per token,   307.12 tokens per second)
llama_perf_context_print:        eval time =    2197.70 ms /    96 runs   (   22.89 ms per token,    43.68 tokens per second)
llama_perf_context_print:       total time =    2599.76 ms /   180 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 120 prefix-match hit, remaining 78 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03230045
date: 2026-03-23
time: 08:49
type: Income
domain: bank_transfer_receive
entity: John Kamau
amount: 20000.0
balance: 220370.0
fee: 0.0
reference: TX03230045

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03230045
Type       : income
Domain     : bank_transfer_receive
Entity     : John Kamau
Amount     : 20000.0
Balance    : 220370.0
Latency: 2.606s
Saved rows: 45

--------------------------------------------------------------------------------
SMS 46/50
--------------------------------------------------------------------------------
SMS: TX03230046 Confirmed. Ksh3,500.00 paid to Naivas Supermarket on 23/03/2026 at 01:18 PM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh216,870.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     256.55 ms /    78 tokens (    3.29 ms per token,   304.03 tokens per second)
llama_perf_context_print:        eval time =    2234.91 ms /    96 runs   (   23.28 ms per token,    42.95 tokens per second)
llama_perf_context_print:       total time =    2618.93 ms /   174 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 116 prefix-match hit, remaining 94 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03230046; date: 2026-03-23; time: 01:18; type: expense; domain: bank_transfer_paid; entity: Naivas Supermarket; amount: 3500.0; balance: 216870.0; fee: 0.0; reference: TX03230046

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03230046; date: 2026-03-23; time: 01:18; type: expense; domain: bank_transfer_paid; entity: Naivas Supermarket; amount: 3500.0; balance: 216870.0; fee: 0.0; reference: TX03230046
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 2.626s
Saved rows: 46

--------------------------------------------------------------------------------
SMS 47/50
--------------------------------------------------------------------------------
SMS: TX03240047 Confirmed. Ksh800.00 withdrawn from M-PESA at Agent 526156 - John Kamau on 24/03/2026 at 09:02 AM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh216,020.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     309.32 ms /    94 tokens (    3.29 ms per token,   303.89 tokens per second)
llama_perf_context_print:        eval time =    2215.20 ms /    95 runs   (   23.32 ms per token,    42.89 tokens per second)
llama_perf_context_print:       total time =    2650.04 ms /   189 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 120 prefix-match hit, remaining 77 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03240047
date: 2026-03-24
time: 09:02
type: Expense
domain: cash_withdrawal
entity: Agent 526156
amount: 800.0
balance: 216.0
fee: 50.0
reference: TX03240047

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03240047
Type       : expense
Domain     : cash_withdrawal
Entity     : Agent 526156
Amount     : 800.0
Balance    : 216.0
Latency: 2.656s
Saved rows: 47

--------------------------------------------------------------------------------
SMS 48/50
--------------------------------------------------------------------------------
SMS: TX03240048 Confirmed. Ksh2,500.00 paid to Wanga Electronics on 24/03/2026 at 01:49 PM. Transaction cost, Ksh0.00. New M-PESA balance is Ksh213,520.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     251.58 ms /    77 tokens (    3.27 ms per token,   306.07 tokens per second)
llama_perf_context_print:        eval time =    2125.50 ms /    93 runs   (   22.85 ms per token,    43.75 tokens per second)
llama_perf_context_print:       total time =    2500.63 ms /   170 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 116 prefix-match hit, remaining 84 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03240048
date: 2026-03-24
time: 13:49
type: Expense
domain: send_money
entity: Wanga Electronics
amount: 2500.0
balance: 213520.0
fee: 0.0
reference: TX03240048

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03240048
Type       : expense
Domain     : send_money
Entity     : Wanga Electronics
Amount     : 2500.0
Balance    : 213520.0
Latency: 2.507s
Saved rows: 48

--------------------------------------------------------------------------------
SMS 49/50
--------------------------------------------------------------------------------
SMS: TX03250049 Confirmed. You have received Ksh15,000.00 from Brian Otieno on 25/03/2026 at 08:49 AM. New M-PESA balance is Ksh228,520.00. Transaction cost, Ksh0.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     276.76 ms /    84 tokens (    3.29 ms per token,   303.51 tokens per second)
llama_perf_context_print:        eval time =     292.97 ms /    13 runs   (   22.54 ms per token,    44.37 tokens per second)
llama_perf_context_print:       total time =     590.12 ms /    97 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 79 prompt tokens to eval

MODEL OUTPUT:
transaction_id: TX03250049

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03250049
Type       : None
Domain     : None
Entity     : None
Amount     : None
Balance    : None
Latency: 0.596s
Saved rows: 49

--------------------------------------------------------------------------------
SMS 50/50
--------------------------------------------------------------------------------
SMS: TX03250050 Confirmed. Ksh3,500.00 paid to Wanga Electronics on 25/03/2026 at 01:49 PM. Transaction cost, Ksh50.00. New M-PESA balance is Ksh224,970.00.

llama_perf_context_print:        load time =     663.69 ms
llama_perf_context_print: prompt eval time =     292.55 ms /    79 tokens (    3.70 ms per token,   270.04 tokens per second)
llama_perf_context_print:        eval time =    2155.19 ms /    94 runs   (   22.93 ms per token,    43.62 tokens per second)
llama_perf_context_print:       total time =    2572.32 ms /   173 tokens
llama_perf_context_print:    graphs reused =         92

MODEL OUTPUT:
transaction_id: TX03250050
date: 2026-03-25
time: 01:49
type: Expense
domain: send_money
entity: Wanga Electronics
amount: 3500.0
balance: 224970.0
fee: 50.0
reference: TX03250050

Parser: KEY/VALUE
Status: ✓ SUCCESS
Transaction: TX03250050
Type       : expense
Domain     : send_money
Entity     : Wanga Electronics
Amount     : 3500.0
Balance    : 224970.0
Latency: 2.578s
Saved rows: 50

================================================================================
EXTRACTION COMPLETE
================================================================================
Total SMS processed: 50
Output columns: ['sms', 'transaction_id', 'date', 'time', 'type', 'domain', 'entity', 'amount', 'balance']
Output file: /kaggle/working/sme_ledger_50_results.csv

================================================================================
EXTRACTION SUMMARY
================================================================================
Transaction IDs extracted: 50/50
Dates extracted: 27/50
Amounts extracted: 27/50
Balances extracted: 22/50

================================================================================
FINAL LEDGER
================================================================================

,sms,transaction_id,date,time,type,domain,entity,amount,balance
0,"TX03010001 Confirmed. You have received Ksh7,5...",TX03010001; date: 2026-03-01; time: 08:18; typ...,None,None,None,None,None,NaN,NaN
1,"TX03010002 Confirmed. You have received Ksh2,5...",TX03010002,2026-03-01,12:27,income,bank_transfer_receive_money,Peter Mwangi,2500.0,16000.0
2,TX03020003 Confirmed. Ksh500.00 paid to Green ...,TX03020003,2026-03-02,09:02,expense,send_money,Green Valley Shop,500.0,0.0
3,TX03020004 Confirmed. Ksh500.00 sent to David ...,TX03020004,None,None,None,None,None,NaN,NaN
4,"TX03030005 Confirmed. Ksh1,500.00 paid to Wang...",TX03030005; date: 2026-03-03; time: 08:27; typ...,None,None,None,None,None,NaN,NaN
5,"TX03030006 Confirmed. Ksh1,000.00 paid to Airt...",TX03030006; date: 2026-03-03; time: 01:49; typ...,None,None,None,None,None,NaN,NaN
6,"TX03040007 Confirmed. You have received Ksh2,5...",TX03040007,2026-03-04,08:18,income,bank_transfer_receive_money,Grace Njeri,2500.0,158980.0
7,TX03040008 Confirmed. Ksh500.00 sent to Peter ...,TX03040008,None,None,None,None,None,NaN,NaN
8,"TX03050009 Confirmed. You have received Ksh7,5...",TX03050009,2026-03-05,08:49,income,bank_transfer_received,Grace Njeri,7500.0,165930.0
9,"TX03050010 Confirmed. You have received Ksh2,5...",TX03050010,2026-03-05,12:02,income,bank_transfer_receive_money,Ann Mueni,2500.0,168430.0
10,TX03060011 Confirmed. Ksh800.00 withdrawn from...,TX03060011; date: 2026-03-06; time: 08:27; dom...,None,None,None,None,None,NaN,NaN
11,"TX03060012 Confirmed. Ksh2,000.00 paid to Airt...",TX03060012; date: 2026-03-06; time: 01:36; typ...,None,None,None,None,None,NaN,NaN
12,"TX03070013 Confirmed. You have received Ksh7,5...",TX03070013,2026-03-07,08:36,income,bank_transfer_receive_money,Peter Mwangi,7500.0,173080.0
13,"TX03070014 Confirmed. Ksh3,500.00 sent to Mary...",TX03070014,2026-03-07,02:02,expense,send_money,Mary Wanjiku,3500.0,169570.0
14,"TX03080015 Confirmed. Ksh7,500.00 paid to Airt...",TX03080015,None,None,None,None,None,NaN,NaN
15,"TX03080016 Confirmed. You have received Ksh1,5...",TX03080016,None,None,None,None,None,NaN,NaN
16,"TX03090017 Confirmed. Ksh1,250.00 paid to Gree...",TX03090017,2026-03-09,08:49,expense,send_money,Green Valley Shop,1250.0,0.0
17,"TX03090018 Confirmed. Ksh7,500.00 paid to Wang...",TX03090018,2026-03-09,01:49,expense,send_money,Wanga Electronics,7500.0,0.0
18,"TX03100019 Confirmed. You have received Ksh7,5...",TX03100019,2026-03-10,08:36,income,bank_transfer_receive_money,David Kiptoo,7500.0,162235.0
19,"TX03100020 Confirmed. Ksh1,250.00 paid to Safa...",TX03100020; date: 2026-03-10; time: 02:02; typ...,None,None,None,None,None,NaN,NaN
20,TX03110021 Confirmed. Ksh800.00 paid to Water ...,TX03110021,2026-03-11,08:18,expense,paybill,Water Services,800.0,NaN
21,"TX03110022 Confirmed. You have received Ksh15,...",TX03110022; date: 2026-03-11; time: 02:02; typ...,None,None,None,None,None,NaN,NaN
22,"TX03120023 Confirmed. Ksh3,500.00 paid to Quic...",TX03120023,None,None,None,None,None,NaN,NaN
23,"TX03120024 Confirmed. Ksh7,500.00 paid to KPLC...",TX03120024,2026-03-12,02:02,expense,bill_payment,KPLC,7500.0,NaN
24,"TX03130025 Confirmed. You have received Ksh1,5...",TX03130025; date: 2026-03-13; time: 08:49; typ...,None,None,None,None,None,NaN,NaN
25,"TX03130026 Confirmed. Ksh3,500.00 paid to Zuku...",TX03130026,2026-03-13,02:02,expense,bill_payment,Zuku,3500.0,0.0
26,"TX03140027 Confirmed. Ksh1,000.00 sent to Mary...",TX03140027; date: 2026-03-14; time: 09:02; typ...,None,None,None,None,None,NaN,NaN
27,"TX03140028 Confirmed. Fuliza loan of Ksh3,000....",TX03140028,2026-03-14,11:02,income,bank_transfer,Fuliza Bank,3000.0,164135.0
28,TX03150029 Confirmed. Ksh500.00 paid to Airtel...,TX03150029,None,None,None,None,None,NaN,NaN
29,"TX03150030 Confirmed. You have received Ksh5,0...",TX03150030; date: 2026-03-15; time: 13:36; typ...,None,None,None,None,None,NaN,NaN
30,TX03160031 Confirmed. Ksh800.00 paid to Water ...,TX03160031,2026-03-16,08:18,expense,paybill: 88888:98550256,Water Services,0.0,NaN
31,"TX03160032 Confirmed. Fuliza loan of Ksh5,000....",TX03160032; date: 2026-03-16; time: 13:49; typ...,None,None,None,None,None,NaN,NaN
32,"TX03170033 Confirmed. Ksh5,000.00 sent to John...",TX03170033,2026-03-17,08:36,expense,send_money,John Kamau,5000.0,167805.0
33,"TX03170034 Confirmed. Ksh1,250.00 paid to Safa...",TX03170034,2026-03-17,02:02,expense,bill_payment,Safaricom,1250.0,NaN
34,"TX03180035 Confirmed. Ksh3,500.00 paid to Quic...",TX03180035; date: 2026-03-18; time: 08:36; typ...,None,None,None,None,None,NaN,NaN
35,"TX03180036 Confirmed. You have received Ksh10,...",TX03180036,2026-03-18,13:27,income,bank_transfer_receive_money,Ann Mueni,10000.0,0.0
36,"TX03190037 Confirmed. Ksh5,000.00 sent to Ann ...",TX03190037,2026-03-19,09:02,expense,send_money,Ann Mueni,5000.0,167980.0
37,TX03190038 Confirmed. Ksh500.00 paid to KPLC v...,TX03190038,2026-03-19,01:18,expense,bill_payment,KPLC,500.0,NaN
38,"TX03200039 Confirmed. You have received Ksh5,0...",TX03200039,2026-03-20,08:36,income,bank_transfer_receive,Brian Otieno,5000.0,172470.0
39,"TX03200040 Confirmed. You have received Ksh3,0...",TX03200040; date: 2026-03-20; time: 14:49; typ...,None,None,None,None,None,NaN,NaN
40,"TX03210041 Confirmed. Ksh2,500.00 withdrawn fr...",TX03210041,21/03/2026,08:27,expense,M-PESA,Agent 201639,2500.0,172920.0
41,"TX03210042 Confirmed. Ksh2,500.00 paid to Naiv...",TX03210042; date: 2026-03-21; time: 01:49; typ...,None,None,None,None,None,NaN,NaN
42,"TX03220043 Confirmed. You have received Ksh10,...",TX03220043,None,None,None,None,None,NaN,NaN
43,"TX03220044 Confirmed. You have received Ksh20,...",TX03220044,2026-03-22,13:27,income,bank_transfer_received,Mary Wanjiku,20000.0,200370.0
44,"TX03230045 Confirmed. You have received Ksh20,...",TX03230045,2026-03-23,08:49,income,bank_transfer_receive,John Kamau,20000.0,220370.0
45,"TX03230046 Confirmed. Ksh3,500.00 paid to Naiv...",TX03230046; date: 2026-03-23; time: 01:18; typ...,None,None,None,None,None,NaN,NaN
46,TX03240047 Confirmed. Ksh800.00 withdrawn from...,TX03240047,2026-03-24,09:02,expense,cash_withdrawal,Agent 526156,800.0,216.0
47,"TX03240048 Confirmed. Ksh2,500.00 paid to Wang...",TX03240048,2026-03-24,13:49,expense,send_money,Wanga Electronics,2500.0,213520.0
48,"TX03250049 Confirmed. You have received Ksh15,...",TX03250049,None,None,None,None,None,NaN,NaN
49,"TX03250050 Confirmed. Ksh3,500.00 paid to Wang...",TX03250050,2026-03-25,01:49,expense,send_money,Wanga Electronics,3500.0,224970.0

## Financial analysis and dashboard
Run this cell after the `test.csv` inference cell. It builds a Pandas ledger, computes financial KPIs, displays charts and filters, and exports analysis CSVs.

In [6]:
# ============================================================
# SME-LEDGER V2 — FINANCIAL HEALTH ANALYTICS & DASHBOARD
#
# RUN AFTER CELL 5
#
# Cell 5 output:
#   /kaggle/working/sme_ledger_50_results.csv
#
# This cell:
#   1. Loads the structured model output
#   2. Cleans and validates the ledger
#   3. Computes financial-health KPIs
#   4. Analyzes income and expenditure
#   5. Analyzes liquidity / balance
#   6. Analyzes spending concentration
#   7. Analyzes transaction frequency
#   8. Analyzes fees
#   9. Flags financial-risk indicators
#  10. Produces interactive Plotly visualizations
#  11. Saves analysis-ready CSV files
#
# IMPORTANT:
#   This is descriptive financial analysis, not a lending decision
#   or financial advice system.
# ============================================================

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

from IPython.display import display, Markdown

# ============================================================
# 1. CONFIGURATION
# ============================================================

INPUT_CSV = "/kaggle/working/sme_ledger_50_results.csv"

OUTPUT_LEDGER = "/kaggle/working/sme_ledger_final_analysis.csv"
OUTPUT_MONTHLY = "/kaggle/working/sme_ledger_monthly_analysis.csv"
OUTPUT_ENTITY = "/kaggle/working/sme_ledger_entity_analysis.csv"
OUTPUT_DOMAIN = "/kaggle/working/sme_ledger_domain_analysis.csv"
OUTPUT_HEALTH = "/kaggle/working/sme_ledger_financial_health.csv"

# ============================================================
# 2. LOAD STRUCTURED LEDGER
# ============================================================

try:
    ledger = pd.read_csv(INPUT_CSV)
except FileNotFoundError:
    raise FileNotFoundError(
        f"\nCould not find:\n{INPUT_CSV}\n\n"
        "Run Cell 5 first so the 50-SMS extraction CSV exists."
    )

print("=" * 90)
print("SME-LEDGER V2 — FINANCIAL HEALTH ANALYTICS")
print("=" * 90)

print(f"\nLoaded: {INPUT_CSV}")
print(f"Rows: {len(ledger):,}")
print(f"Columns: {len(ledger.columns)}")

# ============================================================
# 3. ENSURE EXPECTED COLUMNS EXIST
# ============================================================

expected_columns = [
    "sms",
    "transaction_id",
    "date",
    "time",
    "type",
    "domain",
    "entity",
    "amount",
    "balance",
    "fee",
    "reference",
    "json_valid",
    "extraction_error",
    "latency_seconds"
]

for col in expected_columns:

    if col not in ledger.columns:

        if col in ["amount", "balance", "fee", "latency_seconds"]:
            ledger[col] = np.nan

        elif col == "json_valid":
            ledger[col] = False

        else:
            ledger[col] = None

# ============================================================
# 4. CLEAN DATA TYPES
# ============================================================

def clean_numeric(series):

    return pd.to_numeric(
        series.astype(str)
        .str.replace(",", "", regex=False)
        .str.replace("Ksh", "", regex=False)
        .str.replace("KES", "", regex=False)
        .str.replace("ksh", "", regex=False)
        .str.strip()
        .replace({
            "": np.nan,
            "nan": np.nan,
            "None": np.nan,
            "none": np.nan,
            "null": np.nan
        }),
        errors="coerce"
    )


for col in ["amount", "balance", "fee"]:
    ledger[col] = clean_numeric(ledger[col])


# ============================================================
# 5. NORMALIZE TRANSACTION TYPE
# ============================================================

ledger["type"] = (
    ledger["type"]
    .fillna("unknown")
    .astype(str)
    .str.strip()
    .str.lower()
)

ledger["direction"] = ledger["type"].map({

    "income": "Income",
    "received": "Income",
    "receive": "Income",
    "deposit": "Income",
    "credit": "Income",

    "expense": "Expense",
    "payment": "Expense",
    "paid": "Expense",
    "sent": "Expense",
    "withdrawal": "Expense",
    "debit": "Expense"

}).fillna("Unknown")


# ============================================================
# 6. CLEAN ENTITY / DOMAIN
# ============================================================

for col in ["entity", "domain"]:

    ledger[col] = (
        ledger[col]
        .fillna("Unknown")
        .astype(str)
        .str.strip()
        .replace({
            "": "Unknown",
            "nan": "Unknown",
            "None": "Unknown",
            "null": "Unknown"
        })
    )


# ============================================================
# 7. DATE / TIME
# ============================================================

ledger["date_parsed"] = pd.to_datetime(
    ledger["date"],
    errors="coerce",
    dayfirst=True
)

# If dates were already YYYY-MM-DD, retry without dayfirst
missing_dates = ledger["date_parsed"].isna()

if missing_dates.any():

    ledger.loc[missing_dates, "date_parsed"] = pd.to_datetime(
        ledger.loc[missing_dates, "date"],
        errors="coerce"
    )

ledger["month"] = ledger["date_parsed"].dt.to_period("M").astype(str)

ledger.loc[
    ledger["date_parsed"].isna(),
    "month"
] = "Unknown date"

ledger["day"] = ledger["date_parsed"].dt.date


# ============================================================
# 8. CORE FINANCIAL VARIABLES
# ============================================================

ledger["income_kes"] = np.where(
    ledger["direction"].eq("Income"),
    ledger["amount"],
    0
)

ledger["expense_kes"] = np.where(
    ledger["direction"].eq("Expense"),
    ledger["amount"],
    0
)

ledger["net_cashflow_kes"] = (
    ledger["income_kes"] -
    ledger["expense_kes"]
)

ledger["fee_kes"] = ledger["fee"].fillna(0)

# ============================================================
# 9. TRANSACTION INDEX
# ============================================================

ledger["transaction_number"] = np.arange(
    1,
    len(ledger) + 1
)


# ============================================================
# 10. DATA QUALITY ANALYSIS
# ============================================================

ledger["missing_amount"] = ledger["amount"].isna()

ledger["missing_balance"] = ledger["balance"].isna()

ledger["missing_date"] = ledger["date_parsed"].isna()

ledger["unknown_direction"] = (
    ledger["direction"] == "Unknown"
)

ledger["invalid_json"] = (
    ledger["json_valid"].astype(str).str.lower()
    .isin(["false", "0", "nan", "none"])
)

# Duplicate references
ref_clean = (
    ledger["reference"]
    .fillna("")
    .astype(str)
    .str.strip()
)

valid_reference = (
    ref_clean.ne("") &
    ~ref_clean.str.lower().isin(
        ["nan", "none", "null"]
    )
)

ledger["possible_duplicate"] = False

ledger.loc[valid_reference, "possible_duplicate"] = (
    ref_clean[valid_reference]
    .duplicated(keep=False)
)

# ============================================================
# 11. BASIC FINANCIAL KPIs
# ============================================================

total_transactions = len(ledger)

valid_transactions = ledger["amount"].notna()

income_rows = ledger[
    ledger["direction"] == "Income"
]

expense_rows = ledger[
    ledger["direction"] == "Expense"
]

total_income = income_rows["amount"].sum()

total_expenses = expense_rows["amount"].sum()

net_cashflow = (
    total_income -
    total_expenses
)

average_transaction = (
    ledger.loc[
        valid_transactions,
        "amount"
    ].mean()
)

median_transaction = (
    ledger.loc[
        valid_transactions,
        "amount"
    ].median()
)

largest_income = (
    income_rows["amount"].max()
    if not income_rows.empty
    else np.nan
)

largest_expense = (
    expense_rows["amount"].max()
    if not expense_rows.empty
    else np.nan
)

income_count = len(income_rows)

expense_count = len(expense_rows)

income_expense_ratio = (
    total_income / total_expenses
    if total_expenses > 0
    else np.nan
)

# ============================================================
# 12. BALANCE / LIQUIDITY
# ============================================================

balance_rows = ledger[
    ledger["balance"].notna()
].copy()

if not balance_rows.empty:

    balance_rows = balance_rows.sort_values(
        ["date_parsed", "transaction_number"],
        na_position="last"
    )

    latest_balance = balance_rows["balance"].iloc[-1]

    lowest_balance = balance_rows["balance"].min()

    highest_balance = balance_rows["balance"].max()

    first_balance = balance_rows["balance"].iloc[0]

    balance_change = (
        latest_balance -
        first_balance
    )

else:

    latest_balance = np.nan
    lowest_balance = np.nan
    highest_balance = np.nan
    first_balance = np.nan
    balance_change = np.nan


# ============================================================
# 13. CASH-FLOW MARGIN
# ============================================================

cashflow_margin = (
    net_cashflow / total_income * 100
    if total_income > 0
    else np.nan
)


# ============================================================
# 14. EXPENSE CONCENTRATION
# ============================================================

expense_entities = (
    expense_rows
    .groupby("entity", dropna=False)["amount"]
    .sum()
    .sort_values(ascending=False)
)

if len(expense_entities) > 0:

    largest_expense_entity = expense_entities.index[0]

    largest_entity_spend = expense_entities.iloc[0]

    largest_entity_share = (
        largest_entity_spend /
        total_expenses * 100
        if total_expenses > 0
        else np.nan
    )

else:

    largest_expense_entity = "N/A"
    largest_entity_spend = np.nan
    largest_entity_share = np.nan


# ============================================================
# 15. DOMAIN ANALYSIS
# ============================================================

domain_expenses = (
    expense_rows
    .groupby("domain", dropna=False)["amount"]
    .agg(
        total_spend="sum",
        transaction_count="count",
        average_transaction="mean"
    )
    .sort_values(
        "total_spend",
        ascending=False
    )
    .reset_index()
)

domain_income = (
    income_rows
    .groupby("domain", dropna=False)["amount"]
    .agg(
        total_income="sum",
        transaction_count="count",
        average_transaction="mean"
    )
    .sort_values(
        "total_income",
        ascending=False
    )
    .reset_index()
)


# ============================================================
# 16. MONTHLY CASH-FLOW ANALYSIS
# ============================================================

monthly = (
    ledger[
        ledger["month"] != "Unknown date"
    ]
    .groupby("month")
    .agg(
        income_kes=("income_kes", "sum"),
        expense_kes=("expense_kes", "sum"),
        net_cashflow_kes=("net_cashflow_kes", "sum"),
        transaction_count=("amount", "count"),
        total_fees_kes=("fee_kes", "sum")
    )
    .reset_index()
)

if not monthly.empty:

    monthly["cashflow_margin_pct"] = np.where(
        monthly["income_kes"] > 0,
        (
            monthly["net_cashflow_kes"] /
            monthly["income_kes"]
        ) * 100,
        np.nan
    )

    monthly["income_expense_ratio"] = np.where(
        monthly["expense_kes"] > 0,
        monthly["income_kes"] /
        monthly["expense_kes"],
        np.nan
    )


# ============================================================
# 17. FINANCIAL HEALTH INDICATORS
# ============================================================

# These are descriptive indicators rather than credit scores.

positive_cashflow = (
    net_cashflow > 0
)

expense_to_income_pct = (
    total_expenses /
    total_income * 100
    if total_income > 0
    else np.nan
)

fee_to_transaction_pct = (
    ledger["fee_kes"].sum() /
    total_income * 100
    if total_income > 0
    else np.nan
)

# Balance stability
if not balance_rows.empty:

    balance_std = balance_rows["balance"].std()

    balance_mean = balance_rows["balance"].mean()

    balance_volatility_pct = (
        balance_std /
        balance_mean * 100
        if balance_mean and balance_mean > 0
        else np.nan
    )

else:

    balance_std = np.nan
    balance_mean = np.nan
    balance_volatility_pct = np.nan


# ============================================================
# 18. FINANCIAL HEALTH SUMMARY
# ============================================================

health_metrics = pd.DataFrame({

    "Metric": [

        "Total transactions",
        "Income transactions",
        "Expense transactions",

        "Total income (KES)",
        "Total expenses (KES)",
        "Net cash flow (KES)",

        "Cash-flow margin (%)",
        "Expense / income (%)",
        "Income / expense ratio",

        "Average transaction (KES)",
        "Median transaction (KES)",

        "Largest income (KES)",
        "Largest expense (KES)",

        "First extracted balance (KES)",
        "Latest extracted balance (KES)",
        "Lowest extracted balance (KES)",
        "Highest extracted balance (KES)",
        "Balance change (KES)",

        "Total fees (KES)",
        "Fees / income (%)",

        "Largest expense entity",
        "Largest entity share of spending (%)",

        "Transactions with missing amount",
        "Transactions with missing date",
        "Unknown transaction direction",
        "Possible duplicate references",
        "Invalid JSON extractions"

    ],

    "Value": [

        total_transactions,
        income_count,
        expense_count,

        total_income,
        total_expenses,
        net_cashflow,

        cashflow_margin,
        expense_to_income_pct,
        income_expense_ratio,

        average_transaction,
        median_transaction,

        largest_income,
        largest_expense,

        first_balance,
        latest_balance,
        lowest_balance,
        highest_balance,
        balance_change,

        ledger["fee_kes"].sum(),
        fee_to_transaction_pct,

        largest_expense_entity,
        largest_entity_share,

        int(ledger["missing_amount"].sum()),
        int(ledger["missing_date"].sum()),
        int(ledger["unknown_direction"].sum()),
        int(ledger["possible_duplicate"].sum()),
        int(ledger["invalid_json"].sum())

    ]

})

# ============================================================
# 19. DASHBOARD HEADER
# ============================================================

display(
    Markdown(
        "# 💰 SME-Ledger V2 — Financial Health Dashboard"
    )
)

display(
    Markdown(
        f"""
### Dataset overview

**Transactions:** {total_transactions:,}

**Income:** KES {total_income:,.2f}

**Expenses:** KES {total_expenses:,.2f}

**Net cash flow:** KES {net_cashflow:,.2f}

**Latest extracted balance:** 
KES {latest_balance:,.2f}
"""
        if pd.notna(latest_balance)
        else
        f"""
### Dataset overview

**Transactions:** {total_transactions:,}

**Income:** KES {total_income:,.2f}

**Expenses:** KES {total_expenses:,.2f}

**Net cash flow:** KES {net_cashflow:,.2f}

**Latest extracted balance:** N/A
"""
    )
)

# ============================================================
# 20. KPI TABLE
# ============================================================

display(
    Markdown("## 📊 Core Financial KPIs")
)

kpi_display = pd.DataFrame({

    "KPI": [
        "Total income",
        "Total expenses",
        "Net cash flow",
        "Average transaction",
        "Median transaction",
        "Income / expense ratio",
        "Cash-flow margin",
        "Latest balance"
    ],

    "Value": [

        f"KES {total_income:,.2f}",

        f"KES {total_expenses:,.2f}",

        f"KES {net_cashflow:,.2f}",

        (
            f"KES {average_transaction:,.2f}"
            if pd.notna(average_transaction)
            else "N/A"
        ),

        (
            f"KES {median_transaction:,.2f}"
            if pd.notna(median_transaction)
            else "N/A"
        ),

        (
            f"{income_expense_ratio:.2f}"
            if pd.notna(income_expense_ratio)
            else "N/A"
        ),

        (
            f"{cashflow_margin:.2f}%"
            if pd.notna(cashflow_margin)
            else "N/A"
        ),

        (
            f"KES {latest_balance:,.2f}"
            if pd.notna(latest_balance)
            else "N/A"
        )

    ]
})

display(kpi_display)


# ============================================================
# 21. FINANCIAL HEALTH OBSERVATIONS
# ============================================================

display(
    Markdown("## 🔎 Financial Health Indicators")
)

observations = []

if positive_cashflow:
    observations.append(
        "🟢 **Positive net cash flow:** "
        "total extracted income exceeds total extracted expenses."
    )
elif net_cashflow < 0:
    observations.append(
        "🔴 **Negative net cash flow:** "
        "extracted expenses exceed extracted income."
    )
else:
    observations.append(
        "🟡 **Neutral cash flow:** "
        "extracted income and expenses are approximately balanced."
    )

if pd.notna(expense_to_income_pct):

    if expense_to_income_pct > 100:
        observations.append(
            "🔴 **Expenses exceed extracted income.**"
        )

    elif expense_to_income_pct > 80:
        observations.append(
            "🟠 **High expense-to-income ratio:** "
            f"expenses represent approximately "
            f"{expense_to_income_pct:.1f}% of extracted income."
        )

    else:
        observations.append(
            "🟢 **Expense-to-income ratio:** "
            f"approximately {expense_to_income_pct:.1f}%."
        )

if pd.notna(balance_change):

    if balance_change > 0:
        observations.append(
            f"🟢 **Balance increased:** "
            f"approximately KES {balance_change:,.2f} "
            "between the first and latest extracted balances."
        )

    elif balance_change < 0:
        observations.append(
            f"🟠 **Balance decreased:** "
            f"approximately KES {abs(balance_change):,.2f}."
        )

if pd.notna(largest_entity_share):

    if largest_entity_share > 50:
        observations.append(
            f"🟠 **Spending concentration:** "
            f"{largest_expense_entity} accounts for approximately "
            f"{largest_entity_share:.1f}% of extracted spending."
        )

if ledger["missing_amount"].sum() > 0:

    observations.append(
        f"🟡 **Data completeness:** "
        f"{int(ledger['missing_amount'].sum())} transaction(s) "
        "have no extracted amount."
    )

if ledger["invalid_json"].sum() > 0:

    observations.append(
        f"🟡 **Extraction quality:** "
        f"{int(ledger['invalid_json'].sum())} row(s) "
        "were not successfully parsed as JSON."
    )

for item in observations:
    display(Markdown(f"- {item}"))


# ============================================================
# 22. CHART 1 — INCOME VS EXPENSE
# ============================================================

if not monthly.empty:

    monthly_long = monthly.melt(
        id_vars=["month"],
        value_vars=[
            "income_kes",
            "expense_kes"
        ],
        var_name="flow",
        value_name="KES"
    )

    monthly_long["flow"] = monthly_long["flow"].map({
        "income_kes": "Income",
        "expense_kes": "Expenses"
    })

    fig = px.bar(
        monthly_long,
        x="month",
        y="KES",
        color="flow",
        barmode="group",
        title="Monthly Income vs Expenses"
    )

    fig.update_layout(
        xaxis_title="Month",
        yaxis_title="KES",
        hovermode="x unified"
    )

    fig.show()


# ============================================================
# 23. CHART 2 — NET CASH FLOW
# ============================================================

if not monthly.empty:

    fig = px.bar(
        monthly,
        x="month",
        y="net_cashflow_kes",
        title="Monthly Net Cash Flow",
        labels={
            "net_cashflow_kes": "Net Cash Flow (KES)",
            "month": "Month"
        }
    )

    fig.add_hline(
        y=0,
        line_dash="dash"
    )

    fig.show()


# ============================================================
# 24. CHART 3 — BALANCE TREND
# ============================================================

balances = (
    ledger[
        ledger["balance"].notna()
    ]
    .sort_values(
        ["date_parsed", "transaction_number"],
        na_position="last"
    )
)

if not balances.empty:

    fig = px.line(
        balances,
        x="date_parsed",
        y="balance",
        markers=True,
        title="Extracted Account Balance Over Time",
        labels={
            "date_parsed": "Date",
            "balance": "Balance (KES)"
        }
    )

    fig.show()


# ============================================================
# 25. CHART 4 — INCOME / EXPENSE TRANSACTION COUNTS
# ============================================================

direction_counts = (
    ledger["direction"]
    .value_counts()
    .rename_axis("Direction")
    .reset_index(name="Transactions")
)

fig = px.bar(
    direction_counts,
    x="Direction",
    y="Transactions",
    title="Transaction Frequency by Direction"
)

fig.show()


# ============================================================
# 26. CHART 5 — EXPENSES BY DOMAIN
# ============================================================

spending_domain = (
    expense_rows
    .groupby("domain")["amount"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

if not spending_domain.empty:

    fig = px.pie(
        spending_domain,
        names="domain",
        values="amount",
        hole=0.45,
        title="Where Is the Money Being Spent?"
    )

    fig.show()


# ============================================================
# 27. CHART 6 — TOP EXPENSE ENTITIES
# ============================================================

top_entities = (
    expense_rows
    .groupby("entity")["amount"]
    .sum()
    .nlargest(10)
    .sort_values()
    .reset_index()
)

if not top_entities.empty:

    fig = px.bar(
        top_entities,
        x="amount",
        y="entity",
        orientation="h",
        title="Top 10 Expense Entities",
        labels={
            "amount": "Total Spending (KES)",
            "entity": "Entity"
        }
    )

    fig.show()


# ============================================================
# 28. CHART 7 — TRANSACTION SIZE DISTRIBUTION
# ============================================================

amount_data = ledger[
    ledger["amount"].notna()
].copy()

if not amount_data.empty:

    fig = px.histogram(
        amount_data,
        x="amount",
        color="direction",
        nbins=20,
        title="Transaction Amount Distribution",
        labels={
            "amount": "Transaction Amount (KES)"
        }
    )

    fig.show()


# ============================================================
# 29. CHART 8 — DAILY CASH FLOW
# ============================================================

daily = (
    ledger[
        ledger["date_parsed"].notna()
    ]
    .groupby("day")
    .agg(
        income_kes=("income_kes", "sum"),
        expense_kes=("expense_kes", "sum"),
        net_cashflow_kes=("net_cashflow_kes", "sum")
    )
    .reset_index()
)

if not daily.empty:

    daily_long = daily.melt(
        id_vars="day",
        value_vars=[
            "income_kes",
            "expense_kes"
        ],
        var_name="flow",
        value_name="KES"
    )

    daily_long["flow"] = daily_long["flow"].map({
        "income_kes": "Income",
        "expense_kes": "Expenses"
    })

    fig = px.bar(
        daily_long,
        x="day",
        y="KES",
        color="flow",
        barmode="group",
        title="Daily Income and Expenses"
    )

    fig.show()


# ============================================================
# 30. CHART 9 — FEES
# ============================================================

fees_by_domain = (
    ledger
    .groupby("domain")["fee_kes"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

fees_by_domain = fees_by_domain[
    fees_by_domain["fee_kes"] > 0
]

if not fees_by_domain.empty:

    fig = px.bar(
        fees_by_domain,
        x="domain",
        y="fee_kes",
        title="Transaction Fees by Financial Domain",
        labels={
            "fee_kes": "Fees (KES)",
            "domain": "Domain"
        }
    )

    fig.show()


# ============================================================
# 31. CHART 10 — CASH FLOW MARGIN
# ============================================================

if not monthly.empty:

    fig = px.line(
        monthly,
        x="month",
        y="cashflow_margin_pct",
        markers=True,
        title="Monthly Cash-Flow Margin",
        labels={
            "cashflow_margin_pct": "Cash-Flow Margin (%)",
            "month": "Month"
        }
    )

    fig.add_hline(
        y=0,
        line_dash="dash"
    )

    fig.show()


# ============================================================
# 32. TOP INCOME SOURCES
# ============================================================

top_income_entities = (
    income_rows
    .groupby("entity")["amount"]
    .sum()
    .nlargest(10)
    .sort_values()
    .reset_index()
)

if not top_income_entities.empty:

    fig = px.bar(
        top_income_entities,
        x="amount",
        y="entity",
        orientation="h",
        title="Top 10 Income Sources",
        labels={
            "amount": "Income (KES)",
            "entity": "Entity"
        }
    )

    fig.show()


# ============================================================
# 33. ENTITY-LEVEL ANALYSIS
# ============================================================

entity_analysis = (
    ledger
    .groupby(
        ["entity", "direction"],
        dropna=False
    )
    .agg(
        total_amount=("amount", "sum"),
        transaction_count=("amount", "count"),
        average_amount=("amount", "mean"),
        total_fees=("fee_kes", "sum")
    )
    .reset_index()
)

entity_analysis.to_csv(
    OUTPUT_ENTITY,
    index=False
)


# ============================================================
# 34. DOMAIN-LEVEL ANALYSIS
# ============================================================

domain_analysis = (
    ledger
    .groupby(
        ["domain", "direction"],
        dropna=False
    )
    .agg(
        total_amount=("amount", "sum"),
        transaction_count=("amount", "count"),
        average_amount=("amount", "mean"),
        total_fees=("fee_kes", "sum")
    )
    .reset_index()
)

domain_analysis.to_csv(
    OUTPUT_DOMAIN,
    index=False
)


# ============================================================
# 35. FINANCIAL HEALTH DATASET
# ============================================================

health_record = {

    "total_transactions":
        total_transactions,

    "income_transactions":
        income_count,

    "expense_transactions":
        expense_count,

    "total_income_kes":
        total_income,

    "total_expenses_kes":
        total_expenses,

    "net_cashflow_kes":
        net_cashflow,

    "cashflow_margin_pct":
        cashflow_margin,

    "expense_to_income_pct":
        expense_to_income_pct,

    "income_expense_ratio":
        income_expense_ratio,

    "average_transaction_kes":
        average_transaction,

    "median_transaction_kes":
        median_transaction,

    "largest_income_kes":
        largest_income,

    "largest_expense_kes":
        largest_expense,

    "first_balance_kes":
        first_balance,

    "latest_balance_kes":
        latest_balance,

    "lowest_balance_kes":
        lowest_balance,

    "highest_balance_kes":
        highest_balance,

    "balance_change_kes":
        balance_change,

    "balance_volatility_pct":
        balance_volatility_pct,

    "total_fees_kes":
        ledger["fee_kes"].sum(),

    "fee_to_income_pct":
        fee_to_transaction_pct,

    "largest_expense_entity":
        largest_expense_entity,

    "largest_entity_spend_kes":
        largest_entity_spend,

    "largest_entity_share_pct":
        largest_entity_share,

    "missing_amount_count":
        int(ledger["missing_amount"].sum()),

    "missing_date_count":
        int(ledger["missing_date"].sum()),

    "unknown_direction_count":
        int(ledger["unknown_direction"].sum()),

    "possible_duplicate_count":
        int(ledger["possible_duplicate"].sum()),

    "invalid_json_count":
        int(ledger["invalid_json"].sum())

}

financial_health = pd.DataFrame(
    [health_record]
)

financial_health.to_csv(
    OUTPUT_HEALTH,
    index=False
)


# ============================================================
# 36. SAVE MONTHLY ANALYSIS
# ============================================================

monthly.to_csv(
    OUTPUT_MONTHLY,
    index=False
)


# ============================================================
# 37. SAVE FINAL ANALYSIS-READY LEDGER
# ============================================================

ledger.to_csv(
    OUTPUT_LEDGER,
    index=False
)


# ============================================================
# 38. TRANSACTION TABLE
# ============================================================

display(
    Markdown(
        "## 📋 Analysis-Ready Transaction Ledger"
    )
)

display(
    ledger[
        [
            "transaction_number",
            "sms",
            "date",
            "time",
            "type",
            "domain",
            "entity",
            "amount",
            "balance",
            "fee",
            "reference",
            "json_valid"
        ]
    ].head(100)
)


# ============================================================
# 39. DATA QUALITY REPORT
# ============================================================

display(
    Markdown(
        "## 🧪 Extraction & Data Quality"
    )
)

quality = pd.DataFrame({

    "Check": [

        "Total rows",
        "Valid JSON",
        "Invalid JSON",
        "Missing amount",
        "Missing balance",
        "Missing date",
        "Unknown direction",
        "Possible duplicate reference"

    ],

    "Rows": [

        len(ledger),

        int(ledger["json_valid"].sum()),

        int(ledger["invalid_json"].sum()),

        int(ledger["missing_amount"].sum()),

        int(ledger["missing_balance"].sum()),

        int(ledger["missing_date"].sum()),

        int(ledger["unknown_direction"].sum()),

        int(ledger["possible_duplicate"].sum())

    ]

})

display(quality)

# ============================================================
# 40. OUTPUT FILES
# ============================================================

print("\n")
print("=" * 90)
print("ANALYSIS COMPLETE")
print("=" * 90)

print(f"\nFinal transaction ledger:")
print(OUTPUT_LEDGER)

print("\nMonthly analysis:")
print(OUTPUT_MONTHLY)

print("\nEntity analysis:")
print(OUTPUT_ENTITY)

print("\nDomain analysis:")
print(OUTPUT_DOMAIN)

print("\nFinancial health summary:")
print(OUTPUT_HEALTH)

print("\nFinal ledger shape:", ledger.shape)

==========================================================================================
SME-LEDGER V2 — FINANCIAL HEALTH ANALYTICS
==========================================================================================

Loaded: /kaggle/working/sme_ledger_50_results.csv
Rows: 50
Columns: 9

/tmp/ipykernel_16/2073597281.py:113: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({

# 💰 SME-Ledger V2 — Financial Health Dashboard

### Dataset overview

**Transactions:** 50

**Income:** KES 88,000.00

**Expenses:** KES 45,600.00

**Net cash flow:** KES 42,400.00

**Latest extracted balance:**
KES 172,920.00

## 📊 Core Financial KPIs

                      KPI           Value
0            Total income   KES 88,000.00
1          Total expenses   KES 45,600.00
2           Net cash flow   KES 42,400.00
3     Average transaction    KES 4,948.15
4      Median transaction    KES 3,500.00
5  Income / expense ratio            1.93
6        Cash-flow margin          48.18%
7          Latest balance  KES 172,920.00

## 🔎 Financial Health Indicators

- 🟢 **Positive net cash flow:** total extracted income exceeds total extracted expenses.

- 🟢 **Expense-to-income ratio:** approximately 51.8%.

- 🟢 **Balance increased:** approximately KES 156,920.00 between the first and latest extracted balances.

- 🟡 **Data completeness:** 23 transaction(s) have no extracted amount.

- 🟡 **Extraction quality:** 50 row(s) were not successfully parsed as JSON.

## 📋 Analysis-Ready Transaction Ledger

,transaction_number,sms,date,time,type,domain,entity,amount,balance,fee,reference,json_valid
0,1,"TX03010001 Confirmed. You have received Ksh7,5...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
1,2,"TX03010002 Confirmed. You have received Ksh2,5...",2026-03-01,12:27,income,bank_transfer_receive_money,Peter Mwangi,2500.0,16000.0,NaN,None,False
2,3,TX03020003 Confirmed. Ksh500.00 paid to Green ...,2026-03-02,09:02,expense,send_money,Green Valley Shop,500.0,0.0,NaN,None,False
3,4,TX03020004 Confirmed. Ksh500.00 sent to David ...,NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
4,5,"TX03030005 Confirmed. Ksh1,500.00 paid to Wang...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
5,6,"TX03030006 Confirmed. Ksh1,000.00 paid to Airt...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
6,7,"TX03040007 Confirmed. You have received Ksh2,5...",2026-03-04,08:18,income,bank_transfer_receive_money,Grace Njeri,2500.0,158980.0,NaN,None,False
7,8,TX03040008 Confirmed. Ksh500.00 sent to Peter ...,NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
8,9,"TX03050009 Confirmed. You have received Ksh7,5...",2026-03-05,08:49,income,bank_transfer_received,Grace Njeri,7500.0,165930.0,NaN,None,False
9,10,"TX03050010 Confirmed. You have received Ksh2,5...",2026-03-05,12:02,income,bank_transfer_receive_money,Ann Mueni,2500.0,168430.0,NaN,None,False
10,11,TX03060011 Confirmed. Ksh800.00 withdrawn from...,NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
11,12,"TX03060012 Confirmed. Ksh2,000.00 paid to Airt...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
12,13,"TX03070013 Confirmed. You have received Ksh7,5...",2026-03-07,08:36,income,bank_transfer_receive_money,Peter Mwangi,7500.0,173080.0,NaN,None,False
13,14,"TX03070014 Confirmed. Ksh3,500.00 sent to Mary...",2026-03-07,02:02,expense,send_money,Mary Wanjiku,3500.0,169570.0,NaN,None,False
14,15,"TX03080015 Confirmed. Ksh7,500.00 paid to Airt...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
15,16,"TX03080016 Confirmed. You have received Ksh1,5...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
16,17,"TX03090017 Confirmed. Ksh1,250.00 paid to Gree...",2026-03-09,08:49,expense,send_money,Green Valley Shop,1250.0,0.0,NaN,None,False
17,18,"TX03090018 Confirmed. Ksh7,500.00 paid to Wang...",2026-03-09,01:49,expense,send_money,Wanga Electronics,7500.0,0.0,NaN,None,False
18,19,"TX03100019 Confirmed. You have received Ksh7,5...",2026-03-10,08:36,income,bank_transfer_receive_money,David Kiptoo,7500.0,162235.0,NaN,None,False
19,20,"TX03100020 Confirmed. Ksh1,250.00 paid to Safa...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
20,21,TX03110021 Confirmed. Ksh800.00 paid to Water ...,2026-03-11,08:18,expense,paybill,Water Services,800.0,NaN,NaN,None,False
21,22,"TX03110022 Confirmed. You have received Ksh15,...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
22,23,"TX03120023 Confirmed. Ksh3,500.00 paid to Quic...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
23,24,"TX03120024 Confirmed. Ksh7,500.00 paid to KPLC...",2026-03-12,02:02,expense,bill_payment,KPLC,7500.0,NaN,NaN,None,False
24,25,"TX03130025 Confirmed. You have received Ksh1,5...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
25,26,"TX03130026 Confirmed. Ksh3,500.00 paid to Zuku...",2026-03-13,02:02,expense,bill_payment,Zuku,3500.0,0.0,NaN,None,False
26,27,"TX03140027 Confirmed. Ksh1,000.00 sent to Mary...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
27,28,"TX03140028 Confirmed. Fuliza loan of Ksh3,000....",2026-03-14,11:02,income,bank_transfer,Fuliza Bank,3000.0,164135.0,NaN,None,False
28,29,TX03150029 Confirmed. Ksh500.00 paid to Airtel...,NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
29,30,"TX03150030 Confirmed. You have received Ksh5,0...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
30,31,TX03160031 Confirmed. Ksh800.00 paid to Water ...,2026-03-16,08:18,expense,paybill: 88888:98550256,Water Services,0.0,NaN,NaN,None,False
31,32,"TX03160032 Confirmed. Fuliza loan of Ksh5,000....",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
32,33,"TX03170033 Confirmed. Ksh5,000.00 sent to John...",2026-03-17,08:36,expense,send_money,John Kamau,5000.0,167805.0,NaN,None,False
33,34,"TX03170034 Confirmed. Ksh1,250.00 paid to Safa...",2026-03-17,02:02,expense,bill_payment,Safaricom,1250.0,NaN,NaN,None,False
34,35,"TX03180035 Confirmed. Ksh3,500.00 paid to Quic...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
35,36,"TX03180036 Confirmed. You have received Ksh10,...",2026-03-18,13:27,income,bank_transfer_receive_money,Ann Mueni,10000.0,0.0,NaN,None,False
36,37,"TX03190037 Confirmed. Ksh5,000.00 sent to Ann ...",2026-03-19,09:02,expense,send_money,Ann Mueni,5000.0,167980.0,NaN,None,False
37,38,TX03190038 Confirmed. Ksh500.00 paid to KPLC v...,2026-03-19,01:18,expense,bill_payment,KPLC,500.0,NaN,NaN,None,False
38,39,"TX03200039 Confirmed. You have received Ksh5,0...",2026-03-20,08:36,income,bank_transfer_receive,Brian Otieno,5000.0,172470.0,NaN,None,False
39,40,"TX03200040 Confirmed. You have received Ksh3,0...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
40,41,"TX03210041 Confirmed. Ksh2,500.00 withdrawn fr...",21/03/2026,08:27,expense,M-PESA,Agent 201639,2500.0,172920.0,NaN,None,False
41,42,"TX03210042 Confirmed. Ksh2,500.00 paid to Naiv...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
42,43,"TX03220043 Confirmed. You have received Ksh10,...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
43,44,"TX03220044 Confirmed. You have received Ksh20,...",2026-03-22,13:27,income,bank_transfer_received,Mary Wanjiku,20000.0,200370.0,NaN,None,False
44,45,"TX03230045 Confirmed. You have received Ksh20,...",2026-03-23,08:49,income,bank_transfer_receive,John Kamau,20000.0,220370.0,NaN,None,False
45,46,"TX03230046 Confirmed. Ksh3,500.00 paid to Naiv...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
46,47,TX03240047 Confirmed. Ksh800.00 withdrawn from...,2026-03-24,09:02,expense,cash_withdrawal,Agent 526156,800.0,216.0,NaN,None,False
47,48,"TX03240048 Confirmed. Ksh2,500.00 paid to Wang...",2026-03-24,13:49,expense,send_money,Wanga Electronics,2500.0,213520.0,NaN,None,False
48,49,"TX03250049 Confirmed. You have received Ksh15,...",NaN,NaN,unknown,Unknown,Unknown,NaN,NaN,NaN,None,False
49,50,"TX03250050 Confirmed. Ksh3,500.00 paid to Wang...",2026-03-25,01:49,expense,send_money,Wanga Electronics,3500.0,224970.0,NaN,None,False

## 🧪 Extraction & Data Quality

                          Check  Rows
0                    Total rows    50
1                    Valid JSON     0
2                  Invalid JSON    50
3                Missing amount    23
4               Missing balance    28
5                  Missing date    24
6             Unknown direction    23
7  Possible duplicate reference     0

==========================================================================================
ANALYSIS COMPLETE
==========================================================================================

Final transaction ledger:
/kaggle/working/sme_ledger_final_analysis.csv

Monthly analysis:
/kaggle/working/sme_ledger_monthly_analysis.csv

Entity analysis:
/kaggle/working/sme_ledger_entity_analysis.csv

Domain analysis:
/kaggle/working/sme_ledger_domain_analysis.csv

Financial health summary:
/kaggle/working/sme_ledger_financial_health.csv

Final ledger shape: (50, 29)