In [1]:
!pip install -U llama-cpp-python

Collecting llama-cpp-python
  Downloading llama_cpp_python-0.3.35.tar.gz (74.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.9/74.9 MB 22.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (4.15.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (2.0.2)
Collecting diskcache>=5.6.1 (from llama-cpp-python)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: jinja2>=2.11.3 in /usr/local/lib/python3.12/dist-packages (from llama-cpp-python) (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.11.3->llama-cpp-python) (3.0.3)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.2 MB/s eta 0:00:00
Building wheels for collected packages: llama-cpp-python
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.3.35-py3-none-linux_x86_64.whl size=20848225 sha256=361cf083cebc8dd720171327059874a8bec20c2d487e34cf3b98b935ecdcd6e6
  Stored in directory: /root/.cache/pip/wheels/1b/64/d4/17744d793e69b485a7664ef47b18e402a72a6e08e84f7b9926
Successfully built llama-cpp-python
Installing collected packages: diskcache, llama-cpp-python
Successfully installed diskcache-5.6.3 llama-cpp-python-0.3.35

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/wangapa106g/massage-analysis/test_50_consistent.csv

In [3]:

from llama_cpp import Llama

llm = Llama.from_pretrained(
	repo_id="EngineerWanga0791709020/SME-Ledger",
	filename="sme-ledger-v2-Q4_K_M.gguf",
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `hf_hub_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

./sme-ledger-v2-Q4_K_M.gguf:   0%|          | 0.00/261M [00:00<?, ?B/s]

llama_model_loader: loaded meta data with 33 key-value pairs and 236 tensors from /root/.cache/huggingface/hub/models--EngineerWanga0791709020--SME-Ledger/snapshots/1aa4d6566c59f07727d7a814269122c8f037dd09/./sme-ledger-v2-Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = gemma3
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                     general.sampling.top_k i32              = 64
llama_model_loader: - kv   3:                     general.sampling.top_p f32              = 0.950000
llama_model_loader: - kv   4:                               general.name str              = Merged
llama_model_loader: - kv   5:                         general.size_label str              = 268M
llama_model_loader: - kv   6:                         gemma3.block_count u32              = 18
llama_model_loader: - kv   7:                      gemma3.context_length u32              = 32768
llama_model_loader: - kv   8:                    gemma3.embedding_length u32              = 640
llama_model_loader: - kv   9:                 gemma3.feed_forward_length u32              = 2048
llama_model_loader: - kv  10:                gemma3.attention.head_count u32              = 4
llama_model_loader: - kv  11:             gemma3.attention.head_count_kv u32              = 1
llama_model_loader: - kv  12:                      gemma3.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:                  gemma3.rope.freq_base_swa f32              = 10000.000000
llama_model_loader: - kv  14:    gemma3.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  15:                gemma3.attention.key_length u32              = 256
llama_model_loader: - kv  16:              gemma3.attention.value_length u32              = 256
llama_model_loader: - kv  17:            gemma3.attention.sliding_window u32              = 512
llama_model_loader: - kv  18:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  19:                         tokenizer.ggml.pre str              = granite-embed-multi-311m
llama_model_loader: - kv  20:                      tokenizer.ggml.tokens arr[str,262144]  = ["<pad>", "<eos>", "<bos>", "<unk>", ...
llama_model_loader: - kv  21:                  tokenizer.ggml.token_type arr[i32,262144]  = [3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  22:                      tokenizer.ggml.merges arr[str,514906]  = ["\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n", ...
llama_model_loader: - kv  23:                tokenizer.ggml.bos_token_id u32              = 2
llama_model_loader: - kv  24:                tokenizer.ggml.eos_token_id u32              = 1
llama_model_loader: - kv  25:            tokenizer.ggml.unknown_token_id u32              = 3
llama_model_loader: - kv  26:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  27:               tokenizer.ggml.mask_token_id u32              = 4
llama_model_loader: - kv  28:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  29:               tokenizer.ggml.add_sep_token bool             = false
llama_model_loader: - kv  30:                    tokenizer.chat_template str              = {{ bos_token }}\n{%- if messages[0]['r...
llama_model_loader: - kv  31:               general.quantization_version u32              = 2
llama_model_loader: - kv  32:                          general.file_type u32              = 15
llama_model_loader: - type  f32:  109 tensors
llama_model_loader: - type q5_0:   81 tensors
llama_model_loader: - type q8_0:   10 tensors
llama_model_loader: - type q4_K:   27 tensors
llama_model_loader: - type q6_K:    9 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 235.16 MiB (7.36 BPW)
init_tokenizer: initializing tokenizer for type 2
load: 6242 unused tokens
load: control token: 256000 '<end_of_image>' is not marked as EOG
load: control token: 255999 '<start_of_image>' is not marked as EOG
load: control token:    105 '<start_of_turn>' is not marked as EOG
load: control token:      2 '<bos>' is not marked as EOG
load: control-looking token:    212 '</s>' was not control-type; this is probably a bug in the model. its type will be overridden
load: control token:      0 '<pad>' is not marked as EOG
load: control token:      3 '<unk>' is not marked as EOG
load: control token:      4 '<mask>' is not marked as EOG
load: printing all EOG tokens:
load:   - 1 ('<eos>')
load:   - 106 ('<end_of_turn>')
load:   - 212 ('</s>')
load: special tokens cache size = 6414
load: token to piece cache size = 1.9458 MB
print_info: arch                  = gemma3
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 32768
print_info: n_embd_inp            = 640
print_info: n_embd                = 640
print_info: n_embd_out            = 640
print_info: n_layer               = 18
print_info: n_layer_all           = 18
print_info: n_head                = 4
print_info: n_head_kv             = 1
print_info: n_rot                 = 256
print_info: n_swa                 = 512
print_info: is_swa_any            = 1
print_info: n_embd_head_k         = 256
print_info: n_embd_head_v         = 256
print_info: n_gqa                 = 4
print_info: n_embd_k_gqa          = 256
print_info: n_embd_v_gqa          = 256
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-06
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 6.2e-02
print_info: f_attn_value_scale    = 0.0000
print_info: n_ff                  = 2048
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 2
print_info: rope scaling          = linear
print_info: freq_base_train       = 1000000.0
print_info: freq_scale_train      = 1
print_info: freq_base_swa         = 10000.0
print_info: freq_scale_swa        = 1
print_info: n_embd_head_k_swa     = 256
print_info: n_embd_head_v_swa     = 256
print_info: n_rot_swa             = 256
print_info: n_ctx_orig_yarn       = 32768
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = 270M
print_info: model params          = 268.10 M
print_info: general.name          = Merged
print_info: vocab type            = BPE
print_info: n_vocab               = 262144
print_info: n_merges              = 514906
print_info: BOS token             = 2 '<bos>'
print_info: EOS token             = 1 '<eos>'
print_info: EOT token             = 106 '<end_of_turn>'
print_info: UNK token             = 3 '<unk>'
print_info: PAD token             = 0 '<pad>'
print_info: MASK token            = 4 '<mask>'
print_info: LF token              = 107 '
'
print_info: EOG token             = 1 '<eos>'
print_info: EOG token             = 106 '<end_of_turn>'
print_info: EOG token             = 212 '</s>'
print_info: max token length      = 48
load_tensors: loading model tensors, this can take a while... (load_mode = mmap)
load_tensors: layer   0 assigned to device CPU, is_swa = 1
load_tensors: layer   1 assigned to device CPU, is_swa = 1
load_tensors: layer   2 assigned to device CPU, is_swa = 1
load_tensors: layer   3 assigned to device CPU, is_swa = 1
load_tensors: layer   4 assigned to device CPU, is_swa = 1
load_tensors: layer   5 assigned to device CPU, is_swa = 0
load_tensors: layer   6 assigned to device CPU, is_swa = 1
load_tensors: layer   7 assigned to device CPU, is_swa = 1
load_tensors: layer   8 assigned to device CPU, is_swa = 1
load_tensors: layer   9 assigned to device CPU, is_swa = 1
load_tensors: layer  10 assigned to device CPU, is_swa = 1
load_tensors: layer  11 assigned to device CPU, is_swa = 0
load_tensors: layer  12 assigned to device CPU, is_swa = 1
load_tensors: layer  13 assigned to device CPU, is_swa = 1
load_tensors: layer  14 assigned to device CPU, is_swa = 1
load_tensors: layer  15 assigned to device CPU, is_swa = 1
load_tensors: layer  16 assigned to device CPU, is_swa = 1
load_tensors: layer  17 assigned to device CPU, is_swa = 0
load_tensors: layer  18 assigned to device CPU, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor output.weight
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor dense_2.weight
create_tensor: loading tensor dense_3.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_qkv.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_q.bias
create_tensor: loading tensor blk.0.attn_k.bias
create_tensor: loading tensor blk.0.attn_v.bias
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.post_attention_norm.weight
create_tensor: loading tensor blk.0.attn_k_norm.weight
create_tensor: loading tensor blk.0.attn_q_norm.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.post_ffw_norm.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_qkv.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_q.bias
create_tensor: loading tensor blk.1.attn_k.bias
create_tensor: loading tensor blk.1.attn_v.bias
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.post_attention_norm.weight
create_tensor: loading tensor blk.1.attn_k_norm.weight
create_tensor: loading tensor blk.1.attn_q_norm.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.post_ffw_norm.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_qkv.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_q.bias
create_tensor: loading tensor blk.2.attn_k.bias
create_tensor: loading tensor blk.2.attn_v.bias
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.post_attention_norm.weight
create_tensor: loading tensor blk.2.attn_k_norm.weight
create_tensor: loading tensor blk.2.attn_q_norm.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.post_ffw_norm.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_qkv.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_q.bias
create_tensor: loading tensor blk.3.attn_k.bias
create_tensor: loading tensor blk.3.attn_v.bias
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.post_attention_norm.weight
create_tensor: loading tensor blk.3.attn_k_norm.weight
create_tensor: loading tensor blk.3.attn_q_norm.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.post_ffw_norm.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_qkv.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_q.bias
create_tensor: loading tensor blk.4.attn_k.bias
create_tensor: loading tensor blk.4.attn_v.bias
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.post_attention_norm.weight
create_tensor: loading tensor blk.4.attn_k_norm.weight
create_tensor: loading tensor blk.4.attn_q_norm.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.post_ffw_norm.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_qkv.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_q.bias
create_tensor: loading tensor blk.5.attn_k.bias
create_tensor: loading tensor blk.5.attn_v.bias
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.post_attention_norm.weight
create_tensor: loading tensor blk.5.attn_k_norm.weight
create_tensor: loading tensor blk.5.attn_q_norm.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.post_ffw_norm.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_qkv.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_q.bias
create_tensor: loading tensor blk.6.attn_k.bias
create_tensor: loading tensor blk.6.attn_v.bias
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.post_attention_norm.weight
create_tensor: loading tensor blk.6.attn_k_norm.weight
create_tensor: loading tensor blk.6.attn_q_norm.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.post_ffw_norm.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_qkv.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_q.bias
create_tensor: loading tensor blk.7.attn_k.bias
create_tensor: loading tensor blk.7.attn_v.bias
create_tensor: loading tensor blk.7.attn_output.weight
create_tensor: loading tensor blk.7.post_attention_norm.weight
create_tensor: loading tensor blk.7.attn_k_norm.weight
create_tensor: loading tensor blk.7.attn_q_norm.weight
create_tensor: loading tensor blk.7.ffn_norm.weight
create_tensor: loading tensor blk.7.ffn_gate.weight
create_tensor: loading tensor blk.7.ffn_up.weight
create_tensor: loading tensor blk.7.ffn_down.weight
create_tensor: loading tensor blk.7.post_ffw_norm.weight
create_tensor: loading tensor blk.8.attn_norm.weight
create_tensor: loading tensor blk.8.attn_qkv.weight
create_tensor: loading tensor blk.8.attn_q.weight
create_tensor: loading tensor blk.8.attn_k.weight
create_tensor: loading tensor blk.8.attn_v.weight
create_tensor: loading tensor blk.8.attn_q.bias
create_tensor: loading tensor blk.8.attn_k.bias
create_tensor: loading tensor blk.8.attn_v.bias
create_tensor: loading tensor blk.8.attn_output.weight
create_tensor: loading tensor blk.8.post_attention_norm.weight
create_tensor: loading tensor blk.8.attn_k_norm.weight
create_tensor: loading tensor blk.8.attn_q_norm.weight
create_tensor: loading tensor blk.8.ffn_norm.weight
create_tensor: loading tensor blk.8.ffn_gate.weight
create_tensor: loading tensor blk.8.ffn_up.weight
create_tensor: loading tensor blk.8.ffn_down.weight
create_tensor: loading tensor blk.8.post_ffw_norm.weight
create_tensor: loading tensor blk.9.attn_norm.weight
create_tensor: loading tensor blk.9.attn_qkv.weight
create_tensor: loading tensor blk.9.attn_q.weight
create_tensor: loading tensor blk.9.attn_k.weight
create_tensor: loading tensor blk.9.attn_v.weight
create_tensor: loading tensor blk.9.attn_q.bias
create_tensor: loading tensor blk.9.attn_k.bias
create_tensor: loading tensor blk.9.attn_v.bias
create_tensor: loading tensor blk.9.attn_output.weight
create_tensor: loading tensor blk.9.post_attention_norm.weight
create_tensor: loading tensor blk.9.attn_k_norm.weight
create_tensor: loading tensor blk.9.attn_q_norm.weight
create_tensor: loading tensor blk.9.ffn_norm.weight
create_tensor: loading tensor blk.9.ffn_gate.weight
create_tensor: loading tensor blk.9.ffn_up.weight
create_tensor: loading tensor blk.9.ffn_down.weight
create_tensor: loading tensor blk.9.post_ffw_norm.weight
create_tensor: loading tensor blk.10.attn_norm.weight
create_tensor: loading tensor blk.10.attn_qkv.weight
create_tensor: loading tensor blk.10.attn_q.weight
create_tensor: loading tensor blk.10.attn_k.weight
create_tensor: loading tensor blk.10.attn_v.weight
create_tensor: loading tensor blk.10.attn_q.bias
create_tensor: loading tensor blk.10.attn_k.bias
create_tensor: loading tensor blk.10.attn_v.bias
create_tensor: loading tensor blk.10.attn_output.weight
create_tensor: loading tensor blk.10.post_attention_norm.weight
create_tensor: loading tensor blk.10.attn_k_norm.weight
create_tensor: loading tensor blk.10.attn_q_norm.weight
create_tensor: loading tensor blk.10.ffn_norm.weight
create_tensor: loading tensor blk.10.ffn_gate.weight
create_tensor: loading tensor blk.10.ffn_up.weight
create_tensor: loading tensor blk.10.ffn_down.weight
create_tensor: loading tensor blk.10.post_ffw_norm.weight
create_tensor: loading tensor blk.11.attn_norm.weight
create_tensor: loading tensor blk.11.attn_qkv.weight
create_tensor: loading tensor blk.11.attn_q.weight
create_tensor: loading tensor blk.11.attn_k.weight
create_tensor: loading tensor blk.11.attn_v.weight
create_tensor: loading tensor blk.11.attn_q.bias
create_tensor: loading tensor blk.11.attn_k.bias
create_tensor: loading tensor blk.11.attn_v.bias
create_tensor: loading tensor blk.11.attn_output.weight
create_tensor: loading tensor blk.11.post_attention_norm.weight
create_tensor: loading tensor blk.11.attn_k_norm.weight
create_tensor: loading tensor blk.11.attn_q_norm.weight
create_tensor: loading tensor blk.11.ffn_norm.weight
create_tensor: loading tensor blk.11.ffn_gate.weight
create_tensor: loading tensor blk.11.ffn_up.weight
create_tensor: loading tensor blk.11.ffn_down.weight
create_tensor: loading tensor blk.11.post_ffw_norm.weight
create_tensor: loading tensor blk.12.attn_norm.weight
create_tensor: loading tensor blk.12.attn_qkv.weight
create_tensor: loading tensor blk.12.attn_q.weight
create_tensor: loading tensor blk.12.attn_k.weight
create_tensor: loading tensor blk.12.attn_v.weight

In [4]:
# ============================================================
# SME-LEDGER V2 — MANUAL 20-SAMPLE EVALUATION
#
# You manually judge:
#   - JSON validity
#   - Correctness
#   - Missing information handling
#   - Capability answers
#
# This script ONLY shows:
#   1. Prompt given to model
#   2. Model response
#   3. Latency
#
# No automatic JSON scoring.
# ============================================================

import json
import time
from datetime import datetime


# ============================================================
# 20 TEST CASES
# ============================================================

TESTS = [

    # ========================================================
    # CATEGORY 1 — VALID TRANSACTIONS (8)
    # ========================================================

    {
        "id": "valid_01",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract the financial transaction below.

Return ONLY valid JSON with exactly these fields:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Rules:
- amount, balance and fee must be numbers.
- type must be income, expense, or unknown.
- date must be YYYY-MM-DD.
- Do not invent missing information.
- Use null when information is unavailable.
- No markdown.
- No explanation.

SMS:
QGH7K3M2P1 Confirmed. You have received Ksh20,000.00 from Ann Mueni 0712***456 on 05/03/2026 at 10:42 AM. New M-PESA balance is Ksh159,583.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_02",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this M-Pesa payment.

Return ONLY JSON with:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent missing information. Use null where necessary.

SMS:
TLA82K9P4Q Confirmed. Ksh1,250.00 paid to Naivas Supermarket on 06/03/2026 at 14:21. New M-PESA balance is Ksh158,333.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_03",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this M-Pesa Till transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
RTP93LMN72 Confirmed. Ksh3,500.00 paid to 123456 - Wanga Electronics via M-PESA Till Number on 07/03/2026 at 09:15 AM. New M-PESA balance is Ksh154,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_04",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this PayBill transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
PBY72LK91A Confirmed. Ksh5,000.00 sent to KPLC via PayBill 88888 for account 123456789 on 08/03/2026 at 18:03. New M-PESA balance is Ksh149,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_05",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this bank transfer received.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
BNK72PQ91 Confirmed. Ksh45,000.00 received in your M-PESA account from Equity Bank on 09/03/2026 at 11:30 AM. New M-PESA balance is Ksh194,833.00. Reference EQT98431.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_06",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this Fuliza transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
FUL123ABC Confirmed. Fuliza loan of Ksh10,000.00 received on 10/03/2026 at 08:05 AM. New M-PESA balance is Ksh204,833.00. Fuliza outstanding balance is Ksh10,000.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_07",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this cash withdrawal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
WD91KLM22 Confirmed. Ksh8,000.00 withdrawn from M-PESA at Agent 456789 - John Kamau on 11/03/2026 at 16:40. Transaction cost, Ksh80.00. New M-PESA balance is Ksh196,753.00.

Return ONLY JSON.
"""
    },

    {
        "id": "valid_08",
        "category": "valid_transaction",
        "task": "Extract transaction",
        "prompt": """
Extract this reversal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
REV8821 Confirmed. Reversal of Ksh2,500.00 for transaction QWE12345 has been credited to your M-PESA account on 12/03/2026 at 13:22. New M-PESA balance is Ksh199,253.00.

Return ONLY JSON.
"""
    },


    # ========================================================
    # CATEGORY 2 — MISSING / AMBIGUOUS DATA (6)
    # ========================================================

    {
        "id": "missing_01",
        "category": "missing_data",
        "task": "Handle missing balance",
        "prompt": """
Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for information that is not present.
Do not guess.

SMS:
ABC12345 Confirmed. You have received Ksh7,500.00 from Mary Wanjiku on 13/03/2026 at 09:10 AM.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_02",
        "category": "missing_data",
        "task": "Handle missing transaction ID",
        "prompt": """
Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for missing information.

SMS:
You paid Ksh2,000.00 to Green Valley Shop on 14/03/2026 at 15:20. New M-PESA balance is Ksh197,253.00.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_03",
        "category": "missing_data",
        "task": "Handle missing entity",
        "prompt": """
Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent an entity.

SMS:
TX99821 Confirmed. Ksh3,200.00 paid via M-PESA on 15/03/2026 at 12:00 PM. New M-PESA balance is Ksh194,053.00.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_04",
        "category": "missing_data",
        "task": "Ambiguous transaction",
        "prompt": """
Determine what can safely be extracted from this message.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null when information is ambiguous or missing.
Do not invent facts.

SMS:
TX7712 Confirmed. Ksh5,000 sent. Balance Ksh100,000.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_05",
        "category": "missing_data",
        "task": "Noisy SMS",
        "prompt": """
Extract the transaction from this noisy SMS.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Ignore irrelevant text.
Do not invent missing information.

SMS:
M-PESA ALERT!!! Your account was updated. TX88K21 Confirmed. You received Ksh12,000 from Peter on 16/03/2026. Please do not share your PIN. New balance Ksh112,000.

Return ONLY JSON.
"""
    },

    {
        "id": "missing_06",
        "category": "missing_data",
        "task": "Conflicting information",
        "prompt": """
Extract this transaction carefully.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

If the message contains conflicting information, preserve only what can be determined safely and use null where necessary.

SMS:
TX5566 Confirmed. Ksh4,000 paid to ABC Shop on 17/03/2026. New M-PESA balance is Ksh90,000. Later message says transaction amount was Ksh5,000.

Return ONLY JSON.
"""
    },


    # ========================================================
    # CATEGORY 3 — CAPABILITY / SELF-KNOWLEDGE (6)
    # ========================================================

    {
        "id": "capability_01",
        "category": "capability",
        "task": "Capabilities",
        "prompt": """
What types of financial transaction messages are you designed to understand?

Mention the transaction categories you can identify.

Answer concisely.
"""
    },

    {
        "id": "capability_02",
        "category": "capability",
        "task": "Supported fields",
        "prompt": """
What information can you extract from an M-Pesa or bank transaction message?

List the fields you are designed to identify.
"""
    },

    {
        "id": "capability_03",
        "category": "capability",
        "task": "Missing information",
        "prompt": """
What do you do when a financial SMS is missing important information such as the transaction ID, entity, balance, date, or amount?
"""
    },

    {
        "id": "capability_04",
        "category": "capability",
        "task": "Unsupported claims",
        "prompt": """
Can you access a user's bank account, M-Pesa account, contacts, internet, or private financial records directly?

Explain what you can and cannot access.
"""
    },

    {
        "id": "capability_05",
        "category": "capability",
        "task": "Role",
        "prompt": """
What is your role in the SME Ledger system?

Explain what happens after you extract a transaction from an SMS.
"""
    },

    {
        "id": "capability_06",
        "category": "capability",
        "task": "Transaction types",
        "prompt": """
Can you distinguish between income, expenses, transfers, withdrawals, merchant payments, PayBill payments, Fuliza transactions, reversals, and failed transactions?

If yes, briefly explain how.
"""
    }
]


# ============================================================
# RUN MODEL
# ============================================================

def run_model(prompt, max_tokens=256):

    start = time.time()

    try:

        response = llm.create_chat_completion(
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0,
            top_p=1,
            seed=42,
            max_tokens=max_tokens
        )

        elapsed = time.time() - start

        text = response["choices"][0]["message"]["content"]

        return text.strip(), round(elapsed, 3), None

    except Exception as e:

        elapsed = time.time() - start

        return "", round(elapsed, 3), str(e)


# ============================================================
# RUN 20 TESTS
# ============================================================

results = []

print("\n")
print("=" * 90)
print("                 SME-LEDGER V2 — MANUAL 20-TEST EVALUATION")
print("=" * 90)


for i, test in enumerate(TESTS, start=1):

    print("\n\n")
    print("█" * 90)
    print(f"TEST {i}/20")
    print(f"ID       : {test['id']}")
    print(f"CATEGORY : {test['category']}")
    print(f"TASK     : {test['task']}")
    print("█" * 90)

    # --------------------------------------------------------
    # PROMPT
    # --------------------------------------------------------

    print("\n")
    print("┌" + "─" * 88 + "┐")
    print("│ PROMPT GIVEN TO MODEL")
    print("└" + "─" * 88 + "┘")

    print(test["prompt"])

    # --------------------------------------------------------
    # MODEL
    # --------------------------------------------------------

    response, latency, error = run_model(test["prompt"])

    print("\n")
    print("┌" + "─" * 88 + "┐")
    print("│ MODEL RESPONSE")
    print("└" + "─" * 88 + "┘")

    if error:
        print("❌ ERROR:")
        print(error)
    else:
        print(response)

    print("\n")
    print(f"⏱️  Latency: {latency:.3f} seconds")

    # --------------------------------------------------------
    # Store raw result
    # --------------------------------------------------------

    results.append({
        "test_number": i,
        "id": test["id"],
        "category": test["category"],
        "task": test["task"],
        "prompt": test["prompt"],
        "response": response,
        "latency_seconds": latency,
        "error": error
    })


# ============================================================
# SAVE RAW RESULTS
# ============================================================

OUTPUT_FILE = "sme_ledger_20_manual_test_results.json"

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:

    json.dump(
        {
            "evaluation": {
                "name": "SME-Ledger V2 Manual 20-Test Evaluation",
                "model": "sme-ledger-v2-Q4_K_M.gguf",
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "seed": 42
            },
            "results": results
        },
        f,
        indent=2,
        ensure_ascii=False
    )


# ============================================================
# FINAL RUN SUMMARY
# ============================================================

successful = sum(
    r["error"] is None
    for r in results
)

average_latency = sum(
    r["latency_seconds"]
    for r in results
) / len(results)


print("\n\n")
print("=" * 90)
print("                         TEST RUN COMPLETE")
print("=" * 90)

print(f"""
Tests executed:       {len(results)}/20
Successful runs:      {successful}/20
Average latency:      {average_latency:.3f} seconds

No automatic correctness or JSON validation was performed.
You are the evaluator.
""")

print(f"Raw results saved to: {OUTPUT_FILE}")
print("=" * 90)

==========================================================================================
                 SME-LEDGER V2 — MANUAL 20-TEST EVALUATION
==========================================================================================



██████████████████████████████████████████████████████████████████████████████████████████
TEST 1/20
ID       : valid_01
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the financial transaction below.

Return ONLY valid JSON with exactly these fields:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Rules:
- amount, balance and fee must be numbers.
- type must be income, expense, or unknown.
- date must be YYYY-MM-DD.
- Do not invent missing information.
- Use null when information is unavailable.
- No markdown.
- No explanation.

SMS:
QGH7K3M2P1 Confirmed. You have received Ksh20,000.00 from Ann Mueni 0712***456 on 05/03/2026 at 10:42 AM. New M-PESA balance is Ksh159,583.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     792.68 ms /   209 tokens (    3.79 ms per token,   263.66 tokens per second)
llama_perf_context_print:        eval time =    2383.37 ms /    93 runs   (   25.63 ms per token,    39.02 tokens per second)
llama_perf_context_print:       total time =    3308.15 ms /   302 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 5 prefix-match hit, remaining 136 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: QGH7K3M2P1
date: 2026-03-05
time: 10:42
type: Income
domain: bank_transfer_receive_money
entity: Ann Mueni
amount: 20000.0
balance: 0.0
fee: 0.0
reference: QGH7K3M2P1


⏱️  Latency: 3.315 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 2/20
ID       : valid_02
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this M-Pesa payment.

Return ONLY JSON with:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent missing information. Use null where necessary.

SMS:
TLA82K9P4Q Confirmed. Ksh1,250.00 paid to Naivas Supermarket on 06/03/2026 at 14:21. New M-PESA balance is Ksh158,333.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     507.76 ms /   136 tokens (    3.73 ms per token,   267.84 tokens per second)
llama_perf_context_print:        eval time =    2460.79 ms /    95 runs   (   25.90 ms per token,    38.61 tokens per second)
llama_perf_context_print:       total time =    3107.27 ms /   231 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 10 prefix-match hit, remaining 133 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: TLA82K9P4Q
date: 2026-03-06
time: 14:21
type: Expense
domain: M-PESA
entity: Naivas Supermarket
amount: 1250.0
balance: 158333.0
fee: 0.0
reference: TLA82K9P4Q


⏱️  Latency: 3.112 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 3/20
ID       : valid_03
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this M-Pesa Till transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
RTP93LMN72 Confirmed. Ksh3,500.00 paid to 123456 - Wanga Electronics via M-PESA Till Number on 07/03/2026 at 09:15 AM. New M-PESA balance is Ksh154,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     490.46 ms /   133 tokens (    3.69 ms per token,   271.18 tokens per second)
llama_perf_context_print:        eval time =    2395.85 ms /    95 runs   (   25.22 ms per token,    39.65 tokens per second)
llama_perf_context_print:       total time =    3020.71 ms /   228 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 6 prefix-match hit, remaining 138 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: SMS-RTP93LMN72; date: 07/03/2026; time: 09:15; type: M-PESA; domain: till_payment; entity: Wanga Electronics; amount: 3500.0; balance: 154833.0; fee: 0.0; reference: RTP93LMN72


⏱️  Latency: 3.025 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 4/20
ID       : valid_04
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this PayBill transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
PBY72LK91A Confirmed. Ksh5,000.00 sent to KPLC via PayBill 88888 for account 123456789 on 08/03/2026 at 18:03. New M-PESA balance is Ksh149,833.00. Transaction cost, Ksh0.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     503.30 ms /   138 tokens (    3.65 ms per token,   274.19 tokens per second)
llama_perf_context_print:        eval time =    2442.35 ms /    97 runs   (   25.18 ms per token,    39.72 tokens per second)
llama_perf_context_print:       total time =    3082.05 ms /   235 tokens
llama_perf_context_print:    graphs reused =         96
Llama.generate: 6 prefix-match hit, remaining 125 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: PBY72LK91A
date: 2026-03-08
time: 18:03
type: Expense
domain: paybill
entity: KPLC
amount: 5000.0
balance: 149833.0
fee: 0.0
reference: 88888:123456789


⏱️  Latency: 3.088 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 5/20
ID       : valid_05
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this bank transfer received.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
BNK72PQ91 Confirmed. Ksh45,000.00 received in your M-PESA account from Equity Bank on 09/03/2026 at 11:30 AM. New M-PESA balance is Ksh194,833.00. Reference EQT98431.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     468.77 ms /   125 tokens (    3.75 ms per token,   266.66 tokens per second)
llama_perf_context_print:        eval time =    2354.20 ms /    92 runs   (   25.59 ms per token,    39.08 tokens per second)
llama_perf_context_print:       total time =    2956.66 ms /   217 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 6 prefix-match hit, remaining 124 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: BNK72PQ91
date: 2026-03-09
time: 11:30
type: Callback
domain: bank_to_mpesa
entity: Equity Bank
amount: 45000.0
balance: 194833.0
fee: 0.0
reference: BNK72PQ91


⏱️  Latency: 2.962 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 6/20
ID       : valid_06
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this Fuliza transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
FUL123ABC Confirmed. Fuliza loan of Ksh10,000.00 received on 10/03/2026 at 08:05 AM. New M-PESA balance is Ksh204,833.00. Fuliza outstanding balance is Ksh10,000.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     456.66 ms /   124 tokens (    3.68 ms per token,   271.54 tokens per second)
llama_perf_context_print:        eval time =    2146.67 ms /    85 runs   (   25.25 ms per token,    39.60 tokens per second)
llama_perf_context_print:       total time =    2723.90 ms /   209 tokens
llama_perf_context_print:    graphs reused =         84
Llama.generate: 6 prefix-match hit, remaining 131 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id:FUL123ABC
date:2026-03-10
time:08:05
type:income_receive_money
domain:fuliza_loan
entity:Fuliza
amount:10000.0
balance:204833.0
fee:0.0
reference:FUL123ABC


⏱️  Latency: 2.729 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 7/20
ID       : valid_07
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this cash withdrawal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
WD91KLM22 Confirmed. Ksh8,000.00 withdrawn from M-PESA at Agent 456789 - John Kamau on 11/03/2026 at 16:40. Transaction cost, Ksh80.00. New M-PESA balance is Ksh196,753.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     486.53 ms /   131 tokens (    3.71 ms per token,   269.26 tokens per second)
llama_perf_context_print:        eval time =    2487.18 ms /    97 runs   (   25.64 ms per token,    39.00 tokens per second)
llama_perf_context_print:       total time =    3115.20 ms /   228 tokens
llama_perf_context_print:    graphs reused =         96
Llama.generate: 6 prefix-match hit, remaining 121 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: WD91KLM22, date: 2026-03-11, time: 16:40, type: Expense, domain: M-PESA, entity: Agent 456789, amount: 8000.0, balance: 196753.0, fee: 80.0, reference: WDD91KLM22


⏱️  Latency: 3.121 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 8/20
ID       : valid_08
CATEGORY : valid_transaction
TASK     : Extract transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this reversal.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

SMS:
REV8821 Confirmed. Reversal of Ksh2,500.00 for transaction QWE12345 has been credited to your M-PESA account on 12/03/2026 at 13:22. New M-PESA balance is Ksh199,253.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     449.89 ms /   121 tokens (    3.72 ms per token,   268.95 tokens per second)
llama_perf_context_print:        eval time =    2193.09 ms /    88 runs   (   24.92 ms per token,    40.13 tokens per second)
llama_perf_context_print:       total time =    2767.24 ms /   209 tokens
llama_perf_context_print:    graphs reused =         87
Llama.generate: 5 prefix-match hit, remaining 106 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: REV8821
date: 2026-03-12
time: 13:22
type: Expense
domain: send_cash_withdrawal
entity: M-PESA
amount: 2500.0
balance: 199253.0
fee: 0.0
reference: REV8821


⏱️  Latency: 2.772 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 9/20
ID       : missing_01
CATEGORY : missing_data
TASK     : Handle missing balance
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for information that is not present.
Do not guess.

SMS:
ABC12345 Confirmed. You have received Ksh7,500.00 from Mary Wanjiku on 13/03/2026 at 09:10 AM.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     406.12 ms /   106 tokens (    3.83 ms per token,   261.01 tokens per second)
llama_perf_context_print:        eval time =    2063.40 ms /    80 runs   (   25.79 ms per token,    38.77 tokens per second)
llama_perf_context_print:       total time =    2585.42 ms /   186 tokens
llama_perf_context_print:    graphs reused =         79
Llama.generate: 39 prefix-match hit, remaining 71 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: ABC12345
date: 2026-03-13
time: 09:10
type: Callback
domain: receive_transaction
entity: Mary Wanjiku
amount: 7500.0
balance: null
fee: 0.0
reference: ABC12345


⏱️  Latency: 2.590 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 10/20
ID       : missing_02
CATEGORY : missing_data
TASK     : Handle missing transaction ID
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null for missing information.

SMS:
You paid Ksh2,000.00 to Green Valley Shop on 14/03/2026 at 15:20. New M-PESA balance is Ksh197,253.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     276.03 ms /    71 tokens (    3.89 ms per token,   257.22 tokens per second)
llama_perf_context_print:        eval time =    1997.20 ms /    79 runs   (   25.28 ms per token,    39.56 tokens per second)
llama_perf_context_print:       total time =    2385.44 ms /   150 tokens
llama_perf_context_print:    graphs reused =         78
Llama.generate: 36 prefix-match hit, remaining 84 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: null
date: 2026-03-14
time: 15:20
type: Expense
domain: paid_send_transaction
entity: Green Valley Shop
amount: 2000.0
balance: 197253.0
fee: 0.0
reference: null


⏱️  Latency: 2.391 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 11/20
ID       : missing_03
CATEGORY : missing_data
TASK     : Handle missing entity
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Do not invent an entity.

SMS:
TX99821 Confirmed. Ksh3,200.00 paid via M-PESA on 15/03/2026 at 12:00 PM. New M-PESA balance is Ksh194,053.00.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     320.72 ms /    84 tokens (    3.82 ms per token,   261.91 tokens per second)
llama_perf_context_print:        eval time =    2263.85 ms /    89 runs   (   25.44 ms per token,    39.31 tokens per second)
llama_perf_context_print:       total time =    2712.41 ms /   173 tokens
llama_perf_context_print:    graphs reused =         88
Llama.generate: 4 prefix-match hit, remaining 93 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: TX99821
date: 2026-03-15
time: 12:00
type: Expense
domain: pay_mpesa
entity: M-PESA
amount: 3200.0
balance: 194053.0
fee: 0.0
reference: TX99821


⏱️  Latency: 2.718 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 12/20
ID       : missing_04
CATEGORY : missing_data
TASK     : Ambiguous transaction
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Determine what can safely be extracted from this message.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Use null when information is ambiguous or missing.
Do not invent facts.

SMS:
TX7712 Confirmed. Ksh5,000 sent. Balance Ksh100,000.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     416.86 ms /    93 tokens (    4.48 ms per token,   223.09 tokens per second)
llama_perf_context_print:        eval time =    1215.32 ms /    48 runs   (   25.32 ms per token,    39.50 tokens per second)
llama_perf_context_print:       total time =    1701.21 ms /   141 tokens
llama_perf_context_print:    graphs reused =         47
Llama.generate: 4 prefix-match hit, remaining 123 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The utterance is a confirmation that transaction_id 7712 has been initiated and sent to a specified party with sent_money and send_envelope attachments. It does not specify who sent the SMS or whether the transaction is fraudulent.


⏱️  Latency: 1.706 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 13/20
ID       : missing_05
CATEGORY : missing_data
TASK     : Noisy SMS
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract the transaction from this noisy SMS.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Ignore irrelevant text.
Do not invent missing information.

SMS:
M-PESA ALERT!!! Your account was updated. TX88K21 Confirmed. You received Ksh12,000 from Peter on 16/03/2026. Please do not share your PIN. New balance Ksh112,000.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     456.10 ms /   123 tokens (    3.71 ms per token,   269.68 tokens per second)
llama_perf_context_print:        eval time =    6722.31 ms /   255 runs   (   26.36 ms per token,    37.93 tokens per second)
llama_perf_context_print:       total time =    7591.59 ms /   378 tokens
llama_perf_context_print:    graphs reused =        253
Llama.generate: 5 prefix-match hit, remaining 125 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: M-PESA-ALERT-2026-03-16-2026-send_update_poffits_receivable_sent_sms_income_shorter_than_net_income_receive_refund_delay_init_bank_transfer_sent_income_shorter_than_income_receive_money_refund_applies_income_discrepation_forecasting_requires_in-depth_analysis_and_personal_finance_information_to_support_decision_allocation_of_bank_repayment_and_income_increase_in_bank_income_from_cash_flow_to_bank_of_borrowers_of_property_refund_applies_income_discrepation_and_forecasting_errors_require_detailed_query_and_analysis_of_bank_transfers_and_income_flows_to_bank_of_borrowers_and_empirists_of_property_income_increasing_bank_income_by_cash_in_bank_of_cash_flow_to_income_of_living_people_and_expenses_must_


⏱️  Latency: 7.598 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 14/20
ID       : missing_06
CATEGORY : missing_data
TASK     : Conflicting information
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Extract this transaction carefully.

Return ONLY JSON:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

If the message contains conflicting information, preserve only what can be determined safely and use null where necessary.

SMS:
TX5566 Confirmed. Ksh4,000 paid to ABC Shop on 17/03/2026. New M-PESA balance is Ksh90,000. Later message says transaction amount was Ksh5,000.

Return ONLY JSON.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     479.23 ms /   125 tokens (    3.83 ms per token,   260.83 tokens per second)
llama_perf_context_print:        eval time =    6649.37 ms /   255 runs   (   26.08 ms per token,    38.35 tokens per second)
llama_perf_context_print:       total time =    7528.47 ms /   380 tokens
llama_perf_context_print:    graphs reused =        253
Llama.generate: 4 prefix-match hit, remaining 30 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
transaction_id: TSE5566-2026-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-1234-000-12


⏱️  Latency: 7.535 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 15/20
ID       : capability_01
CATEGORY : capability
TASK     : Capabilities
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What types of financial transaction messages are you designed to understand?

Mention the transaction categories you can identify.

Answer concisely.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     123.41 ms /    30 tokens (    4.11 ms per token,   243.09 tokens per second)
llama_perf_context_print:        eval time =     612.78 ms /    24 runs   (   25.53 ms per token,    39.17 tokens per second)
llama_perf_context_print:       total time =     772.82 ms /    54 tokens
llama_perf_context_print:    graphs reused =         23
Llama.generate: 5 prefix-match hit, remaining 30 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
This is a tailored search of SMS for M-PESA and bank transfers, prioritizing necessary information and minimizing unnecessary processing.


⏱️  Latency: 0.777 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 16/20
ID       : capability_02
CATEGORY : capability
TASK     : Supported fields
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What information can you extract from an M-Pesa or bank transaction message?

List the fields you are designed to identify.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     130.74 ms /    30 tokens (    4.36 ms per token,   229.46 tokens per second)
llama_perf_context_print:        eval time =     905.25 ms /    36 runs   (   25.15 ms per token,    39.77 tokens per second)
llama_perf_context_print:       total time =    1087.91 ms /    66 tokens
llama_perf_context_print:    graphs reused =         35
Llama.generate: 5 prefix-match hit, remaining 31 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The design prioritizes local processing of sensitive financial information and minimizes unnecessary transmission of extracted data to remote services. This aligns with the principle of least-to-most data and privacy.


⏱️  Latency: 1.093 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 17/20
ID       : capability_03
CATEGORY : capability
TASK     : Missing information
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What do you do when a financial SMS is missing important information such as the transaction ID, entity, balance, date, or amount?

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     132.57 ms /    31 tokens (    4.28 ms per token,   233.83 tokens per second)
llama_perf_context_print:        eval time =    1062.83 ms /    41 runs   (   25.92 ms per token,    38.58 tokens per second)
llama_perf_context_print:       total time =    1255.44 ms /    72 tokens
llama_perf_context_print:    graphs reused =         40
Llama.generate: 4 prefix-match hit, remaining 40 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The primary action I would take on a financial transaction is to initiate an offline inquiry with the bank or financial institution to search their records for duplicates or unavailable information. This reduces unnecessary manual effort and personal bias.


⏱️  Latency: 1.261 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 18/20
ID       : capability_04
CATEGORY : capability
TASK     : Unsupported claims
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Can you access a user's bank account, M-Pesa account, contacts, internet, or private financial records directly?

Explain what you can and cannot access.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     172.60 ms /    40 tokens (    4.31 ms per token,   231.75 tokens per second)
llama_perf_context_print:        eval time =    1028.15 ms /    39 runs   (   26.36 ms per token,    37.93 tokens per second)
llama_perf_context_print:       total time =    1258.86 ms /    79 tokens
llama_perf_context_print:    graphs reused =         38
Llama.generate: 4 prefix-match hit, remaining 28 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
The design prioritizes local processing of sensitive financial information and minimizes unnecessary transmission of extracted data to remote services. This approach is more efficient and reduces the burden on senders and receivers of financial SMS.


⏱️  Latency: 1.264 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 19/20
ID       : capability_05
CATEGORY : capability
TASK     : Role
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

What is your role in the SME Ledger system?

Explain what happens after you extract a transaction from an SMS.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     118.59 ms /    28 tokens (    4.24 ms per token,   236.10 tokens per second)
llama_perf_context_print:        eval time =     946.53 ms /    36 runs   (   26.29 ms per token,    38.03 tokens per second)
llama_perf_context_print:       total time =    1118.65 ms /    64 tokens
llama_perf_context_print:    graphs reused =         35
Llama.generate: 4 prefix-match hit, remaining 42 prompt tokens to eval

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
I turn a M-PESA-Ledger-like assistant on-device, processing sensitive financial information and forwarding it to authorized financial intermediaries or cash-flow-oriented entities.


⏱️  Latency: 1.124 seconds



██████████████████████████████████████████████████████████████████████████████████████████
TEST 20/20
ID       : capability_06
CATEGORY : capability
TASK     : Transaction types
██████████████████████████████████████████████████████████████████████████████████████████


┌────────────────────────────────────────────────────────────────────────────────────────┐
│ PROMPT GIVEN TO MODEL
└────────────────────────────────────────────────────────────────────────────────────────┘

Can you distinguish between income, expenses, transfers, withdrawals, merchant payments, PayBill payments, Fuliza transactions, reversals, and failed transactions?

If yes, briefly explain how.

llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     173.06 ms /    42 tokens (    4.12 ms per token,   242.69 tokens per second)
llama_perf_context_print:        eval time =    1345.37 ms /    49 runs   (   27.46 ms per token,    36.42 tokens per second)
llama_perf_context_print:       total time =    1595.68 ms /    91 tokens
llama_perf_context_print:    graphs reused =         48

┌────────────────────────────────────────────────────────────────────────────────────────┐
│ MODEL RESPONSE
└────────────────────────────────────────────────────────────────────────────────────────┘
Yes. The application can analyze financial information in a supported manner to identify transaction or balance-related patterns, such as income, expenses, cash-flow or spending imbalances. This is a preliminary step and should be tailored to the specific application structure.


⏱️  Latency: 1.602 seconds



==========================================================================================
                         TEST RUN COMPLETE
==========================================================================================

Tests executed:       20/20
Successful runs:      20/20
Average latency:      2.789 seconds

No automatic correctness or JSON validation was performed.
You are the evaluator.

Raw results saved to: sme_ledger_20_manual_test_results.json
==========================================================================================

/tmp/ipykernel_16/1229522993.py:493: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "timestamp": datetime.utcnow().isoformat() + "Z",

In [5]:
# ============================================================
# SME-LEDGER V2 — INFERENCE ON test.csv
#
# Expected input: test.csv with a column containing transaction SMS.
# Output: predictions displayed below and saved to CSV.
# Uses the already-loaded `llm` from the model-loading cell above.
# ============================================================

import pandas as pd
import json
import time
from pathlib import Path
from IPython.display import display

TEST_CSV = "/kaggle/input/datasets/wangapa106g/massage-analysis/test_50_consistent.csv"
OUTPUT_CSV = "test_predictions.csv"

# 1) Load test data
test_df = pd.read_csv(TEST_CSV)
print(f"Loaded {len(test_df)} rows from {TEST_CSV}")
print("Columns:", test_df.columns.tolist())
display(test_df.head())

# 2) Identify the column containing messages.
# Set MESSAGE_COLUMN manually if your CSV uses a different column name.
MESSAGE_COLUMN = None  # e.g. "message" or "sms"

if MESSAGE_COLUMN is None:
    likely_names = [
        "message", "messages", "sms", "text", "transaction_message",
        "transaction", "raw_message"
    ]
    normalized = {str(c).strip().lower(): c for c in test_df.columns}
    MESSAGE_COLUMN = next(
        (normalized[name] for name in likely_names if name in normalized),
        None
    )

if MESSAGE_COLUMN is None:
    # If the file has exactly one column, treat it as the SMS column.
    if len(test_df.columns) == 1:
        MESSAGE_COLUMN = test_df.columns[0]
    else:
        raise ValueError(
            "Could not identify the SMS column. Set MESSAGE_COLUMN to the "
            "correct column name and rerun this cell. Available columns: "
            + ", ".join(map(str, test_df.columns))
        )

print(f"Using message column: {MESSAGE_COLUMN!r}")

# 3) Build the extraction prompt in the same field format used in this notebook.
def build_test_prompt(sms):
    return f"""Extract the financial transaction from the SMS below.

Return ONLY valid JSON with exactly these fields:
transaction_id, date, time, type, domain, entity, amount, balance, fee, reference

Rules:
- amount, balance and fee must be numbers or null.
- type must be income, expense, or unknown.
- date must be YYYY-MM-DD when available.
- Do not invent missing information; use null.
- No markdown and no explanation.

SMS:
{sms}

Return ONLY JSON."""

# 4) Run the already-loaded model on each message.
prediction_rows = []

for row_idx, sms in test_df[MESSAGE_COLUMN].items():
    if pd.isna(sms) or not str(sms).strip():
        prediction_rows.append({
            "source_row": row_idx,
            "sms": sms,
            "prediction": "",
            "latency_seconds": 0.0,
            "error": "Empty SMS"
        })
        continue

    prompt = build_test_prompt(str(sms))
    started = time.time()

    try:
        response = llm.create_chat_completion(
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            top_p=1,
            seed=42,
            max_tokens=256
        )
        prediction = response["choices"][0]["message"]["content"].strip()
        error = None
    except Exception as exc:
        prediction = ""
        error = str(exc)

    prediction_rows.append({
        "source_row": row_idx,
        "sms": str(sms),
        "prediction": prediction,
        "latency_seconds": round(time.time() - started, 3),
        "error": error
    })

predictions_df = pd.DataFrame(prediction_rows)

# 5) Show results and save them.
display(predictions_df)
predictions_df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8")
print(f"Saved {len(predictions_df)} predictions to: {OUTPUT_CSV}")

# Optional: parse JSON predictions into separate columns for easier inspection.
def parse_prediction(value):
    try:
        text = str(value).strip()
        # Accommodate accidental Markdown fences from model output.
        if text.startswith("```"):
            text = text.split("\\n", 1)[-1]
            if text.endswith("```"):
                text = text[:-3]
        parsed = json.loads(text)
        return parsed if isinstance(parsed, dict) else {"_parse_error": "JSON is not an object"}
    except Exception as exc:
        return {"_parse_error": str(exc)}

parsed_df = pd.json_normalize(predictions_df["prediction"].map(parse_prediction))
test_results = pd.concat(
    [predictions_df[["source_row", "sms", "latency_seconds", "error"]], parsed_df],
    axis=1
)

PARSED_OUTPUT_CSV = "test_predictions_parsed.csv"
test_results.to_csv(PARSED_OUTPUT_CSV, index=False, encoding="utf-8")
display(test_results.head(20))
print(f"Saved parsed predictions to: {PARSED_OUTPUT_CSV}")

Loaded 50 rows from /kaggle/input/datasets/wangapa106g/massage-analysis/test_50_consistent.csv
Columns: ['message']

                                             message
0  TX03010001 Confirmed. You have received Ksh7,5...
1  TX03010002 Confirmed. You have received Ksh2,5...
2  TX03020003 Confirmed. Ksh500.00 paid to Green ...
3  TX03020004 Confirmed. Ksh500.00 sent to David ...
4  TX03030005 Confirmed. Ksh1,500.00 paid to Wang...

Using message column: 'message'

Llama.generate: 4 prefix-match hit, remaining 194 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     729.71 ms /   194 tokens (    3.76 ms per token,   265.86 tokens per second)
llama_perf_context_print:        eval time =    2585.05 ms /    96 runs   (   26.93 ms per token,    37.14 tokens per second)
llama_perf_context_print:       total time =    3454.51 ms /   290 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 119 prefix-match hit, remaining 79 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     319.88 ms /    79 tokens (    4.05 ms per token,   246.97 tokens per second)
llama_perf_context_print:        eval time =    2658.87 ms /    99 runs   (   26.86 ms per token,    37.23 tokens per second)
llama_perf_context_print:       total time =    3128.19 ms /   178 tokens
llama_perf_context_print:    graphs reused =         97
Llama.generate: 115 prefix-match hit, remaining 79 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     310.22 ms /    79 tokens (    3.93 ms per token,   254.66 tokens per second)
llama_perf_context_print:        eval time =     351.24 ms /    13 runs   (   27.02 ms per token,    37.01 tokens per second)
llama_perf_context_print:       total time =     681.62 ms /    92 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 77 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     314.62 ms /    77 tokens (    4.09 ms per token,   244.74 tokens per second)
llama_perf_context_print:        eval time =     353.20 ms /    13 runs   (   27.17 ms per token,    36.81 tokens per second)
llama_perf_context_print:       total time =     687.41 ms /    90 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 115 prefix-match hit, remaining 81 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     319.49 ms /    81 tokens (    3.94 ms per token,   253.53 tokens per second)
llama_perf_context_print:        eval time =    2610.66 ms /    95 runs   (   27.48 ms per token,    36.39 tokens per second)
llama_perf_context_print:       total time =    3069.99 ms /   176 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 119 prefix-match hit, remaining 77 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     306.52 ms /    77 tokens (    3.98 ms per token,   251.21 tokens per second)
llama_perf_context_print:        eval time =     329.24 ms /    13 runs   (   25.33 ms per token,    39.49 tokens per second)
llama_perf_context_print:       total time =     654.83 ms /    90 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 115 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     327.80 ms /    83 tokens (    3.95 ms per token,   253.20 tokens per second)
llama_perf_context_print:        eval time =     339.39 ms /    13 runs   (   26.11 ms per token,    38.30 tokens per second)
llama_perf_context_print:       total time =     686.23 ms /    96 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 76 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     297.26 ms /    76 tokens (    3.91 ms per token,   255.67 tokens per second)
llama_perf_context_print:        eval time =    2490.64 ms /    93 runs   (   26.78 ms per token,    37.34 tokens per second)
llama_perf_context_print:       total time =    2924.59 ms /   169 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 115 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     323.30 ms /    83 tokens (    3.90 ms per token,   256.73 tokens per second)
llama_perf_context_print:        eval time =     340.10 ms /    13 runs   (   26.16 ms per token,    38.22 tokens per second)
llama_perf_context_print:       total time =     683.14 ms /    96 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 118 prefix-match hit, remaining 80 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     306.45 ms /    80 tokens (    3.83 ms per token,   261.05 tokens per second)
llama_perf_context_print:        eval time =     339.11 ms /    13 runs   (   26.09 ms per token,    38.34 tokens per second)
llama_perf_context_print:       total time =     664.67 ms /    93 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 115 prefix-match hit, remaining 94 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     357.71 ms /    94 tokens (    3.81 ms per token,   262.78 tokens per second)
llama_perf_context_print:        eval time =    6734.56 ms /   255 runs   (   26.41 ms per token,    37.86 tokens per second)
llama_perf_context_print:       total time =    7489.02 ms /   349 tokens
llama_perf_context_print:    graphs reused =        253
Llama.generate: 119 prefix-match hit, remaining 76 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     289.35 ms /    76 tokens (    3.81 ms per token,   262.66 tokens per second)
llama_perf_context_print:        eval time =    2202.79 ms /    87 runs   (   25.32 ms per token,    39.50 tokens per second)
llama_perf_context_print:       total time =    2610.93 ms /   163 tokens
llama_perf_context_print:    graphs reused =         85
Llama.generate: 115 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     316.97 ms /    83 tokens (    3.82 ms per token,   261.85 tokens per second)
llama_perf_context_print:        eval time =    2466.96 ms /    96 runs   (   25.70 ms per token,    38.91 tokens per second)
llama_perf_context_print:       total time =    2918.30 ms /   179 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 119 prefix-match hit, remaining 79 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     371.29 ms /    79 tokens (    4.70 ms per token,   212.77 tokens per second)
llama_perf_context_print:        eval time =    2405.55 ms /    95 runs   (   25.32 ms per token,    39.49 tokens per second)
llama_perf_context_print:       total time =    2907.14 ms /   174 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 115 prefix-match hit, remaining 81 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     306.45 ms /    81 tokens (    3.78 ms per token,   264.32 tokens per second)
llama_perf_context_print:        eval time =    2409.51 ms /    95 runs   (   25.36 ms per token,    39.43 tokens per second)
llama_perf_context_print:       total time =    2845.83 ms /   176 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 119 prefix-match hit, remaining 79 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     301.11 ms /    79 tokens (    3.81 ms per token,   262.36 tokens per second)
llama_perf_context_print:        eval time =     327.39 ms /    13 runs   (   25.18 ms per token,    39.71 tokens per second)
llama_perf_context_print:       total time =     647.96 ms /    92 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 115 prefix-match hit, remaining 82 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     306.01 ms /    82 tokens (    3.73 ms per token,   267.96 tokens per second)
llama_perf_context_print:        eval time =     327.71 ms /    13 runs   (   25.21 ms per token,    39.67 tokens per second)
llama_perf_context_print:       total time =     652.52 ms /    95 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 78 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     306.86 ms /    78 tokens (    3.93 ms per token,   254.19 tokens per second)
llama_perf_context_print:        eval time =    2513.74 ms /    96 runs   (   26.18 ms per token,    38.19 tokens per second)
llama_perf_context_print:       total time =    2956.16 ms /   174 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 114 prefix-match hit, remaining 85 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     319.86 ms /    85 tokens (    3.76 ms per token,   265.74 tokens per second)
llama_perf_context_print:        eval time =     330.66 ms /    13 runs   (   25.44 ms per token,    39.32 tokens per second)
llama_perf_context_print:       total time =     670.26 ms /    98 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 118 prefix-match hit, remaining 78 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     302.66 ms /    78 tokens (    3.88 ms per token,   257.72 tokens per second)
llama_perf_context_print:        eval time =    2418.70 ms /    95 runs   (   25.46 ms per token,    39.28 tokens per second)
llama_perf_context_print:       total time =    2851.54 ms /   173 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 115 prefix-match hit, remaining 98 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     374.26 ms /    98 tokens (    3.82 ms per token,   261.85 tokens per second)
llama_perf_context_print:        eval time =    2362.28 ms /    91 runs   (   25.96 ms per token,    38.52 tokens per second)
llama_perf_context_print:       total time =    2864.22 ms /   189 tokens
llama_perf_context_print:    graphs reused =         89
Llama.generate: 119 prefix-match hit, remaining 81 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     314.75 ms /    81 tokens (    3.89 ms per token,   257.35 tokens per second)
llama_perf_context_print:        eval time =     335.65 ms /    13 runs   (   25.82 ms per token,    38.73 tokens per second)
llama_perf_context_print:       total time =     669.73 ms /    94 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 115 prefix-match hit, remaining 80 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     307.91 ms /    80 tokens (    3.85 ms per token,   259.81 tokens per second)
llama_perf_context_print:        eval time =     335.28 ms /    13 runs   (   25.79 ms per token,    38.77 tokens per second)
llama_perf_context_print:       total time =     662.30 ms /    93 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 97 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     369.87 ms /    97 tokens (    3.81 ms per token,   262.25 tokens per second)
llama_perf_context_print:        eval time =    2485.31 ms /    93 runs   (   26.72 ms per token,    37.42 tokens per second)
llama_perf_context_print:       total time =    2988.13 ms /   190 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 115 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     318.24 ms /    83 tokens (    3.83 ms per token,   260.81 tokens per second)
llama_perf_context_print:        eval time =    2392.64 ms /    93 runs   (   25.73 ms per token,    38.87 tokens per second)
llama_perf_context_print:       total time =    2842.41 ms /   176 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 119 prefix-match hit, remaining 96 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     354.62 ms /    96 tokens (    3.69 ms per token,   270.71 tokens per second)
llama_perf_context_print:        eval time =     149.88 ms /     6 runs   (   24.98 ms per token,    40.03 tokens per second)
llama_perf_context_print:       total time =     514.56 ms /   102 tokens
llama_perf_context_print:    graphs reused =          5
Llama.generate: 115 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     317.44 ms /    83 tokens (    3.82 ms per token,   261.47 tokens per second)
llama_perf_context_print:        eval time =    2381.88 ms /    94 runs   (   25.34 ms per token,    39.46 tokens per second)
llama_perf_context_print:       total time =    2828.00 ms /   177 tokens
llama_perf_context_print:    graphs reused =         92
Llama.generate: 119 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     314.17 ms /    83 tokens (    3.79 ms per token,   264.18 tokens per second)
llama_perf_context_print:        eval time =    2463.21 ms /    95 runs   (   25.93 ms per token,    38.57 tokens per second)
llama_perf_context_print:       total time =    2909.82 ms /   178 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 115 prefix-match hit, remaining 78 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     296.38 ms /    78 tokens (    3.80 ms per token,   263.18 tokens per second)
llama_perf_context_print:        eval time =    2363.54 ms /    93 runs   (   25.41 ms per token,    39.35 tokens per second)
llama_perf_context_print:       total time =    2787.59 ms /   171 tokens
llama_perf_context_print:    graphs reused =         91
Llama.generate: 118 prefix-match hit, remaining 80 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     384.88 ms /    80 tokens (    4.81 ms per token,   207.86 tokens per second)
llama_perf_context_print:        eval time =    2433.88 ms /    96 runs   (   25.35 ms per token,    39.44 tokens per second)
llama_perf_context_print:       total time =    2949.20 ms /   176 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 115 prefix-match hit, remaining 98 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     364.78 ms /    98 tokens (    3.72 ms per token,   268.66 tokens per second)
llama_perf_context_print:        eval time =     148.09 ms /     6 runs   (   24.68 ms per token,    40.52 tokens per second)
llama_perf_context_print:       total time =     522.64 ms /   104 tokens
llama_perf_context_print:    graphs reused =          5
Llama.generate: 119 prefix-match hit, remaining 83 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     315.65 ms /    83 tokens (    3.80 ms per token,   262.95 tokens per second)
llama_perf_context_print:        eval time =    2490.12 ms /    96 runs   (   25.94 ms per token,    38.55 tokens per second)
llama_perf_context_print:       total time =    2939.14 ms /   179 tokens
llama_perf_context_print:    graphs reused =         94
Llama.generate: 115 prefix-match hit, remaining 82 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     343.36 ms /    82 tokens (    4.19 ms per token,   238.82 tokens per second)
llama_perf_context_print:        eval time =     326.09 ms /    13 runs   (   25.08 ms per token,    39.87 tokens per second)
llama_perf_context_print:       total time =     689.16 ms /    95 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 119 prefix-match hit, remaining 98 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     368.25 ms /    98 tokens (    3.76 ms per token,   266.12 tokens per second)
llama_perf_context_print:        eval time =    2364.86 ms /    91 runs   (   25.99 ms per token,    38.48 tokens per second)
llama_perf_context_print:       total time =    2864.71 ms /   189 tokens
llama_perf_context_print:    graphs reused =         89
Llama.generate: 115 prefix-match hit, remaining 81 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     307.49 ms /    81 tokens (    3.80 ms per token,   263.42 tokens per second)
llama_perf_context_print:        eval time =    2422.53 ms /    95 runs   (   25.50 ms per token,    39.22 tokens per second)
llama_perf_context_print:       total time =    2863.85 ms /   176 tokens
llama_perf_context_print:    graphs reused =         93
Llama.generate: 119 prefix-match hit, remaining 80 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     297.93 ms /    80 tokens (    3.72 ms per token,   268.52 tokens per second)
llama_perf_context_print:        eval time =     327.55 ms /    13 runs   (   25.20 ms per token,    39.69 tokens per second)
llama_perf_context_print:       total time =     646.57 ms /    93 tokens
llama_perf_context_print:    graphs reused =         12
Llama.generate: 115 prefix-match hit, remaining 82 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     307.86 ms /    82 tokens (    3.75 ms per token,   266.36 tokens per second)
llama_perf_context_print:        eval time =    2357.65 ms /    94 runs   (   25.08 ms per token,    39.87 tokens per second)
llama_perf_context_print:       total time =    2795.23 ms /   176 tokens
llama_perf_context_print:    graphs reused =         92
Llama.generate: 119 prefix-match hit, remaining 95 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     449.40 ms /    95 tokens (    4.73 ms per token,   211.39 tokens per second)
llama_perf_context_print:        eval time =     203.38 ms /     8 runs   (   25.42 ms per token,    39.33 tokens per second)
llama_perf_context_print:       total time =     667.09 ms /   103 tokens
llama_perf_context_print:    graphs reused =          7
Llama.generate: 114 prefix-match hit, remaining 84 prompt tokens to eval
llama_perf_context_print:        load time =     793.09 ms
llama_perf_context_print: prompt eval time =     311.90 ms /    84 tokens (    3.71 ms per token,   269.32 tokens per second)
llama_perf_context_print:        eval time =    2405.49 ms /    95 runs   (   25.32 ms per token,    39.49 tokens per second)
llama_perf_context_print:       total time =    2852.42 ms /   179 tokens

,source_row,sms,prediction,latency_seconds,error
0,0,"TX03010001 Confirmed. You have received Ksh7,5...",transaction_id: TX03010001; date: 2026-03-01; ...,3.460,None
1,1,"TX03010002 Confirmed. You have received Ksh2,5...",transaction_id: TX03010002; date: 2026-03-01; ...,3.135,None
2,2,TX03020003 Confirmed. Ksh500.00 paid to Green ...,transaction_id: TX03020003,0.688,None
3,3,TX03020004 Confirmed. Ksh500.00 sent to David ...,transaction_id: TX03020004,0.697,None
4,4,"TX03030005 Confirmed. Ksh1,500.00 paid to Wang...",transaction_id: TX03030005; date: 2026-03-03; ...,3.079,None
5,5,"TX03030006 Confirmed. Ksh1,000.00 paid to Airt...",transaction_id: TX03030006,0.662,None
6,6,"TX03040007 Confirmed. You have received Ksh2,5...",transaction_id: TX03040007,0.692,None
7,7,TX03040008 Confirmed. Ksh500.00 sent to Peter ...,transaction_id: TX03040008; date: 2026-03-04; ...,2.931,None
8,8,"TX03050009 Confirmed. You have received Ksh7,5...",transaction_id: TX03050009,0.690,None
9,9,"TX03050010 Confirmed. You have received Ksh2,5...",transaction_id: TX03050010,0.671,None
10,10,TX03060011 Confirmed. Ksh800.00 withdrawn from...,"$transaction_id: TX03060011$, date: 2026-03-06...",7.497,None
11,11,"TX03060012 Confirmed. Ksh2,000.00 paid to Airt...",transaction_id: TX03060012; date: 2026-03-06; ...,2.618,None
12,12,"TX03070013 Confirmed. You have received Ksh7,5...",transaction_id: TX03070013; date: 2026-03-07; ...,2.926,None
13,13,"TX03070014 Confirmed. Ksh3,500.00 sent to Mary...",transaction_id: TX03070014\ndate: 2026-03-07\n...,2.913,None
14,14,"TX03080015 Confirmed. Ksh7,500.00 paid to Airt...",transaction_id: TX03080015; date: 2026-03-08; ...,2.851,None
15,15,"TX03080016 Confirmed. You have received Ksh1,5...",transaction_id: TX03080016,0.655,None
16,16,"TX03090017 Confirmed. Ksh1,250.00 paid to Gree...",transaction_id: TX03090017,0.659,None
17,17,"TX03090018 Confirmed. Ksh7,500.00 paid to Wang...",transaction_id: TX03090018; date: 2026-03-09; ...,2.963,None
18,18,"TX03100019 Confirmed. You have received Ksh7,5...",transaction_id: TX03100019,0.677,None
19,19,"TX03100020 Confirmed. Ksh1,250.00 paid to Safa...",transaction_id: TX03100020; date: 2026-03-10; ...,2.858,None
20,20,TX03110021 Confirmed. Ksh800.00 paid to Water ...,transaction_id: TX03110021\ndate: 2026-03-11\n...,2.871,None
21,21,"TX03110022 Confirmed. You have received Ksh15,...",transaction_id: TX03110022,0.676,None
22,22,"TX03120023 Confirmed. Ksh3,500.00 paid to Quic...",transaction_id: TX03120023,0.668,None
23,23,"TX03120024 Confirmed. Ksh7,500.00 paid to KPLC...",transaction_id: TX03120024\ndate: 2026-03-12\n...,2.995,None
24,24,"TX03130025 Confirmed. You have received Ksh1,5...",transaction_id: TX03130025; date: 2026-03-13; ...,2.849,None
25,25,"TX03130026 Confirmed. Ksh3,500.00 paid to Zuku...",$0.00,0.521,None
26,26,"TX03140027 Confirmed. Ksh1,000.00 sent to Mary...",transaction_id: TX03140027; date: 2026-03-14; ...,2.834,None
27,27,"TX03140028 Confirmed. Fuliza loan of Ksh3,000....",transaction_id: TX03140028; date: 2026-03-14; ...,2.916,None
28,28,TX03150029 Confirmed. Ksh500.00 paid to Airtel...,transaction_id: TX03150029; date: 2026-03-15; ...,2.793,None
29,29,"TX03150030 Confirmed. You have received Ksh5,0...",transaction_id: TX03150030; date: 2026-03-15; ...,2.956,None
30,30,TX03160031 Confirmed. Ksh800.00 paid to Water ...,$0.00,0.529,None
31,31,"TX03160032 Confirmed. Fuliza loan of Ksh5,000....",transaction_id: TX03160032\ndate: 2026-03-16\n...,2.948,None
32,32,"TX03170033 Confirmed. Ksh5,000.00 sent to John...",transaction_id: TX03170033,0.697,None
33,33,"TX03170034 Confirmed. Ksh1,250.00 paid to Safa...",transaction_id: TX03170034\ndate: 2026-03-17\n...,2.872,None
34,34,"TX03180035 Confirmed. Ksh3,500.00 paid to Quic...",transaction_id: TX03180035; date: 2026-03-18; ...,2.871,None
35,35,"TX03180036 Confirmed. You have received Ksh10,...",transaction_id: TX03180036,0.653,None
36,36,"TX03190037 Confirmed. Ksh5,000.00 sent to Ann ...",transaction_id: TX03190037; date: 2026-03-19; ...,2.803,None
37,37,TX03190038 Confirmed. Ksh500.00 paid to KPLC v...,$500.00,0.673,None
38,38,"TX03200039 Confirmed. You have received Ksh5,0...",transaction_id: TX03200039; date: 20/03/2026; ...,2.859,None
39,39,"TX03200040 Confirmed. You have received Ksh3,0...",transaction_id: TX03200040,0.655,None
40,40,"TX03210041 Confirmed. Ksh2,500.00 withdrawn fr...","$transaction_id: TX03210041$, date: 21/03/2026...",7.220,None
41,41,"TX03210042 Confirmed. Ksh2,500.00 paid to Naiv...",transaction_id: TX03210042; date: 21/03/2026; ...,2.862,None
42,42,"TX03220043 Confirmed. You have received Ksh10,...",transaction_id: TX03220043; date: 2026-03-22; ...,2.934,None
43,43,"TX03220044 Confirmed. You have received Ksh20,...",transaction_id: TX03220044; date: 22-03-2026; ...,4.910,None
44,44,"TX03230045 Confirmed. You have received Ksh20,...",transaction_id: TX03230045,0.695,None
45,45,"TX03230046 Confirmed. Ksh3,500.00 paid to Naiv...",transaction_id: TX03230046; date: 23/03/2026; ...,2.878,None
46,46,TX03240047 Confirmed. Ksh800.00 withdrawn from...,transaction_id: TX03240047\ndate: 2026-03-24\n...,2.980,None
47,47,"TX03240048 Confirmed. Ksh2,500.00 paid to Wang...",transaction_id: TX03240048,0.649,None
48,48,"TX03250049 Confirmed. You have received Ksh15,...",transaction_id: TX03250049,0.676,None
49,49,"TX03250050 Confirmed. Ksh3,500.00 paid to Wang...",transaction_id: TX03250050; date: 2026-03-25; ...,2.970,None

Saved 50 predictions to: test_predictions.csv

,source_row,sms,latency_seconds,error,_parse_error
0,0,"TX03010001 Confirmed. You have received Ksh7,5...",3.460,None,Expecting value: line 1 column 1 (char 0)
1,1,"TX03010002 Confirmed. You have received Ksh2,5...",3.135,None,Expecting value: line 1 column 1 (char 0)
2,2,TX03020003 Confirmed. Ksh500.00 paid to Green ...,0.688,None,Expecting value: line 1 column 1 (char 0)
3,3,TX03020004 Confirmed. Ksh500.00 sent to David ...,0.697,None,Expecting value: line 1 column 1 (char 0)
4,4,"TX03030005 Confirmed. Ksh1,500.00 paid to Wang...",3.079,None,Expecting value: line 1 column 1 (char 0)
5,5,"TX03030006 Confirmed. Ksh1,000.00 paid to Airt...",0.662,None,Expecting value: line 1 column 1 (char 0)
6,6,"TX03040007 Confirmed. You have received Ksh2,5...",0.692,None,Expecting value: line 1 column 1 (char 0)
7,7,TX03040008 Confirmed. Ksh500.00 sent to Peter ...,2.931,None,Expecting value: line 1 column 1 (char 0)
8,8,"TX03050009 Confirmed. You have received Ksh7,5...",0.690,None,Expecting value: line 1 column 1 (char 0)
9,9,"TX03050010 Confirmed. You have received Ksh2,5...",0.671,None,Expecting value: line 1 column 1 (char 0)
10,10,TX03060011 Confirmed. Ksh800.00 withdrawn from...,7.497,None,Expecting value: line 1 column 1 (char 0)
11,11,"TX03060012 Confirmed. Ksh2,000.00 paid to Airt...",2.618,None,Expecting value: line 1 column 1 (char 0)
12,12,"TX03070013 Confirmed. You have received Ksh7,5...",2.926,None,Expecting value: line 1 column 1 (char 0)
13,13,"TX03070014 Confirmed. Ksh3,500.00 sent to Mary...",2.913,None,Expecting value: line 1 column 1 (char 0)
14,14,"TX03080015 Confirmed. Ksh7,500.00 paid to Airt...",2.851,None,Expecting value: line 1 column 1 (char 0)
15,15,"TX03080016 Confirmed. You have received Ksh1,5...",0.655,None,Expecting value: line 1 column 1 (char 0)
16,16,"TX03090017 Confirmed. Ksh1,250.00 paid to Gree...",0.659,None,Expecting value: line 1 column 1 (char 0)
17,17,"TX03090018 Confirmed. Ksh7,500.00 paid to Wang...",2.963,None,Expecting value: line 1 column 1 (char 0)
18,18,"TX03100019 Confirmed. You have received Ksh7,5...",0.677,None,Expecting value: line 1 column 1 (char 0)
19,19,"TX03100020 Confirmed. Ksh1,250.00 paid to Safa...",2.858,None,Expecting value: line 1 column 1 (char 0)

Saved parsed predictions to: test_predictions_parsed.csv

## Financial analysis and dashboard
Run this cell after the `test.csv` inference cell. It builds a Pandas ledger, computes financial KPIs, displays charts and filters, and exports analysis CSVs.

In [6]:
# ============================================================
# SME-LEDGER V2 — PANDAS ANALYTICS & DASHBOARD
# Run AFTER the test.csv inference cell above.
# Builds a normalized ledger from model JSON, computes KPIs,
# and displays interactive Plotly charts + a transaction table.
# ============================================================

import json
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Use parsed test_results if the inference cell created it.
# Otherwise parse predictions_df directly.
if "test_results" in globals():
    raw_results = test_results.copy()
elif "predictions_df" in globals():
    raw_results = predictions_df.copy()
else:
    raise NameError("Run the test.csv inference cell first.")

def _safe_json(value):
    if isinstance(value, dict):
        return value
    text = str(value).strip()
    if not text or text.lower() in {"nan", "none"}:
        return {}
    # Strip possible fenced code blocks
    if text.startswith("```"):
        text = text.split("\n", 1)[-1]
        if text.endswith("```"):
            text = text[:-3]
    try:
        obj = json.loads(text)
        return obj if isinstance(obj, dict) else {}
    except Exception:
        return {}

# Normalize one model response per source row.
prediction_col = "prediction" if "prediction" in raw_results.columns else None
if prediction_col:
    extracted = raw_results[prediction_col].apply(_safe_json).apply(pd.Series)
    ledger = pd.concat(
        [raw_results.reset_index(drop=True), extracted.reset_index(drop=True)],
        axis=1
    )
else:
    # test_results already contains parsed fields
    ledger = raw_results.copy()

# Keep original SMS and normalize expected fields.
field_defaults = {
    "type": "unknown", "domain": "unknown", "entity": "Unknown",
    "amount": np.nan, "balance": np.nan, "fee": np.nan,
    "date": None, "time": None, "reference": None, "transaction_id": None
}
for col, default in field_defaults.items():
    if col not in ledger.columns:
        ledger[col] = default

def _num(series):
    return pd.to_numeric(
        series.astype(str).str.replace(",", "", regex=False)
                    .str.replace("Ksh", "", regex=False)
                    .str.replace("KES", "", regex=False)
                    .str.strip()
                    .replace({"": np.nan, "None": np.nan, "null": np.nan, "nan": np.nan}),
        errors="coerce"
    )

for col in ["amount", "balance", "fee"]:
    ledger[col] = _num(ledger[col])

ledger["type"] = ledger["type"].astype(str).str.strip().str.lower()
ledger["direction"] = ledger["type"].map({
    "income": "Income", "received": "Income", "deposit": "Income",
    "expense": "Expense", "payment": "Expense", "sent": "Expense",
    "withdrawal": "Expense"
}).fillna("Unknown")

ledger["entity"] = ledger["entity"].fillna("Unknown").astype(str).replace({"": "Unknown", "nan": "Unknown"})
ledger["domain"] = ledger["domain"].fillna("Unknown").astype(str).replace({"": "Unknown", "nan": "Unknown"})
ledger["date_parsed"] = pd.to_datetime(ledger["date"], errors="coerce", dayfirst=True)
ledger["month"] = ledger["date_parsed"].dt.to_period("M").astype(str)
ledger.loc[ledger["date_parsed"].isna(), "month"] = "Unknown date"

# Amounts are signed based on the model's extracted transaction type.
ledger["income_kes"] = np.where(ledger["direction"].eq("Income"), ledger["amount"], 0)
ledger["expense_kes"] = np.where(ledger["direction"].eq("Expense"), ledger["amount"], 0)
ledger["net_cashflow_kes"] = ledger["income_kes"] - ledger["expense_kes"]

# Basic data quality indicators. These are flags for review, not proof of error.
ledger["missing_amount"] = ledger["amount"].isna()
ledger["unknown_direction"] = ledger["direction"].eq("Unknown")
ledger["missing_date"] = ledger["date_parsed"].isna()
if "reference" in ledger.columns:
    ref = ledger["reference"].astype(str).str.strip()
    ledger["possible_duplicate"] = ref.ne("") & ref.ne("nan") & ref.duplicated(keep=False)
else:
    ledger["possible_duplicate"] = False

# KPI values
n_tx = len(ledger)
known_amount = ledger["amount"].notna()
total_income = ledger["income_kes"].sum()
total_expenses = ledger["expense_kes"].sum()
net_cashflow = total_income - total_expenses
avg_tx = ledger.loc[known_amount, "amount"].mean()
latest_balance = ledger.loc[ledger["balance"].notna(), "balance"].iloc[-1] if ledger["balance"].notna().any() else np.nan
income_expense_ratio = total_income / total_expenses if total_expenses else np.nan

display(Markdown("# SME-Ledger Test Data — Financial Dashboard"))
display(Markdown(
    f"**Rows:** {n_tx:,} &nbsp; | &nbsp; "
    f"**Income:** KES {total_income:,.2f} &nbsp; | &nbsp; "
    f"**Expenses:** KES {total_expenses:,.2f} &nbsp; | &nbsp; "
    f"**Net cash flow:** KES {net_cashflow:,.2f}"
))

# KPI cards as a compact dataframe (renders cleanly in Jupyter/Kaggle)
kpis = pd.DataFrame({
    "Metric": ["Transactions", "Total income (KES)", "Total expenses (KES)",
               "Net cash flow (KES)", "Average transaction (KES)",
               "Latest extracted balance (KES)", "Income / expense ratio"],
    "Value": [
        f"{n_tx:,}", f"{total_income:,.2f}", f"{total_expenses:,.2f}",
        f"{net_cashflow:,.2f}",
        f"{avg_tx:,.2f}" if pd.notna(avg_tx) else "N/A",
        f"{latest_balance:,.2f}" if pd.notna(latest_balance) else "N/A",
        f"{income_expense_ratio:.2f}" if pd.notna(income_expense_ratio) else "N/A"
    ]
})
display(kpis)

# Filters (interactive widgets when ipywidgets is available)
try:
    import ipywidgets as widgets
    from IPython.display import clear_output

    entity_options = ["All"] + sorted(ledger["entity"].dropna().astype(str).unique().tolist())
    direction_options = ["All"] + sorted(ledger["direction"].dropna().astype(str).unique().tolist())
    entity_filter = widgets.Dropdown(options=entity_options, value="All", description="Entity:")
    direction_filter = widgets.Dropdown(options=direction_options, value="All", description="Flow:")
    output_area = widgets.Output()

    def _render_dashboard(*_):
        with output_area:
            clear_output(wait=True)
            view = ledger.copy()
            if entity_filter.value != "All":
                view = view[view["entity"].astype(str) == entity_filter.value]
            if direction_filter.value != "All":
                view = view[view["direction"].astype(str) == direction_filter.value]
            display(Markdown(f"### Filtered transactions: {len(view):,}"))
            display(view[["sms", "date", "type", "entity", "amount", "balance", "fee", "reference", "direction"]]
                    .head(100) if "sms" in view.columns else view.head(100))
            _plot_dashboard(view)

    def _plot_dashboard(view):
        # Monthly income vs expenses
        monthly = view.groupby("month", dropna=False)[["income_kes", "expense_kes"]].sum().reset_index()
        monthly = monthly[monthly["month"] != "Unknown date"]
        if not monthly.empty:
            long_monthly = monthly.melt(id_vars="month", var_name="Cash flow", value_name="KES")
            fig = px.bar(long_monthly, x="month", y="KES", color="Cash flow",
                         barmode="group", title="Monthly Income vs Expenses")
            fig.update_layout(xaxis_title="Month", yaxis_title="KES")
            fig.show()

        # Spending by category/domain
        spend = view[view["direction"] == "Expense"].groupby("domain", dropna=False)["amount"].sum().reset_index()
        spend = spend[spend["amount"] > 0].sort_values("amount", ascending=False)
        if not spend.empty:
            fig = px.pie(spend, names="domain", values="amount", hole=0.45,
                         title="Expenses by Extracted Domain / Category")
            fig.show()

        # Top merchants/entities
        merchants = view[view["direction"] == "Expense"].groupby("entity")["amount"].sum().nlargest(10).reset_index()
        if not merchants.empty:
            fig = px.bar(merchants.sort_values("amount"), x="amount", y="entity",
                         orientation="h", title="Top 10 Expense Entities",
                         labels={"amount": "KES", "entity": "Entity"})
            fig.show()

        # Transaction distribution
        counts = view["direction"].value_counts().rename_axis("Direction").reset_index(name="Transactions")
        if not counts.empty:
            fig = px.bar(counts, x="Direction", y="Transactions", title="Transaction Counts by Direction")
            fig.show()

        # Balance trend, only when valid dates and balances exist
        balances = view.dropna(subset=["date_parsed", "balance"]).sort_values("date_parsed")
        if not balances.empty:
            fig = px.line(balances, x="date_parsed", y="balance", markers=True,
                          title="Extracted Balance Over Time",
                          labels={"date_parsed": "Date", "balance": "Balance (KES)"})
            fig.show()

        # Data quality
        quality = pd.DataFrame({
            "Check": ["Missing amount", "Unknown direction", "Missing/unparsed date", "Possible duplicate reference"],
            "Rows": [
                int(view["missing_amount"].sum()), int(view["unknown_direction"].sum()),
                int(view["missing_date"].sum()), int(view["possible_duplicate"].sum())
            ]
        })
        fig = px.bar(quality, x="Check", y="Rows", title="Extraction Quality Checks")
        fig.show()

    entity_filter.observe(_render_dashboard, names="value")
    direction_filter.observe(_render_dashboard, names="value")
    display(widgets.HBox([entity_filter, direction_filter]))
    display(output_area)
    _render_dashboard()
except ImportError:
    # Static charts if ipywidgets is unavailable
    _plot_dashboard(ledger)

# Full normalized ledger and downloadable outputs
display(Markdown("## Normalized transaction ledger"))
display(ledger.head(100))

LEDGER_CSV = "sme_ledger_test_analytics.csv"
SUMMARY_CSV = "sme_ledger_test_monthly_summary.csv"
ledger.to_csv(LEDGER_CSV, index=False)
monthly_summary = ledger.groupby("month", dropna=False)[
    ["income_kes", "expense_kes", "net_cashflow_kes"]
].sum().reset_index()
monthly_summary.to_csv(SUMMARY_CSV, index=False)

print(f"Saved normalized ledger: {LEDGER_CSV}")
print(f"Saved monthly summary: {SUMMARY_CSV}")

/tmp/ipykernel_16/600078871.py:70: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({"": np.nan, "None": np.nan, "null": np.nan, "nan": np.nan}),
/tmp/ipykernel_16/600078871.py:70: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({"": np.nan, "None": np.nan, "null": np.nan, "nan": np.nan}),
/tmp/ipykernel_16/600078871.py:70: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({"": np.nan, "None": np.nan, "null": np.nan, "nan": np.nan}),

# SME-Ledger Test Data — Financial Dashboard

**Rows:** 50 &nbsp; | &nbsp; **Income:** KES 0.00 &nbsp; | &nbsp; **Expenses:** KES 0.00 &nbsp; | &nbsp; **Net cash flow:** KES 0.00

                           Metric Value
0                    Transactions    50
1              Total income (KES)  0.00
2            Total expenses (KES)  0.00
3             Net cash flow (KES)  0.00
4       Average transaction (KES)   N/A
5  Latest extracted balance (KES)   N/A
6          Income / expense ratio   N/A

HBox(children=(Dropdown(description='Entity:', options=('All', 'Unknown'), value='All'), Dropdown(description=…

Output()

## Normalized transaction ledger

,source_row,sms,latency_seconds,error,_parse_error,type,domain,entity,amount,balance,...,direction,date_parsed,month,income_kes,expense_kes,net_cashflow_kes,missing_amount,unknown_direction,missing_date,possible_duplicate
0,0,"TX03010001 Confirmed. You have received Ksh7,5...",3.460,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
1,1,"TX03010002 Confirmed. You have received Ksh2,5...",3.135,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
2,2,TX03020003 Confirmed. Ksh500.00 paid to Green ...,0.688,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
3,3,TX03020004 Confirmed. Ksh500.00 sent to David ...,0.697,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
4,4,"TX03030005 Confirmed. Ksh1,500.00 paid to Wang...",3.079,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
5,5,"TX03030006 Confirmed. Ksh1,000.00 paid to Airt...",0.662,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
6,6,"TX03040007 Confirmed. You have received Ksh2,5...",0.692,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
7,7,TX03040008 Confirmed. Ksh500.00 sent to Peter ...,2.931,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
8,8,"TX03050009 Confirmed. You have received Ksh7,5...",0.690,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
9,9,"TX03050010 Confirmed. You have received Ksh2,5...",0.671,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
10,10,TX03060011 Confirmed. Ksh800.00 withdrawn from...,7.497,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
11,11,"TX03060012 Confirmed. Ksh2,000.00 paid to Airt...",2.618,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
12,12,"TX03070013 Confirmed. You have received Ksh7,5...",2.926,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
13,13,"TX03070014 Confirmed. Ksh3,500.00 sent to Mary...",2.913,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
14,14,"TX03080015 Confirmed. Ksh7,500.00 paid to Airt...",2.851,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
15,15,"TX03080016 Confirmed. You have received Ksh1,5...",0.655,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
16,16,"TX03090017 Confirmed. Ksh1,250.00 paid to Gree...",0.659,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
17,17,"TX03090018 Confirmed. Ksh7,500.00 paid to Wang...",2.963,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
18,18,"TX03100019 Confirmed. You have received Ksh7,5...",0.677,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
19,19,"TX03100020 Confirmed. Ksh1,250.00 paid to Safa...",2.858,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
20,20,TX03110021 Confirmed. Ksh800.00 paid to Water ...,2.871,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
21,21,"TX03110022 Confirmed. You have received Ksh15,...",0.676,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
22,22,"TX03120023 Confirmed. Ksh3,500.00 paid to Quic...",0.668,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
23,23,"TX03120024 Confirmed. Ksh7,500.00 paid to KPLC...",2.995,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
24,24,"TX03130025 Confirmed. You have received Ksh1,5...",2.849,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
25,25,"TX03130026 Confirmed. Ksh3,500.00 paid to Zuku...",0.521,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
26,26,"TX03140027 Confirmed. Ksh1,000.00 sent to Mary...",2.834,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
27,27,"TX03140028 Confirmed. Fuliza loan of Ksh3,000....",2.916,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
28,28,TX03150029 Confirmed. Ksh500.00 paid to Airtel...,2.793,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
29,29,"TX03150030 Confirmed. You have received Ksh5,0...",2.956,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
30,30,TX03160031 Confirmed. Ksh800.00 paid to Water ...,0.529,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
31,31,"TX03160032 Confirmed. Fuliza loan of Ksh5,000....",2.948,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
32,32,"TX03170033 Confirmed. Ksh5,000.00 sent to John...",0.697,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
33,33,"TX03170034 Confirmed. Ksh1,250.00 paid to Safa...",2.872,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
34,34,"TX03180035 Confirmed. Ksh3,500.00 paid to Quic...",2.871,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
35,35,"TX03180036 Confirmed. You have received Ksh10,...",0.653,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
36,36,"TX03190037 Confirmed. Ksh5,000.00 sent to Ann ...",2.803,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
37,37,TX03190038 Confirmed. Ksh500.00 paid to KPLC v...,0.673,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
38,38,"TX03200039 Confirmed. You have received Ksh5,0...",2.859,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
39,39,"TX03200040 Confirmed. You have received Ksh3,0...",0.655,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
40,40,"TX03210041 Confirmed. Ksh2,500.00 withdrawn fr...",7.220,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
41,41,"TX03210042 Confirmed. Ksh2,500.00 paid to Naiv...",2.862,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
42,42,"TX03220043 Confirmed. You have received Ksh10,...",2.934,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
43,43,"TX03220044 Confirmed. You have received Ksh20,...",4.910,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
44,44,"TX03230045 Confirmed. You have received Ksh20,...",0.695,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
45,45,"TX03230046 Confirmed. Ksh3,500.00 paid to Naiv...",2.878,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
46,46,TX03240047 Confirmed. Ksh800.00 withdrawn from...,2.980,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
47,47,"TX03240048 Confirmed. Ksh2,500.00 paid to Wang...",0.649,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
48,48,"TX03250049 Confirmed. You have received Ksh15,...",0.676,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True
49,49,"TX03250050 Confirmed. Ksh3,500.00 paid to Wang...",2.970,None,Expecting value: line 1 column 1 (char 0),unknown,unknown,Unknown,NaN,NaN,...,Unknown,NaT,Unknown date,0.0,0.0,0.0,True,True,True,True

Saved normalized ledger: sme_ledger_test_analytics.csv
Saved monthly summary: sme_ledger_test_monthly_summary.csv